// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module sa_grid_store (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        fwd_right_dout,
        fwd_right_empty_n,
        fwd_right_read,
        fwd_right_num_data_valid,
        fwd_right_fifo_cap,
        fwd_down_dout,
        fwd_down_empty_n,
        fwd_down_read,
        fwd_down_num_data_valid,
        fwd_down_fifo_cap,
        xa_out_dout,
        xa_out_empty_n,
        xa_out_read,
        xa_out_num_data_valid,
        xa_out_fifo_cap,
        xb_out_dout,
        xb_out_empty_n,
        xb_out_read,
        xb_out_num_data_valid,
        xb_out_fifo_cap,
        c_mine_dout,
        c_mine_empty_n,
        c_mine_read,
        c_mine_num_data_valid,
        c_mine_fifo_cap,
        c_pass_dout,
        c_pass_empty_n,
        c_pass_read,
        c_pass_num_data_valid,
        c_pass_fifo_cap,
        out_right_TDATA,
        out_right_TVALID,
        out_right_TREADY,
        out_right_TKEEP,
        out_right_TSTRB,
        out_right_TLAST,
        out_down_TDATA,
        out_down_TVALID,
        out_down_TREADY,
        out_down_TKEEP,
        out_down_TSTRB,
        out_down_TLAST,
        pos_s_dout,
        pos_s_empty_n,
        pos_s_read,
        pos_s_num_data_valid,
        pos_s_fifo_cap
);

parameter    ap_ST_fsm_state1 = 20'd1;
parameter    ap_ST_fsm_state2 = 20'd2;
parameter    ap_ST_fsm_state3 = 20'd4;
parameter    ap_ST_fsm_state4 = 20'd8;
parameter    ap_ST_fsm_state5 = 20'd16;
parameter    ap_ST_fsm_state6 = 20'd32;
parameter    ap_ST_fsm_state7 = 20'd64;
parameter    ap_ST_fsm_state8 = 20'd128;
parameter    ap_ST_fsm_state9 = 20'd256;
parameter    ap_ST_fsm_state10 = 20'd512;
parameter    ap_ST_fsm_state11 = 20'd1024;
parameter    ap_ST_fsm_state12 = 20'd2048;
parameter    ap_ST_fsm_state13 = 20'd4096;
parameter    ap_ST_fsm_state14 = 20'd8192;
parameter    ap_ST_fsm_state15 = 20'd16384;
parameter    ap_ST_fsm_state16 = 20'd32768;
parameter    ap_ST_fsm_state17 = 20'd65536;
parameter    ap_ST_fsm_state18 = 20'd131072;
parameter    ap_ST_fsm_state19 = 20'd262144;
parameter    ap_ST_fsm_state20 = 20'd524288;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [32:0] fwd_right_dout;
input   fwd_right_empty_n;
output   fwd_right_read;
input  [3:0] fwd_right_num_data_valid;
input  [3:0] fwd_right_fifo_cap;
input  [32:0] fwd_down_dout;
input   fwd_down_empty_n;
output   fwd_down_read;
input  [3:0] fwd_down_num_data_valid;
input  [3:0] fwd_down_fifo_cap;
input  [31:0] xa_out_dout;
input   xa_out_empty_n;
output   xa_out_read;
input  [2:0] xa_out_num_data_valid;
input  [2:0] xa_out_fifo_cap;
input  [31:0] xb_out_dout;
input   xb_out_empty_n;
output   xb_out_read;
input  [2:0] xb_out_num_data_valid;
input  [2:0] xb_out_fifo_cap;
input  [31:0] c_mine_dout;
input   c_mine_empty_n;
output   c_mine_read;
input  [2:0] c_mine_num_data_valid;
input  [2:0] c_mine_fifo_cap;
input  [32:0] c_pass_dout;
input   c_pass_empty_n;
output   c_pass_read;
input  [4:0] c_pass_num_data_valid;
input  [4:0] c_pass_fifo_cap;
output  [31:0] out_right_TDATA;
output   out_right_TVALID;
input   out_right_TREADY;
output  [3:0] out_right_TKEEP;
output  [3:0] out_right_TSTRB;
output  [0:0] out_right_TLAST;
output  [31:0] out_down_TDATA;
output   out_down_TVALID;
input   out_down_TREADY;
output  [3:0] out_down_TKEEP;
output  [3:0] out_down_TSTRB;
output  [0:0] out_down_TLAST;
input  [7:0] pos_s_dout;
input   pos_s_empty_n;
output   pos_s_read;
input  [2:0] pos_s_num_data_valid;
input  [2:0] pos_s_fifo_cap;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg c_mine_read;
reg c_pass_read;
reg pos_s_read;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [19:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    out_right_TDATA_blk_n;
wire    ap_CS_fsm_state4;
reg   [0:0] is_lastcol_reg_680;
wire    ap_CS_fsm_state5;
wire    ap_CS_fsm_state9;
wire    ap_CS_fsm_state10;
reg    out_down_TDATA_blk_n;
reg   [0:0] is_lastrow_reg_675;
wire    ap_CS_fsm_state6;
wire    ap_CS_fsm_state15;
reg    pos_s_blk_n;
reg   [7:0] pos_reg_647;
reg    ap_block_state1;
wire   [3:0] trunc_ln373_fu_256_p1;
reg   [3:0] trunc_ln373_reg_652;
reg   [3:0] trunc_ln1_reg_661;
wire   [0:0] is_col0_fu_275_p2;
reg   [0:0] is_col0_reg_670;
wire    ap_CS_fsm_state2;
wire   [0:0] is_lastrow_fu_280_p2;
wire   [0:0] is_lastcol_fu_285_p2;
wire   [0:0] or_ln382_fu_290_p2;
reg   [0:0] or_ln382_reg_684;
wire   [0:0] or_ln383_fu_314_p2;
reg   [0:0] or_ln383_reg_688;
wire    ap_CS_fsm_state3;
wire    grp_store_Pipeline_OUT_PASS_fu_146_ap_done;
reg    ap_block_state3_on_subcall_done;
wire   [31:0] zext_ln9_fu_352_p1;
reg    ap_block_state4;
wire    grp_store_Pipeline_OUT_PASS1_fu_160_ap_done;
reg    ap_block_state4_on_subcall_done;
wire   [31:0] zext_ln9_1_fu_373_p1;
reg    ap_block_state5;
wire   [31:0] zext_ln409_fu_461_p1;
reg    ap_block_state9;
wire    grp_store_Pipeline_OUT_PASS_fu_146_ap_start;
wire    grp_store_Pipeline_OUT_PASS_fu_146_ap_idle;
wire    grp_store_Pipeline_OUT_PASS_fu_146_ap_ready;
wire    grp_store_Pipeline_OUT_PASS_fu_146_fwd_right_read;
wire    grp_store_Pipeline_OUT_PASS_fu_146_out_right_TREADY;
wire   [31:0] grp_store_Pipeline_OUT_PASS_fu_146_out_right_TDATA;
wire    grp_store_Pipeline_OUT_PASS_fu_146_out_right_TVALID;
wire   [3:0] grp_store_Pipeline_OUT_PASS_fu_146_out_right_TKEEP;
wire   [3:0] grp_store_Pipeline_OUT_PASS_fu_146_out_right_TSTRB;
wire   [0:0] grp_store_Pipeline_OUT_PASS_fu_146_out_right_TLAST;
wire    grp_store_Pipeline_OUT_PASS1_fu_160_ap_start;
wire    grp_store_Pipeline_OUT_PASS1_fu_160_ap_idle;
wire    grp_store_Pipeline_OUT_PASS1_fu_160_ap_ready;
wire    grp_store_Pipeline_OUT_PASS1_fu_160_fwd_down_read;
wire    grp_store_Pipeline_OUT_PASS1_fu_160_out_down_TREADY;
wire   [31:0] grp_store_Pipeline_OUT_PASS1_fu_160_out_down_TDATA;
wire    grp_store_Pipeline_OUT_PASS1_fu_160_out_down_TVALID;
wire   [3:0] grp_store_Pipeline_OUT_PASS1_fu_160_out_down_TKEEP;
wire   [3:0] grp_store_Pipeline_OUT_PASS1_fu_160_out_down_TSTRB;
wire   [0:0] grp_store_Pipeline_OUT_PASS1_fu_160_out_down_TLAST;
wire    grp_store_Pipeline_XCROSS_fu_174_ap_start;
wire    grp_store_Pipeline_XCROSS_fu_174_ap_done;
wire    grp_store_Pipeline_XCROSS_fu_174_ap_idle;
wire    grp_store_Pipeline_XCROSS_fu_174_ap_ready;
wire    grp_store_Pipeline_XCROSS_fu_174_xa_out_read;
wire    grp_store_Pipeline_XCROSS_fu_174_out_right_TREADY;
wire    grp_store_Pipeline_XCROSS_fu_174_xb_out_read;
wire    grp_store_Pipeline_XCROSS_fu_174_out_down_TREADY;
wire   [31:0] grp_store_Pipeline_XCROSS_fu_174_out_right_TDATA;
wire    grp_store_Pipeline_XCROSS_fu_174_out_right_TVALID;
wire   [3:0] grp_store_Pipeline_XCROSS_fu_174_out_right_TKEEP;
wire   [3:0] grp_store_Pipeline_XCROSS_fu_174_out_right_TSTRB;
wire   [0:0] grp_store_Pipeline_XCROSS_fu_174_out_right_TLAST;
wire   [31:0] grp_store_Pipeline_XCROSS_fu_174_out_down_TDATA;
wire    grp_store_Pipeline_XCROSS_fu_174_out_down_TVALID;
wire   [3:0] grp_store_Pipeline_XCROSS_fu_174_out_down_TKEEP;
wire   [3:0] grp_store_Pipeline_XCROSS_fu_174_out_down_TSTRB;
wire   [0:0] grp_store_Pipeline_XCROSS_fu_174_out_down_TLAST;
wire    grp_store_Pipeline_OUT_PASS3_fu_200_ap_start;
wire    grp_store_Pipeline_OUT_PASS3_fu_200_ap_done;
wire    grp_store_Pipeline_OUT_PASS3_fu_200_ap_idle;
wire    grp_store_Pipeline_OUT_PASS3_fu_200_ap_ready;
wire    grp_store_Pipeline_OUT_PASS3_fu_200_c_pass_read;
wire    grp_store_Pipeline_OUT_PASS3_fu_200_out_right_TREADY;
wire   [31:0] grp_store_Pipeline_OUT_PASS3_fu_200_out_right_TDATA;
wire    grp_store_Pipeline_OUT_PASS3_fu_200_out_right_TVALID;
wire   [3:0] grp_store_Pipeline_OUT_PASS3_fu_200_out_right_TKEEP;
wire   [3:0] grp_store_Pipeline_OUT_PASS3_fu_200_out_right_TSTRB;
wire   [0:0] grp_store_Pipeline_OUT_PASS3_fu_200_out_right_TLAST;
wire    grp_store_Pipeline_MINE4_fu_214_ap_start;
wire    grp_store_Pipeline_MINE4_fu_214_ap_done;
wire    grp_store_Pipeline_MINE4_fu_214_ap_idle;
wire    grp_store_Pipeline_MINE4_fu_214_ap_ready;
wire    grp_store_Pipeline_MINE4_fu_214_c_mine_read;
wire    grp_store_Pipeline_MINE4_fu_214_out_right_TREADY;
wire   [31:0] grp_store_Pipeline_MINE4_fu_214_out_right_TDATA;
wire    grp_store_Pipeline_MINE4_fu_214_out_right_TVALID;
wire   [3:0] grp_store_Pipeline_MINE4_fu_214_out_right_TKEEP;
wire   [3:0] grp_store_Pipeline_MINE4_fu_214_out_right_TSTRB;
wire   [0:0] grp_store_Pipeline_MINE4_fu_214_out_right_TLAST;
wire    grp_store_Pipeline_OUT_PASS2_fu_228_ap_start;
wire    grp_store_Pipeline_OUT_PASS2_fu_228_ap_done;
wire    grp_store_Pipeline_OUT_PASS2_fu_228_ap_idle;
wire    grp_store_Pipeline_OUT_PASS2_fu_228_ap_ready;
wire    grp_store_Pipeline_OUT_PASS2_fu_228_c_pass_read;
wire    grp_store_Pipeline_OUT_PASS2_fu_228_out_down_TREADY;
wire   [31:0] grp_store_Pipeline_OUT_PASS2_fu_228_out_down_TDATA;
wire    grp_store_Pipeline_OUT_PASS2_fu_228_out_down_TVALID;
wire   [3:0] grp_store_Pipeline_OUT_PASS2_fu_228_out_down_TKEEP;
wire   [3:0] grp_store_Pipeline_OUT_PASS2_fu_228_out_down_TSTRB;
wire   [0:0] grp_store_Pipeline_OUT_PASS2_fu_228_out_down_TLAST;
wire    grp_store_Pipeline_MINE_fu_242_ap_start;
wire    grp_store_Pipeline_MINE_fu_242_ap_done;
wire    grp_store_Pipeline_MINE_fu_242_ap_idle;
wire    grp_store_Pipeline_MINE_fu_242_ap_ready;
wire    grp_store_Pipeline_MINE_fu_242_c_mine_read;
wire    grp_store_Pipeline_MINE_fu_242_out_down_TREADY;
wire   [31:0] grp_store_Pipeline_MINE_fu_242_out_down_TDATA;
wire    grp_store_Pipeline_MINE_fu_242_out_down_TVALID;
wire   [3:0] grp_store_Pipeline_MINE_fu_242_out_down_TKEEP;
wire   [3:0] grp_store_Pipeline_MINE_fu_242_out_down_TSTRB;
wire   [0:0] grp_store_Pipeline_MINE_fu_242_out_down_TLAST;
reg    grp_store_Pipeline_OUT_PASS_fu_146_ap_start_reg;
reg   [31:0] out_right_TDATA_reg;
reg   [3:0] out_right_TKEEP_reg;
reg   [3:0] out_right_TSTRB_reg;
reg   [0:0] out_right_TLAST_reg;
reg    grp_store_Pipeline_OUT_PASS1_fu_160_ap_start_reg;
reg   [31:0] out_down_TDATA_reg;
reg   [3:0] out_down_TKEEP_reg;
reg   [3:0] out_down_TSTRB_reg;
reg   [0:0] out_down_TLAST_reg;
reg    grp_store_Pipeline_XCROSS_fu_174_ap_start_reg;
wire    ap_CS_fsm_state7;
wire    ap_CS_fsm_state8;
reg    grp_store_Pipeline_OUT_PASS3_fu_200_ap_start_reg;
wire    ap_CS_fsm_state11;
wire    ap_CS_fsm_state12;
reg    grp_store_Pipeline_MINE4_fu_214_ap_start_reg;
wire    ap_CS_fsm_state13;
wire    ap_CS_fsm_state14;
reg    grp_store_Pipeline_OUT_PASS2_fu_228_ap_start_reg;
wire    ap_CS_fsm_state16;
wire    ap_CS_fsm_state17;
reg    grp_store_Pipeline_MINE_fu_242_ap_start_reg;
wire    ap_CS_fsm_state18;
wire    ap_CS_fsm_state19;
wire   [0:0] is_row0_fu_270_p2;
wire   [3:0] add_ln14_fu_336_p2;
wire   [30:0] w_data_fu_341_p5;
wire   [3:0] add_ln13_fu_357_p2;
wire   [30:0] w_data_2_fu_362_p5;
wire   [30:0] w_data_3_fu_452_p4;
wire    ap_CS_fsm_state20;
wire    regslice_both_out_right_V_data_V_U_apdone_blk;
wire    regslice_both_out_down_V_data_V_U_apdone_blk;
reg    ap_block_state20;
reg   [19:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
reg    ap_ST_fsm_state5_blk;
reg    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
reg    ap_ST_fsm_state8_blk;
reg    ap_ST_fsm_state9_blk;
reg    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
reg    ap_ST_fsm_state12_blk;
wire    ap_ST_fsm_state13_blk;
reg    ap_ST_fsm_state14_blk;
reg    ap_ST_fsm_state15_blk;
wire    ap_ST_fsm_state16_blk;
reg    ap_ST_fsm_state17_blk;
wire    ap_ST_fsm_state18_blk;
reg    ap_ST_fsm_state19_blk;
reg    ap_ST_fsm_state20_blk;
reg   [31:0] out_right_TDATA_int_regslice;
reg    out_right_TVALID_int_regslice;
wire    out_right_TREADY_int_regslice;
wire    regslice_both_out_right_V_data_V_U_vld_out;
wire    regslice_both_out_right_V_keep_V_U_apdone_blk;
reg   [3:0] out_right_TKEEP_int_regslice;
wire    regslice_both_out_right_V_keep_V_U_ack_in_dummy;
wire    regslice_both_out_right_V_keep_V_U_vld_out;
wire    regslice_both_out_right_V_strb_V_U_apdone_blk;
reg   [3:0] out_right_TSTRB_int_regslice;
wire    regslice_both_out_right_V_strb_V_U_ack_in_dummy;
wire    regslice_both_out_right_V_strb_V_U_vld_out;
wire    regslice_both_out_right_V_last_V_U_apdone_blk;
reg   [0:0] out_right_TLAST_int_regslice;
wire    regslice_both_out_right_V_last_V_U_ack_in_dummy;
wire    regslice_both_out_right_V_last_V_U_vld_out;
reg   [31:0] out_down_TDATA_int_regslice;
reg    out_down_TVALID_int_regslice;
wire    out_down_TREADY_int_regslice;
wire    regslice_both_out_down_V_data_V_U_vld_out;
wire    regslice_both_out_down_V_keep_V_U_apdone_blk;
reg   [3:0] out_down_TKEEP_int_regslice;
wire    regslice_both_out_down_V_keep_V_U_ack_in_dummy;
wire    regslice_both_out_down_V_keep_V_U_vld_out;
wire    regslice_both_out_down_V_strb_V_U_apdone_blk;
reg   [3:0] out_down_TSTRB_int_regslice;
wire    regslice_both_out_down_V_strb_V_U_ack_in_dummy;
wire    regslice_both_out_down_V_strb_V_U_vld_out;
wire    regslice_both_out_down_V_last_V_U_apdone_blk;
reg   [0:0] out_down_TLAST_int_regslice;
wire    regslice_both_out_down_V_last_V_U_ack_in_dummy;
wire    regslice_both_out_down_V_last_V_U_vld_out;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 20'd1;
#0 grp_store_Pipeline_OUT_PASS_fu_146_ap_start_reg = 1'b0;
#0 grp_store_Pipeline_OUT_PASS1_fu_160_ap_start_reg = 1'b0;
#0 grp_store_Pipeline_XCROSS_fu_174_ap_start_reg = 1'b0;
#0 grp_store_Pipeline_OUT_PASS3_fu_200_ap_start_reg = 1'b0;
#0 grp_store_Pipeline_MINE4_fu_214_ap_start_reg = 1'b0;
#0 grp_store_Pipeline_OUT_PASS2_fu_228_ap_start_reg = 1'b0;
#0 grp_store_Pipeline_MINE_fu_242_ap_start_reg = 1'b0;
end

sa_grid_store_Pipeline_OUT_PASS grp_store_Pipeline_OUT_PASS_fu_146(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_store_Pipeline_OUT_PASS_fu_146_ap_start),
    .ap_done(grp_store_Pipeline_OUT_PASS_fu_146_ap_done),
    .ap_idle(grp_store_Pipeline_OUT_PASS_fu_146_ap_idle),
    .ap_ready(grp_store_Pipeline_OUT_PASS_fu_146_ap_ready),
    .fwd_right_dout(fwd_right_dout),
    .fwd_right_empty_n(fwd_right_empty_n),
    .fwd_right_read(grp_store_Pipeline_OUT_PASS_fu_146_fwd_right_read),
    .fwd_right_num_data_valid(4'd0),
    .fwd_right_fifo_cap(4'd0),
    .out_right_TREADY(grp_store_Pipeline_OUT_PASS_fu_146_out_right_TREADY),
    .out_right_TDATA(grp_store_Pipeline_OUT_PASS_fu_146_out_right_TDATA),
    .out_right_TVALID(grp_store_Pipeline_OUT_PASS_fu_146_out_right_TVALID),
    .out_right_TKEEP(grp_store_Pipeline_OUT_PASS_fu_146_out_right_TKEEP),
    .out_right_TSTRB(grp_store_Pipeline_OUT_PASS_fu_146_out_right_TSTRB),
    .out_right_TLAST(grp_store_Pipeline_OUT_PASS_fu_146_out_right_TLAST)
);

sa_grid_store_Pipeline_OUT_PASS1 grp_store_Pipeline_OUT_PASS1_fu_160(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_store_Pipeline_OUT_PASS1_fu_160_ap_start),
    .ap_done(grp_store_Pipeline_OUT_PASS1_fu_160_ap_done),
    .ap_idle(grp_store_Pipeline_OUT_PASS1_fu_160_ap_idle),
    .ap_ready(grp_store_Pipeline_OUT_PASS1_fu_160_ap_ready),
    .fwd_down_dout(fwd_down_dout),
    .fwd_down_empty_n(fwd_down_empty_n),
    .fwd_down_read(grp_store_Pipeline_OUT_PASS1_fu_160_fwd_down_read),
    .fwd_down_num_data_valid(4'd0),
    .fwd_down_fifo_cap(4'd0),
    .out_down_TREADY(grp_store_Pipeline_OUT_PASS1_fu_160_out_down_TREADY),
    .out_down_TDATA(grp_store_Pipeline_OUT_PASS1_fu_160_out_down_TDATA),
    .out_down_TVALID(grp_store_Pipeline_OUT_PASS1_fu_160_out_down_TVALID),
    .out_down_TKEEP(grp_store_Pipeline_OUT_PASS1_fu_160_out_down_TKEEP),
    .out_down_TSTRB(grp_store_Pipeline_OUT_PASS1_fu_160_out_down_TSTRB),
    .out_down_TLAST(grp_store_Pipeline_OUT_PASS1_fu_160_out_down_TLAST)
);

sa_grid_store_Pipeline_XCROSS grp_store_Pipeline_XCROSS_fu_174(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_store_Pipeline_XCROSS_fu_174_ap_start),
    .ap_done(grp_store_Pipeline_XCROSS_fu_174_ap_done),
    .ap_idle(grp_store_Pipeline_XCROSS_fu_174_ap_idle),
    .ap_ready(grp_store_Pipeline_XCROSS_fu_174_ap_ready),
    .xa_out_dout(xa_out_dout),
    .xa_out_empty_n(xa_out_empty_n),
    .xa_out_read(grp_store_Pipeline_XCROSS_fu_174_xa_out_read),
    .xa_out_num_data_valid(3'd0),
    .xa_out_fifo_cap(3'd0),
    .out_right_TREADY(grp_store_Pipeline_XCROSS_fu_174_out_right_TREADY),
    .xb_out_dout(xb_out_dout),
    .xb_out_empty_n(xb_out_empty_n),
    .xb_out_read(grp_store_Pipeline_XCROSS_fu_174_xb_out_read),
    .xb_out_num_data_valid(3'd0),
    .xb_out_fifo_cap(3'd0),
    .out_down_TREADY(grp_store_Pipeline_XCROSS_fu_174_out_down_TREADY),
    .out_right_TDATA(grp_store_Pipeline_XCROSS_fu_174_out_right_TDATA),
    .out_right_TVALID(grp_store_Pipeline_XCROSS_fu_174_out_right_TVALID),
    .out_right_TKEEP(grp_store_Pipeline_XCROSS_fu_174_out_right_TKEEP),
    .out_right_TSTRB(grp_store_Pipeline_XCROSS_fu_174_out_right_TSTRB),
    .out_right_TLAST(grp_store_Pipeline_XCROSS_fu_174_out_right_TLAST),
    .out_down_TDATA(grp_store_Pipeline_XCROSS_fu_174_out_down_TDATA),
    .out_down_TVALID(grp_store_Pipeline_XCROSS_fu_174_out_down_TVALID),
    .out_down_TKEEP(grp_store_Pipeline_XCROSS_fu_174_out_down_TKEEP),
    .out_down_TSTRB(grp_store_Pipeline_XCROSS_fu_174_out_down_TSTRB),
    .out_down_TLAST(grp_store_Pipeline_XCROSS_fu_174_out_down_TLAST),
    .empty(trunc_ln373_reg_652),
    .trunc_ln1(trunc_ln1_reg_661)
);

sa_grid_store_Pipeline_OUT_PASS3 grp_store_Pipeline_OUT_PASS3_fu_200(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_store_Pipeline_OUT_PASS3_fu_200_ap_start),
    .ap_done(grp_store_Pipeline_OUT_PASS3_fu_200_ap_done),
    .ap_idle(grp_store_Pipeline_OUT_PASS3_fu_200_ap_idle),
    .ap_ready(grp_store_Pipeline_OUT_PASS3_fu_200_ap_ready),
    .c_pass_dout(c_pass_dout),
    .c_pass_empty_n(c_pass_empty_n),
    .c_pass_read(grp_store_Pipeline_OUT_PASS3_fu_200_c_pass_read),
    .c_pass_num_data_valid(5'd0),
    .c_pass_fifo_cap(5'd0),
    .out_right_TREADY(grp_store_Pipeline_OUT_PASS3_fu_200_out_right_TREADY),
    .out_right_TDATA(grp_store_Pipeline_OUT_PASS3_fu_200_out_right_TDATA),
    .out_right_TVALID(grp_store_Pipeline_OUT_PASS3_fu_200_out_right_TVALID),
    .out_right_TKEEP(grp_store_Pipeline_OUT_PASS3_fu_200_out_right_TKEEP),
    .out_right_TSTRB(grp_store_Pipeline_OUT_PASS3_fu_200_out_right_TSTRB),
    .out_right_TLAST(grp_store_Pipeline_OUT_PASS3_fu_200_out_right_TLAST)
);

sa_grid_store_Pipeline_MINE4 grp_store_Pipeline_MINE4_fu_214(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_store_Pipeline_MINE4_fu_214_ap_start),
    .ap_done(grp_store_Pipeline_MINE4_fu_214_ap_done),
    .ap_idle(grp_store_Pipeline_MINE4_fu_214_ap_idle),
    .ap_ready(grp_store_Pipeline_MINE4_fu_214_ap_ready),
    .c_mine_dout(c_mine_dout),
    .c_mine_empty_n(c_mine_empty_n),
    .c_mine_read(grp_store_Pipeline_MINE4_fu_214_c_mine_read),
    .c_mine_num_data_valid(3'd0),
    .c_mine_fifo_cap(3'd0),
    .out_right_TREADY(grp_store_Pipeline_MINE4_fu_214_out_right_TREADY),
    .out_right_TDATA(grp_store_Pipeline_MINE4_fu_214_out_right_TDATA),
    .out_right_TVALID(grp_store_Pipeline_MINE4_fu_214_out_right_TVALID),
    .out_right_TKEEP(grp_store_Pipeline_MINE4_fu_214_out_right_TKEEP),
    .out_right_TSTRB(grp_store_Pipeline_MINE4_fu_214_out_right_TSTRB),
    .out_right_TLAST(grp_store_Pipeline_MINE4_fu_214_out_right_TLAST)
);

sa_grid_store_Pipeline_OUT_PASS2 grp_store_Pipeline_OUT_PASS2_fu_228(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_store_Pipeline_OUT_PASS2_fu_228_ap_start),
    .ap_done(grp_store_Pipeline_OUT_PASS2_fu_228_ap_done),
    .ap_idle(grp_store_Pipeline_OUT_PASS2_fu_228_ap_idle),
    .ap_ready(grp_store_Pipeline_OUT_PASS2_fu_228_ap_ready),
    .c_pass_dout(c_pass_dout),
    .c_pass_empty_n(c_pass_empty_n),
    .c_pass_read(grp_store_Pipeline_OUT_PASS2_fu_228_c_pass_read),
    .c_pass_num_data_valid(5'd0),
    .c_pass_fifo_cap(5'd0),
    .out_down_TREADY(grp_store_Pipeline_OUT_PASS2_fu_228_out_down_TREADY),
    .out_down_TDATA(grp_store_Pipeline_OUT_PASS2_fu_228_out_down_TDATA),
    .out_down_TVALID(grp_store_Pipeline_OUT_PASS2_fu_228_out_down_TVALID),
    .out_down_TKEEP(grp_store_Pipeline_OUT_PASS2_fu_228_out_down_TKEEP),
    .out_down_TSTRB(grp_store_Pipeline_OUT_PASS2_fu_228_out_down_TSTRB),
    .out_down_TLAST(grp_store_Pipeline_OUT_PASS2_fu_228_out_down_TLAST)
);

sa_grid_store_Pipeline_MINE grp_store_Pipeline_MINE_fu_242(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_store_Pipeline_MINE_fu_242_ap_start),
    .ap_done(grp_store_Pipeline_MINE_fu_242_ap_done),
    .ap_idle(grp_store_Pipeline_MINE_fu_242_ap_idle),
    .ap_ready(grp_store_Pipeline_MINE_fu_242_ap_ready),
    .c_mine_dout(c_mine_dout),
    .c_mine_empty_n(c_mine_empty_n),
    .c_mine_read(grp_store_Pipeline_MINE_fu_242_c_mine_read),
    .c_mine_num_data_valid(3'd0),
    .c_mine_fifo_cap(3'd0),
    .out_down_TREADY(grp_store_Pipeline_MINE_fu_242_out_down_TREADY),
    .out_down_TDATA(grp_store_Pipeline_MINE_fu_242_out_down_TDATA),
    .out_down_TVALID(grp_store_Pipeline_MINE_fu_242_out_down_TVALID),
    .out_down_TKEEP(grp_store_Pipeline_MINE_fu_242_out_down_TKEEP),
    .out_down_TSTRB(grp_store_Pipeline_MINE_fu_242_out_down_TSTRB),
    .out_down_TLAST(grp_store_Pipeline_MINE_fu_242_out_down_TLAST)
);

sa_grid_regslice_both #(
    .DataWidth( 32 ))
regslice_both_out_right_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(out_right_TDATA_int_regslice),
    .vld_in(out_right_TVALID_int_regslice),
    .ack_in(out_right_TREADY_int_regslice),
    .data_out(out_right_TDATA),
    .vld_out(regslice_both_out_right_V_data_V_U_vld_out),
    .ack_out(out_right_TREADY),
    .apdone_blk(regslice_both_out_right_V_data_V_U_apdone_blk)
);

sa_grid_regslice_both #(
    .DataWidth( 4 ))
regslice_both_out_right_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(out_right_TKEEP_int_regslice),
    .vld_in(out_right_TVALID_int_regslice),
    .ack_in(regslice_both_out_right_V_keep_V_U_ack_in_dummy),
    .data_out(out_right_TKEEP),
    .vld_out(regslice_both_out_right_V_keep_V_U_vld_out),
    .ack_out(out_right_TREADY),
    .apdone_blk(regslice_both_out_right_V_keep_V_U_apdone_blk)
);

sa_grid_regslice_both #(
    .DataWidth( 4 ))
regslice_both_out_right_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(out_right_TSTRB_int_regslice),
    .vld_in(out_right_TVALID_int_regslice),
    .ack_in(regslice_both_out_right_V_strb_V_U_ack_in_dummy),
    .data_out(out_right_TSTRB),
    .vld_out(regslice_both_out_right_V_strb_V_U_vld_out),
    .ack_out(out_right_TREADY),
    .apdone_blk(regslice_both_out_right_V_strb_V_U_apdone_blk)
);

sa_grid_regslice_both #(
    .DataWidth( 1 ))
regslice_both_out_right_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(out_right_TLAST_int_regslice),
    .vld_in(out_right_TVALID_int_regslice),
    .ack_in(regslice_both_out_right_V_last_V_U_ack_in_dummy),
    .data_out(out_right_TLAST),
    .vld_out(regslice_both_out_right_V_last_V_U_vld_out),
    .ack_out(out_right_TREADY),
    .apdone_blk(regslice_both_out_right_V_last_V_U_apdone_blk)
);

sa_grid_regslice_both #(
    .DataWidth( 32 ))
regslice_both_out_down_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(out_down_TDATA_int_regslice),
    .vld_in(out_down_TVALID_int_regslice),
    .ack_in(out_down_TREADY_int_regslice),
    .data_out(out_down_TDATA),
    .vld_out(regslice_both_out_down_V_data_V_U_vld_out),
    .ack_out(out_down_TREADY),
    .apdone_blk(regslice_both_out_down_V_data_V_U_apdone_blk)
);

sa_grid_regslice_both #(
    .DataWidth( 4 ))
regslice_both_out_down_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(out_down_TKEEP_int_regslice),
    .vld_in(out_down_TVALID_int_regslice),
    .ack_in(regslice_both_out_down_V_keep_V_U_ack_in_dummy),
    .data_out(out_down_TKEEP),
    .vld_out(regslice_both_out_down_V_keep_V_U_vld_out),
    .ack_out(out_down_TREADY),
    .apdone_blk(regslice_both_out_down_V_keep_V_U_apdone_blk)
);

sa_grid_regslice_both #(
    .DataWidth( 4 ))
regslice_both_out_down_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(out_down_TSTRB_int_regslice),
    .vld_in(out_down_TVALID_int_regslice),
    .ack_in(regslice_both_out_down_V_strb_V_U_ack_in_dummy),
    .data_out(out_down_TSTRB),
    .vld_out(regslice_both_out_down_V_strb_V_U_vld_out),
    .ack_out(out_down_TREADY),
    .apdone_blk(regslice_both_out_down_V_strb_V_U_apdone_blk)
);

sa_grid_regslice_both #(
    .DataWidth( 1 ))
regslice_both_out_down_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(out_down_TLAST_int_regslice),
    .vld_in(out_down_TVALID_int_regslice),
    .ack_in(regslice_both_out_down_V_last_V_U_ack_in_dummy),
    .data_out(out_down_TLAST),
    .vld_out(regslice_both_out_down_V_last_V_U_vld_out),
    .ack_out(out_down_TREADY),
    .apdone_blk(regslice_both_out_down_V_last_V_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_state20) & (1'b0 == ap_block_state20))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_store_Pipeline_MINE4_fu_214_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state13)) begin
            grp_store_Pipeline_MINE4_fu_214_ap_start_reg <= 1'b1;
        end else if ((grp_store_Pipeline_MINE4_fu_214_ap_ready == 1'b1)) begin
            grp_store_Pipeline_MINE4_fu_214_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_store_Pipeline_MINE_fu_242_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state18)) begin
            grp_store_Pipeline_MINE_fu_242_ap_start_reg <= 1'b1;
        end else if ((grp_store_Pipeline_MINE_fu_242_ap_ready == 1'b1)) begin
            grp_store_Pipeline_MINE_fu_242_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_store_Pipeline_OUT_PASS1_fu_160_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state3) & (or_ln383_fu_314_p2 == 1'd0) & (1'b0 == ap_block_state3_on_subcall_done))) begin
            grp_store_Pipeline_OUT_PASS1_fu_160_ap_start_reg <= 1'b1;
        end else if ((grp_store_Pipeline_OUT_PASS1_fu_160_ap_ready == 1'b1)) begin
            grp_store_Pipeline_OUT_PASS1_fu_160_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_store_Pipeline_OUT_PASS2_fu_228_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state16)) begin
            grp_store_Pipeline_OUT_PASS2_fu_228_ap_start_reg <= 1'b1;
        end else if ((grp_store_Pipeline_OUT_PASS2_fu_228_ap_ready == 1'b1)) begin
            grp_store_Pipeline_OUT_PASS2_fu_228_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_store_Pipeline_OUT_PASS3_fu_200_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state11)) begin
            grp_store_Pipeline_OUT_PASS3_fu_200_ap_start_reg <= 1'b1;
        end else if ((grp_store_Pipeline_OUT_PASS3_fu_200_ap_ready == 1'b1)) begin
            grp_store_Pipeline_OUT_PASS3_fu_200_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_store_Pipeline_OUT_PASS_fu_146_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state2) & (or_ln382_fu_290_p2 == 1'd0))) begin
            grp_store_Pipeline_OUT_PASS_fu_146_ap_start_reg <= 1'b1;
        end else if ((grp_store_Pipeline_OUT_PASS_fu_146_ap_ready == 1'b1)) begin
            grp_store_Pipeline_OUT_PASS_fu_146_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_store_Pipeline_XCROSS_fu_174_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state7)) begin
            grp_store_Pipeline_XCROSS_fu_174_ap_start_reg <= 1'b1;
        end else if ((grp_store_Pipeline_XCROSS_fu_174_ap_ready == 1'b1)) begin
            grp_store_Pipeline_XCROSS_fu_174_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((grp_store_Pipeline_MINE_fu_242_out_down_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state19))) begin
        out_down_TDATA_reg <= grp_store_Pipeline_MINE_fu_242_out_down_TDATA;
    end else if (((grp_store_Pipeline_OUT_PASS2_fu_228_out_down_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state17))) begin
        out_down_TDATA_reg <= grp_store_Pipeline_OUT_PASS2_fu_228_out_down_TDATA;
    end else if (((grp_store_Pipeline_XCROSS_fu_174_out_down_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state8))) begin
        out_down_TDATA_reg <= grp_store_Pipeline_XCROSS_fu_174_out_down_TDATA;
    end else if (((grp_store_Pipeline_OUT_PASS1_fu_160_out_down_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state4) & (or_ln383_reg_688 == 1'd0))) begin
        out_down_TDATA_reg <= grp_store_Pipeline_OUT_PASS1_fu_160_out_down_TDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_store_Pipeline_MINE_fu_242_out_down_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state19))) begin
        out_down_TKEEP_reg <= grp_store_Pipeline_MINE_fu_242_out_down_TKEEP;
    end else if (((grp_store_Pipeline_OUT_PASS2_fu_228_out_down_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state17))) begin
        out_down_TKEEP_reg <= grp_store_Pipeline_OUT_PASS2_fu_228_out_down_TKEEP;
    end else if (((grp_store_Pipeline_XCROSS_fu_174_out_down_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state8))) begin
        out_down_TKEEP_reg <= grp_store_Pipeline_XCROSS_fu_174_out_down_TKEEP;
    end else if (((grp_store_Pipeline_OUT_PASS1_fu_160_out_down_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state4) & (or_ln383_reg_688 == 1'd0))) begin
        out_down_TKEEP_reg <= grp_store_Pipeline_OUT_PASS1_fu_160_out_down_TKEEP;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_store_Pipeline_MINE_fu_242_out_down_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state19))) begin
        out_down_TLAST_reg <= grp_store_Pipeline_MINE_fu_242_out_down_TLAST;
    end else if (((grp_store_Pipeline_OUT_PASS2_fu_228_out_down_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state17))) begin
        out_down_TLAST_reg <= grp_store_Pipeline_OUT_PASS2_fu_228_out_down_TLAST;
    end else if (((grp_store_Pipeline_XCROSS_fu_174_out_down_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state8))) begin
        out_down_TLAST_reg <= grp_store_Pipeline_XCROSS_fu_174_out_down_TLAST;
    end else if (((grp_store_Pipeline_OUT_PASS1_fu_160_out_down_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state4) & (or_ln383_reg_688 == 1'd0))) begin
        out_down_TLAST_reg <= grp_store_Pipeline_OUT_PASS1_fu_160_out_down_TLAST;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_store_Pipeline_MINE_fu_242_out_down_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state19))) begin
        out_down_TSTRB_reg <= grp_store_Pipeline_MINE_fu_242_out_down_TSTRB;
    end else if (((grp_store_Pipeline_OUT_PASS2_fu_228_out_down_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state17))) begin
        out_down_TSTRB_reg <= grp_store_Pipeline_OUT_PASS2_fu_228_out_down_TSTRB;
    end else if (((grp_store_Pipeline_XCROSS_fu_174_out_down_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state8))) begin
        out_down_TSTRB_reg <= grp_store_Pipeline_XCROSS_fu_174_out_down_TSTRB;
    end else if (((grp_store_Pipeline_OUT_PASS1_fu_160_out_down_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state4) & (or_ln383_reg_688 == 1'd0))) begin
        out_down_TSTRB_reg <= grp_store_Pipeline_OUT_PASS1_fu_160_out_down_TSTRB;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_store_Pipeline_MINE4_fu_214_out_right_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state14))) begin
        out_right_TDATA_reg <= grp_store_Pipeline_MINE4_fu_214_out_right_TDATA;
    end else if (((grp_store_Pipeline_OUT_PASS3_fu_200_out_right_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state12))) begin
        out_right_TDATA_reg <= grp_store_Pipeline_OUT_PASS3_fu_200_out_right_TDATA;
    end else if (((grp_store_Pipeline_XCROSS_fu_174_out_right_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state8))) begin
        out_right_TDATA_reg <= grp_store_Pipeline_XCROSS_fu_174_out_right_TDATA;
    end else if (((grp_store_Pipeline_OUT_PASS_fu_146_out_right_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state3) & (or_ln382_reg_684 == 1'd0))) begin
        out_right_TDATA_reg <= grp_store_Pipeline_OUT_PASS_fu_146_out_right_TDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_store_Pipeline_MINE4_fu_214_out_right_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state14))) begin
        out_right_TKEEP_reg <= grp_store_Pipeline_MINE4_fu_214_out_right_TKEEP;
    end else if (((grp_store_Pipeline_OUT_PASS3_fu_200_out_right_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state12))) begin
        out_right_TKEEP_reg <= grp_store_Pipeline_OUT_PASS3_fu_200_out_right_TKEEP;
    end else if (((grp_store_Pipeline_XCROSS_fu_174_out_right_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state8))) begin
        out_right_TKEEP_reg <= grp_store_Pipeline_XCROSS_fu_174_out_right_TKEEP;
    end else if (((grp_store_Pipeline_OUT_PASS_fu_146_out_right_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state3) & (or_ln382_reg_684 == 1'd0))) begin
        out_right_TKEEP_reg <= grp_store_Pipeline_OUT_PASS_fu_146_out_right_TKEEP;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_store_Pipeline_MINE4_fu_214_out_right_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state14))) begin
        out_right_TLAST_reg <= grp_store_Pipeline_MINE4_fu_214_out_right_TLAST;
    end else if (((grp_store_Pipeline_OUT_PASS3_fu_200_out_right_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state12))) begin
        out_right_TLAST_reg <= grp_store_Pipeline_OUT_PASS3_fu_200_out_right_TLAST;
    end else if (((grp_store_Pipeline_XCROSS_fu_174_out_right_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state8))) begin
        out_right_TLAST_reg <= grp_store_Pipeline_XCROSS_fu_174_out_right_TLAST;
    end else if (((grp_store_Pipeline_OUT_PASS_fu_146_out_right_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state3) & (or_ln382_reg_684 == 1'd0))) begin
        out_right_TLAST_reg <= grp_store_Pipeline_OUT_PASS_fu_146_out_right_TLAST;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_store_Pipeline_MINE4_fu_214_out_right_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state14))) begin
        out_right_TSTRB_reg <= grp_store_Pipeline_MINE4_fu_214_out_right_TSTRB;
    end else if (((grp_store_Pipeline_OUT_PASS3_fu_200_out_right_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state12))) begin
        out_right_TSTRB_reg <= grp_store_Pipeline_OUT_PASS3_fu_200_out_right_TSTRB;
    end else if (((grp_store_Pipeline_XCROSS_fu_174_out_right_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state8))) begin
        out_right_TSTRB_reg <= grp_store_Pipeline_XCROSS_fu_174_out_right_TSTRB;
    end else if (((grp_store_Pipeline_OUT_PASS_fu_146_out_right_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state3) & (or_ln382_reg_684 == 1'd0))) begin
        out_right_TSTRB_reg <= grp_store_Pipeline_OUT_PASS_fu_146_out_right_TSTRB;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        is_col0_reg_670 <= is_col0_fu_275_p2;
        is_lastcol_reg_680 <= is_lastcol_fu_285_p2;
        is_lastrow_reg_675 <= is_lastrow_fu_280_p2;
        or_ln382_reg_684 <= or_ln382_fu_290_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state3) & (1'b0 == ap_block_state3_on_subcall_done))) begin
        or_ln383_reg_688 <= or_ln383_fu_314_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        pos_reg_647 <= pos_s_dout;
        trunc_ln1_reg_661 <= {{pos_s_dout[7:4]}};
        trunc_ln373_reg_652 <= trunc_ln373_fu_256_p1;
    end
end

always @ (*) begin
    if ((out_right_TREADY_int_regslice == 1'b0)) begin
        ap_ST_fsm_state10_blk = 1'b1;
    end else begin
        ap_ST_fsm_state10_blk = 1'b0;
    end
end

assign ap_ST_fsm_state11_blk = 1'b0;

always @ (*) begin
    if ((grp_store_Pipeline_OUT_PASS3_fu_200_ap_done == 1'b0)) begin
        ap_ST_fsm_state12_blk = 1'b1;
    end else begin
        ap_ST_fsm_state12_blk = 1'b0;
    end
end

assign ap_ST_fsm_state13_blk = 1'b0;

always @ (*) begin
    if ((grp_store_Pipeline_MINE4_fu_214_ap_done == 1'b0)) begin
        ap_ST_fsm_state14_blk = 1'b1;
    end else begin
        ap_ST_fsm_state14_blk = 1'b0;
    end
end

always @ (*) begin
    if ((out_down_TREADY_int_regslice == 1'b0)) begin
        ap_ST_fsm_state15_blk = 1'b1;
    end else begin
        ap_ST_fsm_state15_blk = 1'b0;
    end
end

assign ap_ST_fsm_state16_blk = 1'b0;

always @ (*) begin
    if ((grp_store_Pipeline_OUT_PASS2_fu_228_ap_done == 1'b0)) begin
        ap_ST_fsm_state17_blk = 1'b1;
    end else begin
        ap_ST_fsm_state17_blk = 1'b0;
    end
end

assign ap_ST_fsm_state18_blk = 1'b0;

always @ (*) begin
    if ((grp_store_Pipeline_MINE_fu_242_ap_done == 1'b0)) begin
        ap_ST_fsm_state19_blk = 1'b1;
    end else begin
        ap_ST_fsm_state19_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state20)) begin
        ap_ST_fsm_state20_blk = 1'b1;
    end else begin
        ap_ST_fsm_state20_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_block_state3_on_subcall_done)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_block_state4_on_subcall_done) | (1'b1 == ap_block_state4))) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state5)) begin
        ap_ST_fsm_state5_blk = 1'b1;
    end else begin
        ap_ST_fsm_state5_blk = 1'b0;
    end
end

always @ (*) begin
    if ((out_down_TREADY_int_regslice == 1'b0)) begin
        ap_ST_fsm_state6_blk = 1'b1;
    end else begin
        ap_ST_fsm_state6_blk = 1'b0;
    end
end

assign ap_ST_fsm_state7_blk = 1'b0;

always @ (*) begin
    if ((grp_store_Pipeline_XCROSS_fu_174_ap_done == 1'b0)) begin
        ap_ST_fsm_state8_blk = 1'b1;
    end else begin
        ap_ST_fsm_state8_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state9)) begin
        ap_ST_fsm_state9_blk = 1'b1;
    end else begin
        ap_ST_fsm_state9_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state20) & (1'b0 == ap_block_state20))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state20) & (1'b0 == ap_block_state20))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state19)) begin
        c_mine_read = grp_store_Pipeline_MINE_fu_242_c_mine_read;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        c_mine_read = grp_store_Pipeline_MINE4_fu_214_c_mine_read;
    end else begin
        c_mine_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        c_pass_read = grp_store_Pipeline_OUT_PASS2_fu_228_c_pass_read;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        c_pass_read = grp_store_Pipeline_OUT_PASS3_fu_200_c_pass_read;
    end else begin
        c_pass_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state6) | ((1'b1 == ap_CS_fsm_state9) & (is_lastcol_reg_680 == 1'd1)) | ((1'b1 == ap_CS_fsm_state5) & (is_lastrow_reg_675 == 1'd0)))) begin
        out_down_TDATA_blk_n = out_down_TREADY_int_regslice;
    end else begin
        out_down_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state9) & (1'b0 == ap_block_state9) & (is_lastcol_reg_680 == 1'd1))) begin
        out_down_TDATA_int_regslice = zext_ln409_fu_461_p1;
    end else if (((1'b1 == ap_CS_fsm_state5) & (1'b0 == ap_block_state5) & (is_lastrow_reg_675 == 1'd0))) begin
        out_down_TDATA_int_regslice = zext_ln9_1_fu_373_p1;
    end else if (((grp_store_Pipeline_MINE_fu_242_out_down_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state19))) begin
        out_down_TDATA_int_regslice = grp_store_Pipeline_MINE_fu_242_out_down_TDATA;
    end else if (((grp_store_Pipeline_OUT_PASS2_fu_228_out_down_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state17))) begin
        out_down_TDATA_int_regslice = grp_store_Pipeline_OUT_PASS2_fu_228_out_down_TDATA;
    end else if (((grp_store_Pipeline_XCROSS_fu_174_out_down_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state8))) begin
        out_down_TDATA_int_regslice = grp_store_Pipeline_XCROSS_fu_174_out_down_TDATA;
    end else if (((grp_store_Pipeline_OUT_PASS1_fu_160_out_down_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state4) & (or_ln383_reg_688 == 1'd0))) begin
        out_down_TDATA_int_regslice = grp_store_Pipeline_OUT_PASS1_fu_160_out_down_TDATA;
    end else begin
        out_down_TDATA_int_regslice = out_down_TDATA_reg;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state9) & (1'b0 == ap_block_state9) & (is_lastcol_reg_680 == 1'd1)) | ((1'b1 == ap_CS_fsm_state5) & (1'b0 == ap_block_state5) & (is_lastrow_reg_675 == 1'd0)))) begin
        out_down_TKEEP_int_regslice = 4'd15;
    end else if (((grp_store_Pipeline_MINE_fu_242_out_down_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state19))) begin
        out_down_TKEEP_int_regslice = grp_store_Pipeline_MINE_fu_242_out_down_TKEEP;
    end else if (((grp_store_Pipeline_OUT_PASS2_fu_228_out_down_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state17))) begin
        out_down_TKEEP_int_regslice = grp_store_Pipeline_OUT_PASS2_fu_228_out_down_TKEEP;
    end else if (((grp_store_Pipeline_XCROSS_fu_174_out_down_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state8))) begin
        out_down_TKEEP_int_regslice = grp_store_Pipeline_XCROSS_fu_174_out_down_TKEEP;
    end else if (((grp_store_Pipeline_OUT_PASS1_fu_160_out_down_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state4) & (or_ln383_reg_688 == 1'd0))) begin
        out_down_TKEEP_int_regslice = grp_store_Pipeline_OUT_PASS1_fu_160_out_down_TKEEP;
    end else begin
        out_down_TKEEP_int_regslice = out_down_TKEEP_reg;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state9) & (1'b0 == ap_block_state9) & (is_lastcol_reg_680 == 1'd1)) | ((1'b1 == ap_CS_fsm_state5) & (1'b0 == ap_block_state5) & (is_lastrow_reg_675 == 1'd0)))) begin
        out_down_TLAST_int_regslice = 1'd0;
    end else if (((grp_store_Pipeline_MINE_fu_242_out_down_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state19))) begin
        out_down_TLAST_int_regslice = grp_store_Pipeline_MINE_fu_242_out_down_TLAST;
    end else if (((grp_store_Pipeline_OUT_PASS2_fu_228_out_down_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state17))) begin
        out_down_TLAST_int_regslice = grp_store_Pipeline_OUT_PASS2_fu_228_out_down_TLAST;
    end else if (((grp_store_Pipeline_XCROSS_fu_174_out_down_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state8))) begin
        out_down_TLAST_int_regslice = grp_store_Pipeline_XCROSS_fu_174_out_down_TLAST;
    end else if (((grp_store_Pipeline_OUT_PASS1_fu_160_out_down_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state4) & (or_ln383_reg_688 == 1'd0))) begin
        out_down_TLAST_int_regslice = grp_store_Pipeline_OUT_PASS1_fu_160_out_down_TLAST;
    end else begin
        out_down_TLAST_int_regslice = out_down_TLAST_reg;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state9) & (1'b0 == ap_block_state9) & (is_lastcol_reg_680 == 1'd1)) | ((1'b1 == ap_CS_fsm_state5) & (1'b0 == ap_block_state5) & (is_lastrow_reg_675 == 1'd0)))) begin
        out_down_TSTRB_int_regslice = 4'd15;
    end else if (((grp_store_Pipeline_MINE_fu_242_out_down_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state19))) begin
        out_down_TSTRB_int_regslice = grp_store_Pipeline_MINE_fu_242_out_down_TSTRB;
    end else if (((grp_store_Pipeline_OUT_PASS2_fu_228_out_down_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state17))) begin
        out_down_TSTRB_int_regslice = grp_store_Pipeline_OUT_PASS2_fu_228_out_down_TSTRB;
    end else if (((grp_store_Pipeline_XCROSS_fu_174_out_down_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state8))) begin
        out_down_TSTRB_int_regslice = grp_store_Pipeline_XCROSS_fu_174_out_down_TSTRB;
    end else if (((grp_store_Pipeline_OUT_PASS1_fu_160_out_down_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state4) & (or_ln383_reg_688 == 1'd0))) begin
        out_down_TSTRB_int_regslice = grp_store_Pipeline_OUT_PASS1_fu_160_out_down_TSTRB;
    end else begin
        out_down_TSTRB_int_regslice = out_down_TSTRB_reg;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state9) & (1'b0 == ap_block_state9) & (is_lastcol_reg_680 == 1'd1)) | ((1'b1 == ap_CS_fsm_state5) & (1'b0 == ap_block_state5) & (is_lastrow_reg_675 == 1'd0)))) begin
        out_down_TVALID_int_regslice = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state19)) begin
        out_down_TVALID_int_regslice = grp_store_Pipeline_MINE_fu_242_out_down_TVALID;
    end else if ((1'b1 == ap_CS_fsm_state17)) begin
        out_down_TVALID_int_regslice = grp_store_Pipeline_OUT_PASS2_fu_228_out_down_TVALID;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        out_down_TVALID_int_regslice = grp_store_Pipeline_XCROSS_fu_174_out_down_TVALID;
    end else if (((1'b1 == ap_CS_fsm_state4) & (or_ln383_reg_688 == 1'd0))) begin
        out_down_TVALID_int_regslice = grp_store_Pipeline_OUT_PASS1_fu_160_out_down_TVALID;
    end else begin
        out_down_TVALID_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | ((1'b1 == ap_CS_fsm_state9) & (is_lastcol_reg_680 == 1'd0)) | ((1'b1 == ap_CS_fsm_state5) & (is_lastcol_reg_680 == 1'd0)) | ((1'b1 == ap_CS_fsm_state4) & (is_lastcol_reg_680 == 1'd0)))) begin
        out_right_TDATA_blk_n = out_right_TREADY_int_regslice;
    end else begin
        out_right_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state9) & (1'b0 == ap_block_state9) & (is_lastcol_reg_680 == 1'd0))) begin
        out_right_TDATA_int_regslice = zext_ln409_fu_461_p1;
    end else if ((~((1'b1 == ap_block_state4_on_subcall_done) | (1'b1 == ap_block_state4)) & (1'b1 == ap_CS_fsm_state4) & (is_lastcol_reg_680 == 1'd0))) begin
        out_right_TDATA_int_regslice = zext_ln9_fu_352_p1;
    end else if (((grp_store_Pipeline_MINE4_fu_214_out_right_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state14))) begin
        out_right_TDATA_int_regslice = grp_store_Pipeline_MINE4_fu_214_out_right_TDATA;
    end else if (((grp_store_Pipeline_OUT_PASS3_fu_200_out_right_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state12))) begin
        out_right_TDATA_int_regslice = grp_store_Pipeline_OUT_PASS3_fu_200_out_right_TDATA;
    end else if (((grp_store_Pipeline_XCROSS_fu_174_out_right_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state8))) begin
        out_right_TDATA_int_regslice = grp_store_Pipeline_XCROSS_fu_174_out_right_TDATA;
    end else if (((grp_store_Pipeline_OUT_PASS_fu_146_out_right_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state3) & (or_ln382_reg_684 == 1'd0))) begin
        out_right_TDATA_int_regslice = grp_store_Pipeline_OUT_PASS_fu_146_out_right_TDATA;
    end else begin
        out_right_TDATA_int_regslice = out_right_TDATA_reg;
    end
end

always @ (*) begin
    if (((~((1'b1 == ap_block_state4_on_subcall_done) | (1'b1 == ap_block_state4)) & (1'b1 == ap_CS_fsm_state4) & (is_lastcol_reg_680 == 1'd0)) | ((1'b1 == ap_CS_fsm_state9) & (1'b0 == ap_block_state9) & (is_lastcol_reg_680 == 1'd0)))) begin
        out_right_TKEEP_int_regslice = 4'd15;
    end else if (((grp_store_Pipeline_MINE4_fu_214_out_right_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state14))) begin
        out_right_TKEEP_int_regslice = grp_store_Pipeline_MINE4_fu_214_out_right_TKEEP;
    end else if (((grp_store_Pipeline_OUT_PASS3_fu_200_out_right_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state12))) begin
        out_right_TKEEP_int_regslice = grp_store_Pipeline_OUT_PASS3_fu_200_out_right_TKEEP;
    end else if (((grp_store_Pipeline_XCROSS_fu_174_out_right_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state8))) begin
        out_right_TKEEP_int_regslice = grp_store_Pipeline_XCROSS_fu_174_out_right_TKEEP;
    end else if (((grp_store_Pipeline_OUT_PASS_fu_146_out_right_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state3) & (or_ln382_reg_684 == 1'd0))) begin
        out_right_TKEEP_int_regslice = grp_store_Pipeline_OUT_PASS_fu_146_out_right_TKEEP;
    end else begin
        out_right_TKEEP_int_regslice = out_right_TKEEP_reg;
    end
end

always @ (*) begin
    if (((~((1'b1 == ap_block_state4_on_subcall_done) | (1'b1 == ap_block_state4)) & (1'b1 == ap_CS_fsm_state4) & (is_lastcol_reg_680 == 1'd0)) | ((1'b1 == ap_CS_fsm_state9) & (1'b0 == ap_block_state9) & (is_lastcol_reg_680 == 1'd0)))) begin
        out_right_TLAST_int_regslice = 1'd0;
    end else if (((grp_store_Pipeline_MINE4_fu_214_out_right_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state14))) begin
        out_right_TLAST_int_regslice = grp_store_Pipeline_MINE4_fu_214_out_right_TLAST;
    end else if (((grp_store_Pipeline_OUT_PASS3_fu_200_out_right_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state12))) begin
        out_right_TLAST_int_regslice = grp_store_Pipeline_OUT_PASS3_fu_200_out_right_TLAST;
    end else if (((grp_store_Pipeline_XCROSS_fu_174_out_right_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state8))) begin
        out_right_TLAST_int_regslice = grp_store_Pipeline_XCROSS_fu_174_out_right_TLAST;
    end else if (((grp_store_Pipeline_OUT_PASS_fu_146_out_right_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state3) & (or_ln382_reg_684 == 1'd0))) begin
        out_right_TLAST_int_regslice = grp_store_Pipeline_OUT_PASS_fu_146_out_right_TLAST;
    end else begin
        out_right_TLAST_int_regslice = out_right_TLAST_reg;
    end
end

always @ (*) begin
    if (((~((1'b1 == ap_block_state4_on_subcall_done) | (1'b1 == ap_block_state4)) & (1'b1 == ap_CS_fsm_state4) & (is_lastcol_reg_680 == 1'd0)) | ((1'b1 == ap_CS_fsm_state9) & (1'b0 == ap_block_state9) & (is_lastcol_reg_680 == 1'd0)))) begin
        out_right_TSTRB_int_regslice = 4'd15;
    end else if (((grp_store_Pipeline_MINE4_fu_214_out_right_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state14))) begin
        out_right_TSTRB_int_regslice = grp_store_Pipeline_MINE4_fu_214_out_right_TSTRB;
    end else if (((grp_store_Pipeline_OUT_PASS3_fu_200_out_right_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state12))) begin
        out_right_TSTRB_int_regslice = grp_store_Pipeline_OUT_PASS3_fu_200_out_right_TSTRB;
    end else if (((grp_store_Pipeline_XCROSS_fu_174_out_right_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state8))) begin
        out_right_TSTRB_int_regslice = grp_store_Pipeline_XCROSS_fu_174_out_right_TSTRB;
    end else if (((grp_store_Pipeline_OUT_PASS_fu_146_out_right_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state3) & (or_ln382_reg_684 == 1'd0))) begin
        out_right_TSTRB_int_regslice = grp_store_Pipeline_OUT_PASS_fu_146_out_right_TSTRB;
    end else begin
        out_right_TSTRB_int_regslice = out_right_TSTRB_reg;
    end
end

always @ (*) begin
    if (((~((1'b1 == ap_block_state4_on_subcall_done) | (1'b1 == ap_block_state4)) & (1'b1 == ap_CS_fsm_state4) & (is_lastcol_reg_680 == 1'd0)) | ((1'b1 == ap_CS_fsm_state9) & (1'b0 == ap_block_state9) & (is_lastcol_reg_680 == 1'd0)))) begin
        out_right_TVALID_int_regslice = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        out_right_TVALID_int_regslice = grp_store_Pipeline_MINE4_fu_214_out_right_TVALID;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        out_right_TVALID_int_regslice = grp_store_Pipeline_OUT_PASS3_fu_200_out_right_TVALID;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        out_right_TVALID_int_regslice = grp_store_Pipeline_XCROSS_fu_174_out_right_TVALID;
    end else if (((1'b1 == ap_CS_fsm_state3) & (or_ln382_reg_684 == 1'd0))) begin
        out_right_TVALID_int_regslice = grp_store_Pipeline_OUT_PASS_fu_146_out_right_TVALID;
    end else begin
        out_right_TVALID_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        pos_s_blk_n = pos_s_empty_n;
    end else begin
        pos_s_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        pos_s_read = 1'b1;
    end else begin
        pos_s_read = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if (((1'b1 == ap_CS_fsm_state3) & (1'b0 == ap_block_state3_on_subcall_done))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            if ((~((1'b1 == ap_block_state4_on_subcall_done) | (1'b1 == ap_block_state4)) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            if (((1'b1 == ap_CS_fsm_state5) & (1'b0 == ap_block_state5) & (is_lastrow_reg_675 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else if (((1'b1 == ap_CS_fsm_state5) & (1'b0 == ap_block_state5) & (is_lastrow_reg_675 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state6 : begin
            if (((out_down_TREADY_int_regslice == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            if (((grp_store_Pipeline_XCROSS_fu_174_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state8))) begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end
        end
        ap_ST_fsm_state9 : begin
            if (((1'b1 == ap_CS_fsm_state9) & (1'b0 == ap_block_state9) & (is_lastcol_reg_680 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state15;
            end else if (((1'b1 == ap_CS_fsm_state9) & (1'b0 == ap_block_state9) & (is_lastcol_reg_680 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end
        end
        ap_ST_fsm_state10 : begin
            if (((out_right_TREADY_int_regslice == 1'b1) & (1'b1 == ap_CS_fsm_state10) & (is_col0_reg_670 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end else if (((out_right_TREADY_int_regslice == 1'b1) & (1'b1 == ap_CS_fsm_state10) & (is_col0_reg_670 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            if (((grp_store_Pipeline_OUT_PASS3_fu_200_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state12))) begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            if (((grp_store_Pipeline_MINE4_fu_214_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state14))) begin
                ap_NS_fsm = ap_ST_fsm_state20;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end
        end
        ap_ST_fsm_state15 : begin
            if (((out_down_TREADY_int_regslice == 1'b1) & (1'b1 == ap_CS_fsm_state15))) begin
                ap_NS_fsm = ap_ST_fsm_state16;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state15;
            end
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            if (((grp_store_Pipeline_OUT_PASS2_fu_228_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state17))) begin
                ap_NS_fsm = ap_ST_fsm_state18;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state17;
            end
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state19;
        end
        ap_ST_fsm_state19 : begin
            if (((grp_store_Pipeline_MINE_fu_242_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state19))) begin
                ap_NS_fsm = ap_ST_fsm_state20;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state19;
            end
        end
        ap_ST_fsm_state20 : begin
            if (((1'b1 == ap_CS_fsm_state20) & (1'b0 == ap_block_state20))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state20;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln13_fu_357_p2 = (trunc_ln1_reg_661 + 4'd1);

assign add_ln14_fu_336_p2 = (trunc_ln373_reg_652 + 4'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_state18 = ap_CS_fsm[32'd17];

assign ap_CS_fsm_state19 = ap_CS_fsm[32'd18];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state20 = ap_CS_fsm[32'd19];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_block_state1 = ((pos_s_empty_n == 1'b0) | (ap_done_reg == 1'b1) | (ap_start == 1'b0));
end

always @ (*) begin
    ap_block_state20 = ((regslice_both_out_down_V_data_V_U_apdone_blk == 1'b1) | (regslice_both_out_right_V_data_V_U_apdone_blk == 1'b1));
end

always @ (*) begin
    ap_block_state3_on_subcall_done = ((grp_store_Pipeline_OUT_PASS_fu_146_ap_done == 1'b0) & (or_ln382_reg_684 == 1'd0));
end

always @ (*) begin
    ap_block_state4 = ((out_right_TREADY_int_regslice == 1'b0) & (is_lastcol_reg_680 == 1'd0));
end

always @ (*) begin
    ap_block_state4_on_subcall_done = ((grp_store_Pipeline_OUT_PASS1_fu_160_ap_done == 1'b0) & (or_ln383_reg_688 == 1'd0));
end

always @ (*) begin
    ap_block_state5 = (((out_down_TREADY_int_regslice == 1'b0) & (is_lastrow_reg_675 == 1'd0)) | ((out_right_TREADY_int_regslice == 1'b0) & (is_lastcol_reg_680 == 1'd0)));
end

always @ (*) begin
    ap_block_state9 = (((out_down_TREADY_int_regslice == 1'b0) & (is_lastcol_reg_680 == 1'd1)) | ((out_right_TREADY_int_regslice == 1'b0) & (is_lastcol_reg_680 == 1'd0)));
end

assign fwd_down_read = grp_store_Pipeline_OUT_PASS1_fu_160_fwd_down_read;

assign fwd_right_read = grp_store_Pipeline_OUT_PASS_fu_146_fwd_right_read;

assign grp_store_Pipeline_MINE4_fu_214_ap_start = grp_store_Pipeline_MINE4_fu_214_ap_start_reg;

assign grp_store_Pipeline_MINE4_fu_214_out_right_TREADY = (out_right_TREADY_int_regslice & ap_CS_fsm_state14);

assign grp_store_Pipeline_MINE_fu_242_ap_start = grp_store_Pipeline_MINE_fu_242_ap_start_reg;

assign grp_store_Pipeline_MINE_fu_242_out_down_TREADY = (out_down_TREADY_int_regslice & ap_CS_fsm_state19);

assign grp_store_Pipeline_OUT_PASS1_fu_160_ap_start = grp_store_Pipeline_OUT_PASS1_fu_160_ap_start_reg;

assign grp_store_Pipeline_OUT_PASS1_fu_160_out_down_TREADY = (out_down_TREADY_int_regslice & ap_CS_fsm_state4);

assign grp_store_Pipeline_OUT_PASS2_fu_228_ap_start = grp_store_Pipeline_OUT_PASS2_fu_228_ap_start_reg;

assign grp_store_Pipeline_OUT_PASS2_fu_228_out_down_TREADY = (out_down_TREADY_int_regslice & ap_CS_fsm_state17);

assign grp_store_Pipeline_OUT_PASS3_fu_200_ap_start = grp_store_Pipeline_OUT_PASS3_fu_200_ap_start_reg;

assign grp_store_Pipeline_OUT_PASS3_fu_200_out_right_TREADY = (out_right_TREADY_int_regslice & ap_CS_fsm_state12);

assign grp_store_Pipeline_OUT_PASS_fu_146_ap_start = grp_store_Pipeline_OUT_PASS_fu_146_ap_start_reg;

assign grp_store_Pipeline_OUT_PASS_fu_146_out_right_TREADY = (out_right_TREADY_int_regslice & ap_CS_fsm_state3);

assign grp_store_Pipeline_XCROSS_fu_174_ap_start = grp_store_Pipeline_XCROSS_fu_174_ap_start_reg;

assign grp_store_Pipeline_XCROSS_fu_174_out_down_TREADY = (out_down_TREADY_int_regslice & ap_CS_fsm_state8);

assign grp_store_Pipeline_XCROSS_fu_174_out_right_TREADY = (out_right_TREADY_int_regslice & ap_CS_fsm_state8);

assign is_col0_fu_275_p2 = ((trunc_ln373_reg_652 != 4'd0) ? 1'b1 : 1'b0);

assign is_lastcol_fu_285_p2 = ((trunc_ln373_reg_652 == 4'd1) ? 1'b1 : 1'b0);

assign is_lastrow_fu_280_p2 = ((trunc_ln1_reg_661 == 4'd1) ? 1'b1 : 1'b0);

assign is_row0_fu_270_p2 = ((trunc_ln1_reg_661 != 4'd0) ? 1'b1 : 1'b0);

assign or_ln382_fu_290_p2 = (is_row0_fu_270_p2 | is_lastcol_fu_285_p2);

assign or_ln383_fu_314_p2 = (is_lastrow_reg_675 | is_col0_reg_670);

assign out_down_TVALID = regslice_both_out_down_V_data_V_U_vld_out;

assign out_right_TVALID = regslice_both_out_right_V_data_V_U_vld_out;

assign trunc_ln373_fu_256_p1 = pos_s_dout[3:0];

assign w_data_2_fu_362_p5 = {{{{{{11'd1331}, {add_ln13_fu_357_p2}}}, {trunc_ln373_reg_652}}}, {12'd11}};

assign w_data_3_fu_452_p4 = {{{{11'd1332}, {pos_reg_647}}}, {12'd0}};

assign w_data_fu_341_p5 = {{{{{{11'd1330}, {trunc_ln1_reg_661}}}, {add_ln14_fu_336_p2}}}, {12'd11}};

assign xa_out_read = grp_store_Pipeline_XCROSS_fu_174_xa_out_read;

assign xb_out_read = grp_store_Pipeline_XCROSS_fu_174_xb_out_read;

assign zext_ln409_fu_461_p1 = w_data_3_fu_452_p4;

assign zext_ln9_1_fu_373_p1 = w_data_2_fu_362_p5;

assign zext_ln9_fu_352_p1 = w_data_fu_341_p5;

endmodule //sa_grid_store
