// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module sa_grid_frame_group_Pipeline_PAYLOAD (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        in_left_TVALID,
        in_up_TVALID,
        fwd_right_din,
        fwd_right_full_n,
        fwd_right_write,
        fwd_right_num_data_valid,
        fwd_right_fifo_cap,
        fwd_down_din,
        fwd_down_full_n,
        fwd_down_write,
        fwd_down_num_data_valid,
        fwd_down_fifo_cap,
        bufB_din,
        bufB_full_n,
        bufB_write,
        bufB_num_data_valid,
        bufB_fifo_cap,
        bufA_din,
        bufA_full_n,
        bufA_write,
        bufA_num_data_valid,
        bufA_fifo_cap,
        in_up_TDATA,
        in_up_TREADY,
        in_up_TKEEP,
        in_up_TSTRB,
        in_up_TLAST,
        use_up,
        in_left_TDATA,
        in_left_TREADY,
        in_left_TKEEP,
        in_left_TSTRB,
        in_left_TLAST,
        type_r,
        icmp_ln52,
        icmp_ln52_1,
        ds,
        my_s,
        dr,
        my_r,
        storemerge_phi_out,
        storemerge_phi_out_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input   in_left_TVALID;
input   in_up_TVALID;
output  [32:0] fwd_right_din;
input   fwd_right_full_n;
output   fwd_right_write;
input  [3:0] fwd_right_num_data_valid;
input  [3:0] fwd_right_fifo_cap;
output  [32:0] fwd_down_din;
input   fwd_down_full_n;
output   fwd_down_write;
input  [3:0] fwd_down_num_data_valid;
input  [3:0] fwd_down_fifo_cap;
output  [31:0] bufB_din;
input   bufB_full_n;
output   bufB_write;
input  [2:0] bufB_num_data_valid;
input  [2:0] bufB_fifo_cap;
output  [31:0] bufA_din;
input   bufA_full_n;
output   bufA_write;
input  [2:0] bufA_num_data_valid;
input  [2:0] bufA_fifo_cap;
input  [31:0] in_up_TDATA;
output   in_up_TREADY;
input  [3:0] in_up_TKEEP;
input  [3:0] in_up_TSTRB;
input  [0:0] in_up_TLAST;
input  [0:0] use_up;
input  [31:0] in_left_TDATA;
output   in_left_TREADY;
input  [3:0] in_left_TKEEP;
input  [3:0] in_left_TSTRB;
input  [0:0] in_left_TLAST;
input  [3:0] type_r;
input  [0:0] icmp_ln52;
input  [0:0] icmp_ln52_1;
input  [3:0] ds;
input  [3:0] my_s;
input  [3:0] dr;
input  [3:0] my_r;
output  [0:0] storemerge_phi_out;
output   storemerge_phi_out_ap_vld;

reg ap_idle;
reg fwd_right_write;
reg fwd_down_write;
reg bufB_write;
reg bufA_write;
reg in_up_TREADY;
reg in_left_TREADY;
reg storemerge_phi_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
reg   [0:0] icmp_ln62_reg_334;
reg    ap_predicate_op42_read_state2;
reg    ap_predicate_op46_read_state2;
reg   [0:0] and_ln52_reg_330;
reg   [0:0] cmp_i_i111_reg_326;
reg    ap_predicate_op54_write_state2;
reg    ap_predicate_op56_write_state2;
reg    ap_predicate_op58_write_state2;
reg    ap_predicate_op60_write_state2;
reg    ap_block_state2_pp0_stage0_iter1_grp1;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln62_fu_253_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    bufA_blk_n;
wire    ap_block_pp0_stage0_grp1;
reg    in_up_TDATA_blk_n;
reg    in_left_TDATA_blk_n;
reg    bufB_blk_n;
reg    fwd_down_blk_n;
reg    fwd_right_blk_n;
reg    ap_block_pp0_stage0_11001;
wire   [0:0] cmp_i_i111_fu_233_p2;
wire   [0:0] and_ln52_fu_239_p2;
reg   [31:0] ap_phi_mux_w_data_6_phi_fu_216_p4;
wire   [31:0] ap_phi_reg_pp0_iter1_w_data_6_reg_213;
reg    ap_block_pp0_stage0_11001_grp1;
reg   [0:0] ap_phi_mux_last_1_phi_fu_227_p4;
wire   [0:0] ap_phi_reg_pp0_iter1_last_1_reg_224;
reg   [0:0] last_fu_98;
reg   [2:0] k_fu_102;
wire   [2:0] k_2_fu_259_p2;
wire    ap_loop_init;
reg   [2:0] ap_sig_allocacmp_k_1;
wire    ap_block_pp0_stage0;
wire    ap_block_pp0_stage0_11001_grp0;
wire    ap_block_pp0_stage0_subdone_grp0;
wire   [32:0] tmp_9_fu_295_p3;
reg    ap_block_pp0_stage0_01001_grp1;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 last_fu_98 = 1'd0;
#0 k_fu_102 = 3'd0;
#0 ap_done_reg = 1'b0;
end

sa_grid_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if (((ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln62_fu_253_p2 == 1'd0))) begin
            k_fu_102 <= k_2_fu_259_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            k_fu_102 <= 3'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        and_ln52_reg_330 <= and_ln52_fu_239_p2;
        cmp_i_i111_reg_326 <= cmp_i_i111_fu_233_p2;
        icmp_ln62_reg_334 <= icmp_ln62_fu_253_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        last_fu_98 <= ap_phi_mux_last_1_phi_fu_227_p4;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln62_fu_253_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((icmp_ln62_reg_334 == 1'd0)) begin
        if ((use_up == 1'd0)) begin
            ap_phi_mux_last_1_phi_fu_227_p4 = in_left_TLAST;
        end else if ((use_up == 1'd1)) begin
            ap_phi_mux_last_1_phi_fu_227_p4 = in_up_TLAST;
        end else begin
            ap_phi_mux_last_1_phi_fu_227_p4 = ap_phi_reg_pp0_iter1_last_1_reg_224;
        end
    end else begin
        ap_phi_mux_last_1_phi_fu_227_p4 = ap_phi_reg_pp0_iter1_last_1_reg_224;
    end
end

always @ (*) begin
    if ((icmp_ln62_reg_334 == 1'd0)) begin
        if ((use_up == 1'd0)) begin
            ap_phi_mux_w_data_6_phi_fu_216_p4 = in_left_TDATA;
        end else if ((use_up == 1'd1)) begin
            ap_phi_mux_w_data_6_phi_fu_216_p4 = in_up_TDATA;
        end else begin
            ap_phi_mux_w_data_6_phi_fu_216_p4 = ap_phi_reg_pp0_iter1_w_data_6_reg_213;
        end
    end else begin
        ap_phi_mux_w_data_6_phi_fu_216_p4 = ap_phi_reg_pp0_iter1_w_data_6_reg_213;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_sig_allocacmp_k_1 = 3'd0;
    end else begin
        ap_sig_allocacmp_k_1 = k_fu_102;
    end
end

always @ (*) begin
    if (((ap_predicate_op60_write_state2 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_grp1))) begin
        bufA_blk_n = bufA_full_n;
    end else begin
        bufA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_predicate_op60_write_state2 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        bufA_write = 1'b1;
    end else begin
        bufA_write = 1'b0;
    end
end

always @ (*) begin
    if (((ap_predicate_op58_write_state2 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_grp1))) begin
        bufB_blk_n = bufB_full_n;
    end else begin
        bufB_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_predicate_op58_write_state2 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        bufB_write = 1'b1;
    end else begin
        bufB_write = 1'b0;
    end
end

always @ (*) begin
    if (((ap_predicate_op56_write_state2 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_grp1))) begin
        fwd_down_blk_n = fwd_down_full_n;
    end else begin
        fwd_down_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_predicate_op56_write_state2 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        fwd_down_write = 1'b1;
    end else begin
        fwd_down_write = 1'b0;
    end
end

always @ (*) begin
    if (((ap_predicate_op54_write_state2 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_grp1))) begin
        fwd_right_blk_n = fwd_right_full_n;
    end else begin
        fwd_right_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_predicate_op54_write_state2 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        fwd_right_write = 1'b1;
    end else begin
        fwd_right_write = 1'b0;
    end
end

always @ (*) begin
    if (((ap_predicate_op42_read_state2 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_grp1))) begin
        in_left_TDATA_blk_n = in_left_TVALID;
    end else begin
        in_left_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_predicate_op42_read_state2 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        in_left_TREADY = 1'b1;
    end else begin
        in_left_TREADY = 1'b0;
    end
end

always @ (*) begin
    if (((ap_predicate_op46_read_state2 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_grp1))) begin
        in_up_TDATA_blk_n = in_up_TVALID;
    end else begin
        in_up_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_predicate_op46_read_state2 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        in_up_TREADY = 1'b1;
    end else begin
        in_up_TREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_exit_ready == 1'b1) & (icmp_ln62_fu_253_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        storemerge_phi_out_ap_vld = 1'b1;
    end else begin
        storemerge_phi_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign and_ln52_fu_239_p2 = (icmp_ln52_1 & icmp_ln52);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001_grp1 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1_grp1));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1_grp1));
end

assign ap_block_pp0_stage0_11001_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001_grp1 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1_grp1));
end

assign ap_block_pp0_stage0_grp1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1_grp1));
end

assign ap_block_pp0_stage0_subdone_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1_grp1 = (((ap_predicate_op58_write_state2 == 1'b1) & (bufB_full_n == 1'b0)) | ((ap_predicate_op56_write_state2 == 1'b1) & (fwd_down_full_n == 1'b0)) | ((ap_predicate_op54_write_state2 == 1'b1) & (fwd_right_full_n == 1'b0)) | ((ap_predicate_op46_read_state2 == 1'b1) & (in_up_TVALID == 1'b0)) | ((ap_predicate_op42_read_state2 == 1'b1) & (in_left_TVALID == 1'b0)) | ((ap_predicate_op60_write_state2 == 1'b1) & (bufA_full_n == 1'b0)));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_phi_reg_pp0_iter1_last_1_reg_224 = 'bx;

assign ap_phi_reg_pp0_iter1_w_data_6_reg_213 = 'bx;

always @ (*) begin
    ap_predicate_op42_read_state2 = ((use_up == 1'd0) & (icmp_ln62_reg_334 == 1'd0));
end

always @ (*) begin
    ap_predicate_op46_read_state2 = ((use_up == 1'd1) & (icmp_ln62_reg_334 == 1'd0));
end

always @ (*) begin
    ap_predicate_op54_write_state2 = ((cmp_i_i111_reg_326 == 1'd0) & (1'd0 == and_ln52_reg_330));
end

always @ (*) begin
    ap_predicate_op56_write_state2 = ((cmp_i_i111_reg_326 == 1'd1) & (1'd0 == and_ln52_reg_330));
end

always @ (*) begin
    ap_predicate_op58_write_state2 = ((cmp_i_i111_reg_326 == 1'd0) & (1'd1 == and_ln52_reg_330));
end

always @ (*) begin
    ap_predicate_op60_write_state2 = ((cmp_i_i111_reg_326 == 1'd1) & (1'd1 == and_ln52_reg_330));
end

assign ap_ready = ap_ready_sig;

assign bufA_din = ap_phi_mux_w_data_6_phi_fu_216_p4;

assign bufB_din = ap_phi_mux_w_data_6_phi_fu_216_p4;

assign cmp_i_i111_fu_233_p2 = ((type_r == 4'd0) ? 1'b1 : 1'b0);

assign fwd_down_din = tmp_9_fu_295_p3;

assign fwd_right_din = tmp_9_fu_295_p3;

assign icmp_ln62_fu_253_p2 = ((ap_sig_allocacmp_k_1 == 3'd4) ? 1'b1 : 1'b0);

assign k_2_fu_259_p2 = (ap_sig_allocacmp_k_1 + 3'd1);

assign storemerge_phi_out = last_fu_98;

assign tmp_9_fu_295_p3 = {{ap_phi_mux_last_1_phi_fu_227_p4}, {ap_phi_mux_w_data_6_phi_fu_216_p4}};

endmodule //sa_grid_frame_group_Pipeline_PAYLOAD
