// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module sa_grid_load_Pipeline_PICK (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        in_left_TDATA,
        in_left_TVALID,
        in_left_TREADY,
        in_left_TKEEP,
        in_left_TSTRB,
        in_left_TLAST,
        in_up_TDATA,
        in_up_TVALID,
        in_up_TREADY,
        in_up_TKEEP,
        in_up_TSTRB,
        in_up_TLAST,
        h_data_out,
        h_data_out_ap_vld,
        from_left_out,
        from_left_out_ap_vld,
        from_up_out,
        from_up_out_ap_vld
);

parameter    ap_ST_fsm_state1 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] in_left_TDATA;
input   in_left_TVALID;
output   in_left_TREADY;
input  [3:0] in_left_TKEEP;
input  [3:0] in_left_TSTRB;
input  [0:0] in_left_TLAST;
input  [31:0] in_up_TDATA;
input   in_up_TVALID;
output   in_up_TREADY;
input  [3:0] in_up_TKEEP;
input  [3:0] in_up_TSTRB;
input  [0:0] in_up_TLAST;
output  [31:0] h_data_out;
output   h_data_out_ap_vld;
output  [0:0] from_left_out;
output   from_left_out_ap_vld;
output  [0:0] from_up_out;
output   from_up_out_ap_vld;

reg ap_idle;
reg in_left_TREADY;
reg in_up_TREADY;
reg h_data_out_ap_vld;
reg from_left_out_ap_vld;
reg from_up_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_block_state1_pp0_stage0_iter0;
wire   [0:0] or_ln112_fu_160_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg   [0:0] from_left_reg_113;
reg   [0:0] from_up_reg_124;
reg   [0:0] ap_phi_mux_from_left_phi_fu_116_p4;
wire    ap_loop_init;
reg   [0:0] ap_phi_mux_retval_0_i45_phi_fu_139_p4;
reg   [0:0] ap_phi_mux_from_up_phi_fu_127_p4;
reg   [0:0] ap_phi_mux_from_up_1_phi_fu_152_p4;
wire   [0:0] ap_phi_reg_pp0_iter0_retval_0_i45_reg_135;
wire   [0:0] p_vld_fu_166_p1;
wire   [0:0] ap_phi_reg_pp0_iter0_from_up_1_reg_148;
reg   [31:0] h_data_fu_64;
wire   [31:0] select_ln117_fu_186_p3;
wire   [0:0] empty_nbread_fu_68_p5_0;
wire   [0:0] from_up_2_nbread_fu_80_p5_0;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
reg    ap_condition_66;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 h_data_fu_64 = 32'd0;
#0 ap_done_reg = 1'b0;
end

sa_grid_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_66)) begin
        if ((p_vld_fu_166_p1 == 1'd1)) begin
            h_data_fu_64 <= in_left_TDATA;
        end else if ((p_vld_fu_166_p1 == 1'd0)) begin
            h_data_fu_64 <= select_ln117_fu_186_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((or_ln112_fu_160_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        from_left_reg_113 <= ap_phi_mux_retval_0_i45_phi_fu_139_p4;
        from_up_reg_124 <= ap_phi_mux_from_up_1_phi_fu_152_p4;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1_pp0_stage0_iter0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if (((or_ln112_fu_160_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_phi_mux_from_left_phi_fu_116_p4 = 1'd0;
    end else begin
        ap_phi_mux_from_left_phi_fu_116_p4 = from_left_reg_113;
    end
end

always @ (*) begin
    if ((or_ln112_fu_160_p2 == 1'd0)) begin
        if ((p_vld_fu_166_p1 == 1'd1)) begin
            ap_phi_mux_from_up_1_phi_fu_152_p4 = 1'd0;
        end else if ((p_vld_fu_166_p1 == 1'd0)) begin
            ap_phi_mux_from_up_1_phi_fu_152_p4 = from_up_2_nbread_fu_80_p5_0;
        end else begin
            ap_phi_mux_from_up_1_phi_fu_152_p4 = ap_phi_reg_pp0_iter0_from_up_1_reg_148;
        end
    end else begin
        ap_phi_mux_from_up_1_phi_fu_152_p4 = ap_phi_reg_pp0_iter0_from_up_1_reg_148;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_phi_mux_from_up_phi_fu_127_p4 = 1'd0;
    end else begin
        ap_phi_mux_from_up_phi_fu_127_p4 = from_up_reg_124;
    end
end

always @ (*) begin
    if ((or_ln112_fu_160_p2 == 1'd0)) begin
        if ((p_vld_fu_166_p1 == 1'd1)) begin
            ap_phi_mux_retval_0_i45_phi_fu_139_p4 = 1'd1;
        end else if ((p_vld_fu_166_p1 == 1'd0)) begin
            ap_phi_mux_retval_0_i45_phi_fu_139_p4 = 1'd0;
        end else begin
            ap_phi_mux_retval_0_i45_phi_fu_139_p4 = ap_phi_reg_pp0_iter0_retval_0_i45_reg_135;
        end
    end else begin
        ap_phi_mux_retval_0_i45_phi_fu_139_p4 = ap_phi_reg_pp0_iter0_retval_0_i45_reg_135;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (or_ln112_fu_160_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        from_left_out_ap_vld = 1'b1;
    end else begin
        from_left_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (or_ln112_fu_160_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        from_up_out_ap_vld = 1'b1;
    end else begin
        from_up_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (or_ln112_fu_160_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        h_data_out_ap_vld = 1'b1;
    end else begin
        h_data_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((in_left_TVALID == 1'b1) & (or_ln112_fu_160_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        in_left_TREADY = 1'b1;
    end else begin
        in_left_TREADY = 1'b0;
    end
end

always @ (*) begin
    if (((p_vld_fu_166_p1 == 1'd0) & (in_up_TVALID == 1'b1) & (or_ln112_fu_160_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        in_up_TREADY = 1'b1;
    end else begin
        in_up_TREADY = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (ap_start_int == 1'b0);
end

always @ (*) begin
    ap_condition_66 = ((or_ln112_fu_160_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1));
end

assign ap_done = ap_done_sig;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_phi_reg_pp0_iter0_from_up_1_reg_148 = 'bx;

assign ap_phi_reg_pp0_iter0_retval_0_i45_reg_135 = 'bx;

assign ap_ready = ap_ready_sig;

assign empty_nbread_fu_68_p5_0 = in_left_TVALID;

assign from_left_out = ap_phi_mux_from_left_phi_fu_116_p4;

assign from_up_2_nbread_fu_80_p5_0 = in_up_TVALID;

assign from_up_out = ap_phi_mux_from_up_phi_fu_127_p4;

assign h_data_out = h_data_fu_64;

assign or_ln112_fu_160_p2 = (ap_phi_mux_from_up_phi_fu_127_p4 | ap_phi_mux_from_left_phi_fu_116_p4);

assign p_vld_fu_166_p1 = empty_nbread_fu_68_p5_0;

assign select_ln117_fu_186_p3 = ((from_up_2_nbread_fu_80_p5_0[0:0] == 1'b1) ? in_up_TDATA : h_data_fu_64);

endmodule //sa_grid_load_Pipeline_PICK
