// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="sa_grid_sa_grid,hls_ip_2024_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xczu4eg-sfvc784-2-e,HLS_INPUT_CLOCK=3.333000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=2.794000,HLS_SYN_LAT=55,HLS_SYN_TPT=55,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=2497,HLS_SYN_LUT=4249,HLS_VERSION=2024_2}" *)

module sa_grid (
        s_axi_control_AWVALID,
        s_axi_control_AWREADY,
        s_axi_control_AWADDR,
        s_axi_control_WVALID,
        s_axi_control_WREADY,
        s_axi_control_WDATA,
        s_axi_control_WSTRB,
        s_axi_control_ARVALID,
        s_axi_control_ARREADY,
        s_axi_control_ARADDR,
        s_axi_control_RVALID,
        s_axi_control_RREADY,
        s_axi_control_RDATA,
        s_axi_control_RRESP,
        s_axi_control_BVALID,
        s_axi_control_BREADY,
        s_axi_control_BRESP,
        ap_clk,
        ap_rst_n,
        interrupt,
        in_left_TDATA,
        in_left_TKEEP,
        in_left_TSTRB,
        in_left_TLAST,
        in_up_TDATA,
        in_up_TKEEP,
        in_up_TSTRB,
        in_up_TLAST,
        out_right_TDATA,
        out_right_TKEEP,
        out_right_TSTRB,
        out_right_TLAST,
        out_down_TDATA,
        out_down_TKEEP,
        out_down_TSTRB,
        out_down_TLAST,
        in_left_TVALID,
        in_left_TREADY,
        in_up_TVALID,
        in_up_TREADY,
        out_right_TVALID,
        out_right_TREADY,
        out_down_TVALID,
        out_down_TREADY
);

parameter    C_S_AXI_CONTROL_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_ADDR_WIDTH = 4;
parameter    C_S_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_CONTROL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);

input   s_axi_control_AWVALID;
output   s_axi_control_AWREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_AWADDR;
input   s_axi_control_WVALID;
output   s_axi_control_WREADY;
input  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_WDATA;
input  [C_S_AXI_CONTROL_WSTRB_WIDTH - 1:0] s_axi_control_WSTRB;
input   s_axi_control_ARVALID;
output   s_axi_control_ARREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_ARADDR;
output   s_axi_control_RVALID;
input   s_axi_control_RREADY;
output  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_RDATA;
output  [1:0] s_axi_control_RRESP;
output   s_axi_control_BVALID;
input   s_axi_control_BREADY;
output  [1:0] s_axi_control_BRESP;
input   ap_clk;
input   ap_rst_n;
output   interrupt;
input  [31:0] in_left_TDATA;
input  [3:0] in_left_TKEEP;
input  [3:0] in_left_TSTRB;
input  [0:0] in_left_TLAST;
input  [31:0] in_up_TDATA;
input  [3:0] in_up_TKEEP;
input  [3:0] in_up_TSTRB;
input  [0:0] in_up_TLAST;
output  [31:0] out_right_TDATA;
output  [3:0] out_right_TKEEP;
output  [3:0] out_right_TSTRB;
output  [0:0] out_right_TLAST;
output  [31:0] out_down_TDATA;
output  [3:0] out_down_TKEEP;
output  [3:0] out_down_TSTRB;
output  [0:0] out_down_TLAST;
input   in_left_TVALID;
output   in_left_TREADY;
input   in_up_TVALID;
output   in_up_TREADY;
output   out_right_TVALID;
input   out_right_TREADY;
output   out_down_TVALID;
input   out_down_TREADY;

 reg    ap_rst_n_inv;
wire    ap_start;
wire    ap_ready;
wire    ap_done;
wire    ap_idle;
wire    load_U0_ap_start;
wire    load_U0_start_full_n;
wire    load_U0_ap_done;
wire    load_U0_ap_continue;
wire    load_U0_ap_idle;
wire    load_U0_ap_ready;
wire    load_U0_start_out;
wire    load_U0_start_write;
wire    load_U0_in_left_TREADY;
wire    load_U0_in_up_TREADY;
wire   [32:0] load_U0_fwd_right_din;
wire    load_U0_fwd_right_write;
wire   [32:0] load_U0_fwd_down_din;
wire    load_U0_fwd_down_write;
wire   [31:0] load_U0_bufA_din;
wire    load_U0_bufA_write;
wire   [31:0] load_U0_bufB_din;
wire    load_U0_bufB_write;
wire   [31:0] load_U0_xa_in_din;
wire    load_U0_xa_in_write;
wire   [31:0] load_U0_xb_in_din;
wire    load_U0_xb_in_write;
wire   [32:0] load_U0_c_pass_din;
wire    load_U0_c_pass_write;
wire   [7:0] load_U0_pos_c_din;
wire    load_U0_pos_c_write;
wire   [7:0] load_U0_pos_s_din;
wire    load_U0_pos_s_write;
wire    compute_U0_ap_start;
wire    compute_U0_ap_done;
wire    compute_U0_ap_continue;
wire    compute_U0_ap_idle;
wire    compute_U0_ap_ready;
wire    compute_U0_bufA_read;
wire    compute_U0_bufB_read;
wire    compute_U0_xa_in_read;
wire    compute_U0_xb_in_read;
wire   [31:0] compute_U0_xa_out_din;
wire    compute_U0_xa_out_write;
wire   [31:0] compute_U0_xa_out_num_data_valid;
wire   [31:0] compute_U0_xa_out_fifo_cap;
wire   [31:0] compute_U0_xb_out_din;
wire    compute_U0_xb_out_write;
wire   [31:0] compute_U0_xb_out_num_data_valid;
wire   [31:0] compute_U0_xb_out_fifo_cap;
wire   [31:0] compute_U0_c_mine_din;
wire    compute_U0_c_mine_write;
wire   [31:0] compute_U0_c_mine_num_data_valid;
wire   [31:0] compute_U0_c_mine_fifo_cap;
wire    compute_U0_pos_c_read;
wire    store_U0_ap_start;
wire    store_U0_ap_done;
wire    store_U0_ap_continue;
wire    store_U0_ap_idle;
wire    store_U0_ap_ready;
wire    store_U0_fwd_right_read;
wire    store_U0_fwd_down_read;
wire    store_U0_xa_out_read;
wire    store_U0_xb_out_read;
wire    store_U0_c_mine_read;
wire    store_U0_c_pass_read;
wire   [31:0] store_U0_out_right_TDATA;
wire    store_U0_out_right_TVALID;
wire   [3:0] store_U0_out_right_TKEEP;
wire   [3:0] store_U0_out_right_TSTRB;
wire   [0:0] store_U0_out_right_TLAST;
wire   [31:0] store_U0_out_down_TDATA;
wire    store_U0_out_down_TVALID;
wire   [3:0] store_U0_out_down_TKEEP;
wire   [3:0] store_U0_out_down_TSTRB;
wire   [0:0] store_U0_out_down_TLAST;
wire    store_U0_pos_s_read;
wire    fwd_right_full_n;
wire   [32:0] fwd_right_dout;
wire    fwd_right_empty_n;
wire   [3:0] fwd_right_num_data_valid;
wire   [3:0] fwd_right_fifo_cap;
wire    fwd_down_full_n;
wire   [32:0] fwd_down_dout;
wire    fwd_down_empty_n;
wire   [3:0] fwd_down_num_data_valid;
wire   [3:0] fwd_down_fifo_cap;
wire    bufA_full_n;
wire   [31:0] bufA_dout;
wire    bufA_empty_n;
wire   [2:0] bufA_num_data_valid;
wire   [2:0] bufA_fifo_cap;
wire    bufB_full_n;
wire   [31:0] bufB_dout;
wire    bufB_empty_n;
wire   [2:0] bufB_num_data_valid;
wire   [2:0] bufB_fifo_cap;
wire    xa_in_full_n;
wire   [31:0] xa_in_dout;
wire    xa_in_empty_n;
wire   [2:0] xa_in_num_data_valid;
wire   [2:0] xa_in_fifo_cap;
wire    xb_in_full_n;
wire   [31:0] xb_in_dout;
wire    xb_in_empty_n;
wire   [2:0] xb_in_num_data_valid;
wire   [2:0] xb_in_fifo_cap;
wire    c_pass_full_n;
wire   [32:0] c_pass_dout;
wire    c_pass_empty_n;
wire   [4:0] c_pass_num_data_valid;
wire   [4:0] c_pass_fifo_cap;
wire    pos_c_full_n;
wire   [7:0] pos_c_dout;
wire    pos_c_empty_n;
wire   [2:0] pos_c_num_data_valid;
wire   [2:0] pos_c_fifo_cap;
wire    pos_s_full_n;
wire   [7:0] pos_s_dout;
wire    pos_s_empty_n;
wire   [2:0] pos_s_num_data_valid;
wire   [2:0] pos_s_fifo_cap;
wire    xa_out_full_n;
wire   [31:0] xa_out_dout;
wire    xa_out_empty_n;
wire   [2:0] xa_out_num_data_valid;
wire   [2:0] xa_out_fifo_cap;
wire    xb_out_full_n;
wire   [31:0] xb_out_dout;
wire    xb_out_empty_n;
wire   [2:0] xb_out_num_data_valid;
wire   [2:0] xb_out_fifo_cap;
wire    c_mine_full_n;
wire   [31:0] c_mine_dout;
wire    c_mine_empty_n;
wire   [2:0] c_mine_num_data_valid;
wire   [2:0] c_mine_fifo_cap;
wire   [0:0] start_for_compute_U0_din;
wire    start_for_compute_U0_full_n;
wire   [0:0] start_for_compute_U0_dout;
wire    start_for_compute_U0_empty_n;
wire   [0:0] start_for_store_U0_din;
wire    start_for_store_U0_full_n;
wire   [0:0] start_for_store_U0_dout;
wire    start_for_store_U0_empty_n;

sa_grid_control_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CONTROL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CONTROL_DATA_WIDTH ))
control_s_axi_U(
    .AWVALID(s_axi_control_AWVALID),
    .AWREADY(s_axi_control_AWREADY),
    .AWADDR(s_axi_control_AWADDR),
    .WVALID(s_axi_control_WVALID),
    .WREADY(s_axi_control_WREADY),
    .WDATA(s_axi_control_WDATA),
    .WSTRB(s_axi_control_WSTRB),
    .ARVALID(s_axi_control_ARVALID),
    .ARREADY(s_axi_control_ARREADY),
    .ARADDR(s_axi_control_ARADDR),
    .RVALID(s_axi_control_RVALID),
    .RREADY(s_axi_control_RREADY),
    .RDATA(s_axi_control_RDATA),
    .RRESP(s_axi_control_RRESP),
    .BVALID(s_axi_control_BVALID),
    .BREADY(s_axi_control_BREADY),
    .BRESP(s_axi_control_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle)
);

sa_grid_load load_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(load_U0_ap_start),
    .start_full_n(load_U0_start_full_n),
    .ap_done(load_U0_ap_done),
    .ap_continue(load_U0_ap_continue),
    .ap_idle(load_U0_ap_idle),
    .ap_ready(load_U0_ap_ready),
    .start_out(load_U0_start_out),
    .start_write(load_U0_start_write),
    .in_left_TDATA(in_left_TDATA),
    .in_left_TVALID(in_left_TVALID),
    .in_left_TREADY(load_U0_in_left_TREADY),
    .in_left_TKEEP(in_left_TKEEP),
    .in_left_TSTRB(in_left_TSTRB),
    .in_left_TLAST(in_left_TLAST),
    .in_up_TDATA(in_up_TDATA),
    .in_up_TVALID(in_up_TVALID),
    .in_up_TREADY(load_U0_in_up_TREADY),
    .in_up_TKEEP(in_up_TKEEP),
    .in_up_TSTRB(in_up_TSTRB),
    .in_up_TLAST(in_up_TLAST),
    .fwd_right_din(load_U0_fwd_right_din),
    .fwd_right_full_n(fwd_right_full_n),
    .fwd_right_write(load_U0_fwd_right_write),
    .fwd_right_num_data_valid(fwd_right_num_data_valid),
    .fwd_right_fifo_cap(fwd_right_fifo_cap),
    .fwd_down_din(load_U0_fwd_down_din),
    .fwd_down_full_n(fwd_down_full_n),
    .fwd_down_write(load_U0_fwd_down_write),
    .fwd_down_num_data_valid(fwd_down_num_data_valid),
    .fwd_down_fifo_cap(fwd_down_fifo_cap),
    .bufA_din(load_U0_bufA_din),
    .bufA_full_n(bufA_full_n),
    .bufA_write(load_U0_bufA_write),
    .bufA_num_data_valid(bufA_num_data_valid),
    .bufA_fifo_cap(bufA_fifo_cap),
    .bufB_din(load_U0_bufB_din),
    .bufB_full_n(bufB_full_n),
    .bufB_write(load_U0_bufB_write),
    .bufB_num_data_valid(bufB_num_data_valid),
    .bufB_fifo_cap(bufB_fifo_cap),
    .xa_in_din(load_U0_xa_in_din),
    .xa_in_full_n(xa_in_full_n),
    .xa_in_write(load_U0_xa_in_write),
    .xa_in_num_data_valid(xa_in_num_data_valid),
    .xa_in_fifo_cap(xa_in_fifo_cap),
    .xb_in_din(load_U0_xb_in_din),
    .xb_in_full_n(xb_in_full_n),
    .xb_in_write(load_U0_xb_in_write),
    .xb_in_num_data_valid(xb_in_num_data_valid),
    .xb_in_fifo_cap(xb_in_fifo_cap),
    .c_pass_din(load_U0_c_pass_din),
    .c_pass_full_n(c_pass_full_n),
    .c_pass_write(load_U0_c_pass_write),
    .c_pass_num_data_valid(c_pass_num_data_valid),
    .c_pass_fifo_cap(c_pass_fifo_cap),
    .pos_c_din(load_U0_pos_c_din),
    .pos_c_full_n(pos_c_full_n),
    .pos_c_write(load_U0_pos_c_write),
    .pos_c_num_data_valid(pos_c_num_data_valid),
    .pos_c_fifo_cap(pos_c_fifo_cap),
    .pos_s_din(load_U0_pos_s_din),
    .pos_s_full_n(pos_s_full_n),
    .pos_s_write(load_U0_pos_s_write),
    .pos_s_num_data_valid(pos_s_num_data_valid),
    .pos_s_fifo_cap(pos_s_fifo_cap)
);

sa_grid_compute compute_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(compute_U0_ap_start),
    .ap_done(compute_U0_ap_done),
    .ap_continue(compute_U0_ap_continue),
    .ap_idle(compute_U0_ap_idle),
    .ap_ready(compute_U0_ap_ready),
    .bufA_dout(bufA_dout),
    .bufA_empty_n(bufA_empty_n),
    .bufA_read(compute_U0_bufA_read),
    .bufA_num_data_valid(bufA_num_data_valid),
    .bufA_fifo_cap(bufA_fifo_cap),
    .bufB_dout(bufB_dout),
    .bufB_empty_n(bufB_empty_n),
    .bufB_read(compute_U0_bufB_read),
    .bufB_num_data_valid(bufB_num_data_valid),
    .bufB_fifo_cap(bufB_fifo_cap),
    .xa_in_dout(xa_in_dout),
    .xa_in_empty_n(xa_in_empty_n),
    .xa_in_read(compute_U0_xa_in_read),
    .xa_in_num_data_valid(xa_in_num_data_valid),
    .xa_in_fifo_cap(xa_in_fifo_cap),
    .xb_in_dout(xb_in_dout),
    .xb_in_empty_n(xb_in_empty_n),
    .xb_in_read(compute_U0_xb_in_read),
    .xb_in_num_data_valid(xb_in_num_data_valid),
    .xb_in_fifo_cap(xb_in_fifo_cap),
    .xa_out_din(compute_U0_xa_out_din),
    .xa_out_full_n(xa_out_full_n),
    .xa_out_write(compute_U0_xa_out_write),
    .xa_out_num_data_valid(compute_U0_xa_out_num_data_valid),
    .xa_out_fifo_cap(compute_U0_xa_out_fifo_cap),
    .xb_out_din(compute_U0_xb_out_din),
    .xb_out_full_n(xb_out_full_n),
    .xb_out_write(compute_U0_xb_out_write),
    .xb_out_num_data_valid(compute_U0_xb_out_num_data_valid),
    .xb_out_fifo_cap(compute_U0_xb_out_fifo_cap),
    .c_mine_din(compute_U0_c_mine_din),
    .c_mine_full_n(c_mine_full_n),
    .c_mine_write(compute_U0_c_mine_write),
    .c_mine_num_data_valid(compute_U0_c_mine_num_data_valid),
    .c_mine_fifo_cap(compute_U0_c_mine_fifo_cap),
    .pos_c_dout(pos_c_dout),
    .pos_c_empty_n(pos_c_empty_n),
    .pos_c_read(compute_U0_pos_c_read),
    .pos_c_num_data_valid(pos_c_num_data_valid),
    .pos_c_fifo_cap(pos_c_fifo_cap)
);

sa_grid_store store_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(store_U0_ap_start),
    .ap_done(store_U0_ap_done),
    .ap_continue(store_U0_ap_continue),
    .ap_idle(store_U0_ap_idle),
    .ap_ready(store_U0_ap_ready),
    .fwd_right_dout(fwd_right_dout),
    .fwd_right_empty_n(fwd_right_empty_n),
    .fwd_right_read(store_U0_fwd_right_read),
    .fwd_right_num_data_valid(fwd_right_num_data_valid),
    .fwd_right_fifo_cap(fwd_right_fifo_cap),
    .fwd_down_dout(fwd_down_dout),
    .fwd_down_empty_n(fwd_down_empty_n),
    .fwd_down_read(store_U0_fwd_down_read),
    .fwd_down_num_data_valid(fwd_down_num_data_valid),
    .fwd_down_fifo_cap(fwd_down_fifo_cap),
    .xa_out_dout(xa_out_dout),
    .xa_out_empty_n(xa_out_empty_n),
    .xa_out_read(store_U0_xa_out_read),
    .xa_out_num_data_valid(xa_out_num_data_valid),
    .xa_out_fifo_cap(xa_out_fifo_cap),
    .xb_out_dout(xb_out_dout),
    .xb_out_empty_n(xb_out_empty_n),
    .xb_out_read(store_U0_xb_out_read),
    .xb_out_num_data_valid(xb_out_num_data_valid),
    .xb_out_fifo_cap(xb_out_fifo_cap),
    .c_mine_dout(c_mine_dout),
    .c_mine_empty_n(c_mine_empty_n),
    .c_mine_read(store_U0_c_mine_read),
    .c_mine_num_data_valid(c_mine_num_data_valid),
    .c_mine_fifo_cap(c_mine_fifo_cap),
    .c_pass_dout(c_pass_dout),
    .c_pass_empty_n(c_pass_empty_n),
    .c_pass_read(store_U0_c_pass_read),
    .c_pass_num_data_valid(c_pass_num_data_valid),
    .c_pass_fifo_cap(c_pass_fifo_cap),
    .out_right_TDATA(store_U0_out_right_TDATA),
    .out_right_TVALID(store_U0_out_right_TVALID),
    .out_right_TREADY(out_right_TREADY),
    .out_right_TKEEP(store_U0_out_right_TKEEP),
    .out_right_TSTRB(store_U0_out_right_TSTRB),
    .out_right_TLAST(store_U0_out_right_TLAST),
    .out_down_TDATA(store_U0_out_down_TDATA),
    .out_down_TVALID(store_U0_out_down_TVALID),
    .out_down_TREADY(out_down_TREADY),
    .out_down_TKEEP(store_U0_out_down_TKEEP),
    .out_down_TSTRB(store_U0_out_down_TSTRB),
    .out_down_TLAST(store_U0_out_down_TLAST),
    .pos_s_dout(pos_s_dout),
    .pos_s_empty_n(pos_s_empty_n),
    .pos_s_read(store_U0_pos_s_read),
    .pos_s_num_data_valid(pos_s_num_data_valid),
    .pos_s_fifo_cap(pos_s_fifo_cap)
);

sa_grid_fifo_w33_d7_S fwd_right_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(load_U0_fwd_right_din),
    .if_full_n(fwd_right_full_n),
    .if_write(load_U0_fwd_right_write),
    .if_dout(fwd_right_dout),
    .if_empty_n(fwd_right_empty_n),
    .if_read(store_U0_fwd_right_read),
    .if_num_data_valid(fwd_right_num_data_valid),
    .if_fifo_cap(fwd_right_fifo_cap)
);

sa_grid_fifo_w33_d7_S fwd_down_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(load_U0_fwd_down_din),
    .if_full_n(fwd_down_full_n),
    .if_write(load_U0_fwd_down_write),
    .if_dout(fwd_down_dout),
    .if_empty_n(fwd_down_empty_n),
    .if_read(store_U0_fwd_down_read),
    .if_num_data_valid(fwd_down_num_data_valid),
    .if_fifo_cap(fwd_down_fifo_cap)
);

sa_grid_fifo_w32_d4_S bufA_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(load_U0_bufA_din),
    .if_full_n(bufA_full_n),
    .if_write(load_U0_bufA_write),
    .if_dout(bufA_dout),
    .if_empty_n(bufA_empty_n),
    .if_read(compute_U0_bufA_read),
    .if_num_data_valid(bufA_num_data_valid),
    .if_fifo_cap(bufA_fifo_cap)
);

sa_grid_fifo_w32_d4_S bufB_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(load_U0_bufB_din),
    .if_full_n(bufB_full_n),
    .if_write(load_U0_bufB_write),
    .if_dout(bufB_dout),
    .if_empty_n(bufB_empty_n),
    .if_read(compute_U0_bufB_read),
    .if_num_data_valid(bufB_num_data_valid),
    .if_fifo_cap(bufB_fifo_cap)
);

sa_grid_fifo_w32_d4_S xa_in_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(load_U0_xa_in_din),
    .if_full_n(xa_in_full_n),
    .if_write(load_U0_xa_in_write),
    .if_dout(xa_in_dout),
    .if_empty_n(xa_in_empty_n),
    .if_read(compute_U0_xa_in_read),
    .if_num_data_valid(xa_in_num_data_valid),
    .if_fifo_cap(xa_in_fifo_cap)
);

sa_grid_fifo_w32_d4_S xb_in_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(load_U0_xb_in_din),
    .if_full_n(xb_in_full_n),
    .if_write(load_U0_xb_in_write),
    .if_dout(xb_in_dout),
    .if_empty_n(xb_in_empty_n),
    .if_read(compute_U0_xb_in_read),
    .if_num_data_valid(xb_in_num_data_valid),
    .if_fifo_cap(xb_in_fifo_cap)
);

sa_grid_fifo_w33_d14_S c_pass_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(load_U0_c_pass_din),
    .if_full_n(c_pass_full_n),
    .if_write(load_U0_c_pass_write),
    .if_dout(c_pass_dout),
    .if_empty_n(c_pass_empty_n),
    .if_read(store_U0_c_pass_read),
    .if_num_data_valid(c_pass_num_data_valid),
    .if_fifo_cap(c_pass_fifo_cap)
);

sa_grid_fifo_w8_d2_S pos_c_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(load_U0_pos_c_din),
    .if_full_n(pos_c_full_n),
    .if_write(load_U0_pos_c_write),
    .if_dout(pos_c_dout),
    .if_empty_n(pos_c_empty_n),
    .if_read(compute_U0_pos_c_read),
    .if_num_data_valid(pos_c_num_data_valid),
    .if_fifo_cap(pos_c_fifo_cap)
);

sa_grid_fifo_w8_d2_S pos_s_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(load_U0_pos_s_din),
    .if_full_n(pos_s_full_n),
    .if_write(load_U0_pos_s_write),
    .if_dout(pos_s_dout),
    .if_empty_n(pos_s_empty_n),
    .if_read(store_U0_pos_s_read),
    .if_num_data_valid(pos_s_num_data_valid),
    .if_fifo_cap(pos_s_fifo_cap)
);

sa_grid_fifo_w32_d4_S xa_out_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(compute_U0_xa_out_din),
    .if_full_n(xa_out_full_n),
    .if_write(compute_U0_xa_out_write),
    .if_dout(xa_out_dout),
    .if_empty_n(xa_out_empty_n),
    .if_read(store_U0_xa_out_read),
    .if_num_data_valid(xa_out_num_data_valid),
    .if_fifo_cap(xa_out_fifo_cap)
);

sa_grid_fifo_w32_d4_S xb_out_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(compute_U0_xb_out_din),
    .if_full_n(xb_out_full_n),
    .if_write(compute_U0_xb_out_write),
    .if_dout(xb_out_dout),
    .if_empty_n(xb_out_empty_n),
    .if_read(store_U0_xb_out_read),
    .if_num_data_valid(xb_out_num_data_valid),
    .if_fifo_cap(xb_out_fifo_cap)
);

sa_grid_fifo_w32_d4_S c_mine_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(compute_U0_c_mine_din),
    .if_full_n(c_mine_full_n),
    .if_write(compute_U0_c_mine_write),
    .if_dout(c_mine_dout),
    .if_empty_n(c_mine_empty_n),
    .if_read(store_U0_c_mine_read),
    .if_num_data_valid(c_mine_num_data_valid),
    .if_fifo_cap(c_mine_fifo_cap)
);

sa_grid_start_for_compute_U0 start_for_compute_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_compute_U0_din),
    .if_full_n(start_for_compute_U0_full_n),
    .if_write(load_U0_start_write),
    .if_dout(start_for_compute_U0_dout),
    .if_empty_n(start_for_compute_U0_empty_n),
    .if_read(compute_U0_ap_ready)
);

sa_grid_start_for_store_U0 start_for_store_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_store_U0_din),
    .if_full_n(start_for_store_U0_full_n),
    .if_write(load_U0_start_write),
    .if_dout(start_for_store_U0_dout),
    .if_empty_n(start_for_store_U0_empty_n),
    .if_read(store_U0_ap_ready)
);

assign ap_done = store_U0_ap_done;

assign ap_idle = (store_U0_ap_idle & load_U0_ap_idle & compute_U0_ap_idle);

assign ap_ready = load_U0_ap_ready;

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign compute_U0_ap_continue = 1'b1;

assign compute_U0_ap_start = start_for_compute_U0_empty_n;

assign compute_U0_c_mine_fifo_cap = c_mine_fifo_cap;

assign compute_U0_c_mine_num_data_valid = c_mine_num_data_valid;

assign compute_U0_xa_out_fifo_cap = xa_out_fifo_cap;

assign compute_U0_xa_out_num_data_valid = xa_out_num_data_valid;

assign compute_U0_xb_out_fifo_cap = xb_out_fifo_cap;

assign compute_U0_xb_out_num_data_valid = xb_out_num_data_valid;

assign in_left_TREADY = load_U0_in_left_TREADY;

assign in_up_TREADY = load_U0_in_up_TREADY;

assign load_U0_ap_continue = 1'b1;

assign load_U0_ap_start = ap_start;

assign load_U0_start_full_n = (start_for_store_U0_full_n & start_for_compute_U0_full_n);

assign out_down_TDATA = store_U0_out_down_TDATA;

assign out_down_TKEEP = store_U0_out_down_TKEEP;

assign out_down_TLAST = store_U0_out_down_TLAST;

assign out_down_TSTRB = store_U0_out_down_TSTRB;

assign out_down_TVALID = store_U0_out_down_TVALID;

assign out_right_TDATA = store_U0_out_right_TDATA;

assign out_right_TKEEP = store_U0_out_right_TKEEP;

assign out_right_TLAST = store_U0_out_right_TLAST;

assign out_right_TSTRB = store_U0_out_right_TSTRB;

assign out_right_TVALID = store_U0_out_right_TVALID;

assign start_for_compute_U0_din = 1'b1;

assign start_for_store_U0_din = 1'b1;

assign store_U0_ap_continue = 1'b1;

assign store_U0_ap_start = start_for_store_U0_empty_n;


reg find_df_deadlock = 0;
// synthesis translate_off
`include "sa_grid_hls_deadlock_detector.vh"
// synthesis translate_on

reg find_kernel_block = 0;
// synthesis translate_off
`include "sa_grid_hls_deadlock_kernel_monitor_top.vh"
// synthesis translate_on

endmodule //sa_grid

