// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module sa_grid_compute_Pipeline_VITIS_LOOP_207_1 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        bufA_dout,
        bufA_empty_n,
        bufA_read,
        bufA_num_data_valid,
        bufA_fifo_cap,
        bufA_8_out,
        bufA_8_out_ap_vld,
        bufA_7_out,
        bufA_7_out_ap_vld,
        bufA_6_out,
        bufA_6_out_ap_vld,
        bufA_5_out,
        bufA_5_out_ap_vld,
        bufA_4_out,
        bufA_4_out_ap_vld,
        bufA_3_out,
        bufA_3_out_ap_vld,
        bufA_2_out,
        bufA_2_out_ap_vld,
        bufA_1_out,
        bufA_1_out_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] bufA_dout;
input   bufA_empty_n;
output   bufA_read;
input  [2:0] bufA_num_data_valid;
input  [2:0] bufA_fifo_cap;
output  [15:0] bufA_8_out;
output   bufA_8_out_ap_vld;
output  [15:0] bufA_7_out;
output   bufA_7_out_ap_vld;
output  [15:0] bufA_6_out;
output   bufA_6_out_ap_vld;
output  [15:0] bufA_5_out;
output   bufA_5_out_ap_vld;
output  [15:0] bufA_4_out;
output   bufA_4_out_ap_vld;
output  [15:0] bufA_3_out;
output   bufA_3_out_ap_vld;
output  [15:0] bufA_2_out;
output   bufA_2_out_ap_vld;
output  [15:0] bufA_1_out;
output   bufA_1_out_ap_vld;

reg ap_idle;
reg bufA_read;
reg bufA_8_out_ap_vld;
reg bufA_7_out_ap_vld;
reg bufA_6_out_ap_vld;
reg bufA_5_out_ap_vld;
reg bufA_4_out_ap_vld;
reg bufA_3_out_ap_vld;
reg bufA_2_out_ap_vld;
reg bufA_1_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln207_fu_166_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    bufA_blk_n;
wire    ap_block_pp0_stage0_grp1;
wire   [1:0] trunc_ln207_fu_178_p1;
reg   [1:0] trunc_ln207_reg_329;
reg    ap_block_pp0_stage0_11001;
reg   [2:0] k_fu_60;
wire   [2:0] add_ln207_fu_172_p2;
wire    ap_loop_init;
reg   [2:0] ap_sig_allocacmp_k_3;
wire    ap_block_pp0_stage0;
reg   [15:0] bufA_1_fu_64;
wire   [15:0] bufA_9_fu_187_p1;
reg    ap_block_pp0_stage0_11001_grp1;
reg   [15:0] bufA_2_fu_68;
reg   [15:0] bufA_3_fu_72;
reg   [15:0] bufA_4_fu_76;
reg   [15:0] bufA_5_fu_80;
reg   [15:0] bufA_6_fu_84;
reg   [15:0] bufA_7_fu_88;
reg   [15:0] bufA_8_fu_92;
reg    ap_block_pp0_stage0_01001_grp1;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 k_fu_60 = 3'd0;
#0 bufA_1_fu_64 = 16'd0;
#0 bufA_2_fu_68 = 16'd0;
#0 bufA_3_fu_72 = 16'd0;
#0 bufA_4_fu_76 = 16'd0;
#0 bufA_5_fu_80 = 16'd0;
#0 bufA_6_fu_84 = 16'd0;
#0 bufA_7_fu_88 = 16'd0;
#0 bufA_8_fu_92 = 16'd0;
#0 ap_done_reg = 1'b0;
end

sa_grid_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln207_fu_166_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            k_fu_60 <= add_ln207_fu_172_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            k_fu_60 <= 3'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln207_reg_329 == 2'd0) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        bufA_1_fu_64 <= bufA_9_fu_187_p1;
        bufA_5_fu_80 <= {{bufA_dout[31:16]}};
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln207_reg_329 == 2'd1) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        bufA_2_fu_68 <= bufA_9_fu_187_p1;
        bufA_6_fu_84 <= {{bufA_dout[31:16]}};
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln207_reg_329 == 2'd2) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        bufA_3_fu_72 <= bufA_9_fu_187_p1;
        bufA_7_fu_88 <= {{bufA_dout[31:16]}};
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln207_reg_329 == 2'd3) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        bufA_4_fu_76 <= bufA_9_fu_187_p1;
        bufA_8_fu_92 <= {{bufA_dout[31:16]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        trunc_ln207_reg_329 <= trunc_ln207_fu_178_p1;
    end
end

always @ (*) begin
    if (((icmp_ln207_fu_166_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_k_3 = 3'd0;
    end else begin
        ap_sig_allocacmp_k_3 = k_fu_60;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln207_fu_166_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        bufA_1_out_ap_vld = 1'b1;
    end else begin
        bufA_1_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln207_fu_166_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        bufA_2_out_ap_vld = 1'b1;
    end else begin
        bufA_2_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln207_fu_166_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        bufA_3_out_ap_vld = 1'b1;
    end else begin
        bufA_3_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln207_fu_166_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        bufA_4_out_ap_vld = 1'b1;
    end else begin
        bufA_4_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln207_fu_166_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        bufA_5_out_ap_vld = 1'b1;
    end else begin
        bufA_5_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln207_fu_166_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        bufA_6_out_ap_vld = 1'b1;
    end else begin
        bufA_6_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln207_fu_166_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        bufA_7_out_ap_vld = 1'b1;
    end else begin
        bufA_7_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln207_fu_166_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        bufA_8_out_ap_vld = 1'b1;
    end else begin
        bufA_8_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        bufA_blk_n = bufA_empty_n;
    end else begin
        bufA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        bufA_read = 1'b1;
    end else begin
        bufA_read = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln207_fu_172_p2 = (ap_sig_allocacmp_k_3 + 3'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001_grp1 = ((bufA_empty_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((bufA_empty_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_grp1 = ((bufA_empty_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

assign ap_block_pp0_stage0_grp1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((bufA_empty_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign bufA_1_out = bufA_1_fu_64;

assign bufA_2_out = bufA_2_fu_68;

assign bufA_3_out = bufA_3_fu_72;

assign bufA_4_out = bufA_4_fu_76;

assign bufA_5_out = bufA_5_fu_80;

assign bufA_6_out = bufA_6_fu_84;

assign bufA_7_out = bufA_7_fu_88;

assign bufA_8_out = bufA_8_fu_92;

assign bufA_9_fu_187_p1 = bufA_dout[15:0];

assign icmp_ln207_fu_166_p2 = ((ap_sig_allocacmp_k_3 == 3'd4) ? 1'b1 : 1'b0);

assign trunc_ln207_fu_178_p1 = ap_sig_allocacmp_k_3[1:0];

endmodule //sa_grid_compute_Pipeline_VITIS_LOOP_207_1
