// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module sa_grid_compute_Pipeline_STEP (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        xa_out_din,
        xa_out_full_n,
        xa_out_write,
        xa_out_num_data_valid,
        xa_out_fifo_cap,
        xb_out_din,
        xb_out_full_n,
        xb_out_write,
        xb_out_num_data_valid,
        xb_out_fifo_cap,
        xa_in_dout,
        xa_in_empty_n,
        xa_in_read,
        xa_in_num_data_valid,
        xa_in_fifo_cap,
        xb_in_dout,
        xb_in_empty_n,
        xb_in_read,
        xb_in_num_data_valid,
        xb_in_fifo_cap,
        zext_ln241,
        bufB_9,
        bufB_11,
        bufB_13,
        bufB_15,
        zext_ln241_1,
        bufA_9,
        bufA_10,
        bufA_11,
        bufA_12,
        bufA_13,
        bufA_14,
        bufA_15,
        bufA_16,
        bufB_10,
        bufB_12,
        bufB_14,
        bufB_16,
        empty,
        trunc_ln,
        p_out,
        p_out_ap_vld,
        p_out1,
        p_out1_ap_vld,
        p_out2,
        p_out2_ap_vld,
        p_out3,
        p_out3_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [31:0] xa_out_din;
input   xa_out_full_n;
output   xa_out_write;
input  [31:0] xa_out_num_data_valid;
input  [31:0] xa_out_fifo_cap;
output  [31:0] xb_out_din;
input   xb_out_full_n;
output   xb_out_write;
input  [31:0] xb_out_num_data_valid;
input  [31:0] xb_out_fifo_cap;
input  [31:0] xa_in_dout;
input   xa_in_empty_n;
output   xa_in_read;
input  [2:0] xa_in_num_data_valid;
input  [2:0] xa_in_fifo_cap;
input  [31:0] xb_in_dout;
input   xb_in_empty_n;
output   xb_in_read;
input  [2:0] xb_in_num_data_valid;
input  [2:0] xb_in_fifo_cap;
input  [4:0] zext_ln241;
input  [15:0] bufB_9;
input  [15:0] bufB_11;
input  [15:0] bufB_13;
input  [15:0] bufB_15;
input  [4:0] zext_ln241_1;
input  [15:0] bufA_9;
input  [15:0] bufA_10;
input  [15:0] bufA_11;
input  [15:0] bufA_12;
input  [15:0] bufA_13;
input  [15:0] bufA_14;
input  [15:0] bufA_15;
input  [15:0] bufA_16;
input  [15:0] bufB_10;
input  [15:0] bufB_12;
input  [15:0] bufB_14;
input  [15:0] bufB_16;
input  [3:0] empty;
input  [3:0] trunc_ln;
output  [31:0] p_out;
output   p_out_ap_vld;
output  [31:0] p_out1;
output   p_out1_ap_vld;
output  [31:0] p_out2;
output   p_out2_ap_vld;
output  [31:0] p_out3;
output   p_out3_ap_vld;

reg ap_idle;
reg xa_out_write;
reg xb_out_write;
reg xa_in_read;
reg xb_in_read;
reg p_out_ap_vld;
reg p_out1_ap_vld;
reg p_out2_ap_vld;
reg p_out3_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_idle_pp0;
reg   [0:0] icmp_ln241_reg_1124;
reg   [0:0] is_lastcol_reg_1108;
reg    ap_predicate_op111_write_state2;
reg   [0:0] is_lastrow_reg_1112;
reg    ap_predicate_op113_write_state2;
reg   [0:0] icmp_ln194_reg_1116;
reg    ap_predicate_op115_read_state2;
reg   [0:0] icmp_ln193_reg_1120;
reg    ap_predicate_op126_read_state2;
reg    ap_block_state2_pp0_stage0_iter1_grp1;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln241_fu_498_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    xa_out_blk_n;
wire    ap_block_pp0_stage0_grp1;
reg    xb_out_blk_n;
reg    xa_in_blk_n;
reg    xb_in_blk_n;
wire    ap_block_pp0_stage0_11001_grp0;
wire    ap_block_pp0_stage0_subdone_grp0;
reg    ap_block_pp0_stage0_11001_grp1;
wire   [0:0] is_lastcol_fu_406_p2;
reg    ap_block_pp0_stage0_11001;
wire   [0:0] is_lastrow_fu_412_p2;
wire   [0:0] icmp_ln194_fu_418_p2;
wire   [0:0] icmp_ln193_fu_424_p2;
reg   [0:0] icmp_ln241_reg_1124_pp0_iter1_reg;
reg   [0:0] icmp_ln241_reg_1124_pp0_iter2_reg;
wire   [2:0] trunc_ln290_fu_520_p1;
reg   [2:0] trunc_ln290_reg_1128;
wire   [0:0] icmp_ln290_fu_534_p2;
reg   [0:0] icmp_ln290_reg_1134;
wire   [0:0] icmp_ln290_1_fu_556_p2;
reg   [0:0] icmp_ln290_1_reg_1139;
wire   [2:0] trunc_ln307_fu_568_p1;
reg   [2:0] trunc_ln307_reg_1143;
wire   [0:0] icmp_ln307_fu_582_p2;
reg   [0:0] icmp_ln307_reg_1149;
wire   [0:0] icmp_ln307_1_fu_604_p2;
reg   [0:0] icmp_ln307_1_reg_1154;
reg    ap_condition_exit_pp0_iter1_stage0;
reg   [15:0] ap_phi_mux_ref_tmp201_0_150_phi_fu_355_p6;
wire   [15:0] ap_phi_reg_pp0_iter1_ref_tmp201_0_150_reg_352;
wire   [15:0] tmp_9_fu_731_p11;
reg   [15:0] ap_phi_mux_ref_tmp201_043_phi_fu_367_p6;
wire   [15:0] trunc_ln297_fu_689_p1;
wire   [15:0] ap_phi_reg_pp0_iter1_ref_tmp201_043_reg_364;
wire   [15:0] ref_tmp201_0_fu_722_p3;
reg   [15:0] ap_phi_mux_ref_tmp241_0_148_phi_fu_378_p6;
wire   [15:0] ap_phi_reg_pp0_iter1_ref_tmp241_0_148_reg_375;
wire   [15:0] tmp_3_fu_793_p11;
reg   [15:0] ap_phi_mux_ref_tmp241_045_phi_fu_390_p6;
wire   [15:0] trunc_ln314_fu_751_p1;
wire   [15:0] ap_phi_reg_pp0_iter1_ref_tmp241_045_reg_387;
wire   [15:0] ref_tmp241_0_fu_784_p3;
reg   [31:0] empty_50_fu_126;
wire   [31:0] grp_fu_897_p3;
reg   [31:0] ap_sig_allocacmp_p_load7;
wire    ap_loop_init;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg   [15:0] ref_tmp201_04246_fu_130;
reg   [31:0] empty_51_fu_134;
wire   [31:0] grp_fu_906_p3;
reg   [31:0] ap_sig_allocacmp_p_load5;
reg   [15:0] ref_tmp241_04451_fu_138;
reg   [31:0] empty_52_fu_142;
wire   [31:0] grp_fu_915_p3;
reg   [31:0] ap_sig_allocacmp_p_load3;
reg   [15:0] ref_tmp201_0_14952_fu_146;
reg   [15:0] ref_tmp241_0_14753_fu_150;
reg   [31:0] empty_53_fu_154;
wire   [31:0] grp_fu_924_p3;
reg   [31:0] ap_sig_allocacmp_p_load;
reg   [3:0] t_fu_158;
wire   [3:0] add_ln241_fu_504_p2;
reg   [3:0] ap_sig_allocacmp_t_5;
wire    ap_block_pp0_stage0;
reg   [15:0] ref_tmp201_042_fu_162;
reg   [15:0] ref_tmp241_044_fu_166;
reg   [15:0] ref_tmp241_0_147_fu_170;
reg   [15:0] ref_tmp201_0_149_fu_174;
reg    ap_block_pp0_stage0_01001_grp1;
wire   [5:0] zext_ln241_2_fu_510_p1;
wire   [5:0] zext_ln241_1_cast_fu_398_p1;
wire   [5:0] empty_55_fu_514_p2;
wire   [3:0] tmp_4_fu_524_p4;
wire   [5:0] add_ln290_fu_540_p2;
wire   [3:0] tmp_5_fu_546_p4;
wire   [5:0] zext_ln241_cast_fu_402_p1;
wire   [5:0] empty_54_fu_562_p2;
wire   [3:0] tmp_6_fu_572_p4;
wire   [5:0] add_ln307_fu_588_p2;
wire   [3:0] tmp_10_fu_594_p4;
wire  signed [15:0] sext_ln250_fu_639_p0;
wire  signed [15:0] sext_ln250_1_fu_643_p0;
wire  signed [15:0] sext_ln250_2_fu_647_p0;
wire  signed [15:0] sext_ln250_3_fu_651_p0;
wire  signed [15:0] sext_ln250_4_fu_655_p0;
wire  signed [15:0] sext_ln250_5_fu_659_p0;
wire  signed [15:0] sext_ln250_6_fu_663_p0;
wire  signed [15:0] sext_ln250_7_fu_667_p0;
wire  signed [15:0] ea_fu_671_p1;
wire  signed [15:0] ea_fu_671_p2;
wire  signed [15:0] eb_fu_680_p1;
wire  signed [15:0] eb_fu_680_p2;
wire   [15:0] tmp_8_fu_703_p9;
wire   [15:0] tmp_8_fu_703_p11;
wire   [15:0] tmp_9_fu_731_p9;
wire   [15:0] tmp_2_fu_765_p9;
wire   [15:0] tmp_2_fu_765_p11;
wire   [15:0] tmp_3_fu_793_p9;
reg    grp_fu_897_ce;
reg    grp_fu_906_ce;
reg    grp_fu_915_ce;
reg    grp_fu_924_ce;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire   [2:0] tmp_8_fu_703_p1;
wire   [2:0] tmp_8_fu_703_p3;
wire   [2:0] tmp_8_fu_703_p5;
wire   [2:0] tmp_8_fu_703_p7;
wire   [2:0] tmp_9_fu_731_p1;
wire   [2:0] tmp_9_fu_731_p3;
wire   [2:0] tmp_9_fu_731_p5;
wire  signed [2:0] tmp_9_fu_731_p7;
wire   [2:0] tmp_2_fu_765_p1;
wire   [2:0] tmp_2_fu_765_p3;
wire   [2:0] tmp_2_fu_765_p5;
wire   [2:0] tmp_2_fu_765_p7;
wire   [2:0] tmp_3_fu_793_p1;
wire   [2:0] tmp_3_fu_793_p3;
wire   [2:0] tmp_3_fu_793_p5;
wire  signed [2:0] tmp_3_fu_793_p7;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 empty_50_fu_126 = 32'd0;
#0 ref_tmp201_04246_fu_130 = 16'd0;
#0 empty_51_fu_134 = 32'd0;
#0 ref_tmp241_04451_fu_138 = 16'd0;
#0 empty_52_fu_142 = 32'd0;
#0 ref_tmp201_0_14952_fu_146 = 16'd0;
#0 ref_tmp241_0_14753_fu_150 = 16'd0;
#0 empty_53_fu_154 = 32'd0;
#0 t_fu_158 = 4'd0;
#0 ref_tmp201_042_fu_162 = 16'd0;
#0 ref_tmp241_044_fu_166 = 16'd0;
#0 ref_tmp241_0_147_fu_170 = 16'd0;
#0 ref_tmp201_0_149_fu_174 = 16'd0;
#0 ap_done_reg = 1'b0;
end

(* dissolve_hierarchy = "yes" *) sa_grid_sparsemux_9_3_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h0 ),
    .din0_WIDTH( 16 ),
    .CASE1( 3'h1 ),
    .din1_WIDTH( 16 ),
    .CASE2( 3'h2 ),
    .din2_WIDTH( 16 ),
    .CASE3( 3'h3 ),
    .din3_WIDTH( 16 ),
    .def_WIDTH( 16 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 16 ))
sparsemux_9_3_16_1_1_U116(
    .din0(bufA_9),
    .din1(bufA_10),
    .din2(bufA_11),
    .din3(bufA_12),
    .def(tmp_8_fu_703_p9),
    .sel(trunc_ln290_reg_1128),
    .dout(tmp_8_fu_703_p11)
);

(* dissolve_hierarchy = "yes" *) sa_grid_sparsemux_9_3_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h1 ),
    .din0_WIDTH( 16 ),
    .CASE1( 3'h2 ),
    .din1_WIDTH( 16 ),
    .CASE2( 3'h3 ),
    .din2_WIDTH( 16 ),
    .CASE3( 3'h4 ),
    .din3_WIDTH( 16 ),
    .def_WIDTH( 16 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 16 ))
sparsemux_9_3_16_1_1_U117(
    .din0(bufA_13),
    .din1(bufA_14),
    .din2(bufA_15),
    .din3(bufA_16),
    .def(tmp_9_fu_731_p9),
    .sel(trunc_ln290_reg_1128),
    .dout(tmp_9_fu_731_p11)
);

(* dissolve_hierarchy = "yes" *) sa_grid_sparsemux_9_3_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h0 ),
    .din0_WIDTH( 16 ),
    .CASE1( 3'h1 ),
    .din1_WIDTH( 16 ),
    .CASE2( 3'h2 ),
    .din2_WIDTH( 16 ),
    .CASE3( 3'h3 ),
    .din3_WIDTH( 16 ),
    .def_WIDTH( 16 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 16 ))
sparsemux_9_3_16_1_1_U118(
    .din0(bufB_9),
    .din1(bufB_11),
    .din2(bufB_13),
    .din3(bufB_15),
    .def(tmp_2_fu_765_p9),
    .sel(trunc_ln307_reg_1143),
    .dout(tmp_2_fu_765_p11)
);

(* dissolve_hierarchy = "yes" *) sa_grid_sparsemux_9_3_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h1 ),
    .din0_WIDTH( 16 ),
    .CASE1( 3'h2 ),
    .din1_WIDTH( 16 ),
    .CASE2( 3'h3 ),
    .din2_WIDTH( 16 ),
    .CASE3( 3'h4 ),
    .din3_WIDTH( 16 ),
    .def_WIDTH( 16 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 16 ))
sparsemux_9_3_16_1_1_U119(
    .din0(bufB_10),
    .din1(bufB_12),
    .din2(bufB_14),
    .din3(bufB_16),
    .def(tmp_3_fu_793_p9),
    .sel(trunc_ln307_reg_1143),
    .dout(tmp_3_fu_793_p11)
);

sa_grid_mac_muladd_16s_16s_32ns_32_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mac_muladd_16s_16s_32ns_32_4_1_U120(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(sext_ln250_fu_639_p0),
    .din1(sext_ln250_1_fu_643_p0),
    .din2(ap_sig_allocacmp_p_load7),
    .ce(grp_fu_897_ce),
    .dout(grp_fu_897_p3)
);

sa_grid_mac_muladd_16s_16s_32ns_32_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mac_muladd_16s_16s_32ns_32_4_1_U121(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(sext_ln250_2_fu_647_p0),
    .din1(sext_ln250_3_fu_651_p0),
    .din2(ap_sig_allocacmp_p_load5),
    .ce(grp_fu_906_ce),
    .dout(grp_fu_906_p3)
);

sa_grid_mac_muladd_16s_16s_32ns_32_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mac_muladd_16s_16s_32ns_32_4_1_U122(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(sext_ln250_4_fu_655_p0),
    .din1(sext_ln250_5_fu_659_p0),
    .din2(ap_sig_allocacmp_p_load3),
    .ce(grp_fu_915_ce),
    .dout(grp_fu_915_p3)
);

sa_grid_mac_muladd_16s_16s_32ns_32_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mac_muladd_16s_16s_32ns_32_4_1_U123(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(sext_ln250_6_fu_663_p0),
    .din1(sext_ln250_7_fu_667_p0),
    .din2(ap_sig_allocacmp_p_load),
    .ce(grp_fu_924_ce),
    .dout(grp_fu_924_p3)
);

sa_grid_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter3_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            empty_50_fu_126 <= 32'd0;
        end else if ((ap_enable_reg_pp0_iter4 == 1'b1)) begin
            empty_50_fu_126 <= grp_fu_897_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            empty_51_fu_134 <= 32'd0;
        end else if ((ap_enable_reg_pp0_iter4 == 1'b1)) begin
            empty_51_fu_134 <= grp_fu_906_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            empty_52_fu_142 <= 32'd0;
        end else if ((ap_enable_reg_pp0_iter4 == 1'b1)) begin
            empty_52_fu_142 <= grp_fu_915_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            empty_53_fu_154 <= 32'd0;
        end else if ((ap_enable_reg_pp0_iter4 == 1'b1)) begin
            empty_53_fu_154 <= grp_fu_924_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        if ((ap_loop_init == 1'b1)) begin
            ref_tmp201_04246_fu_130 <= 16'd0;
        end else if (((icmp_ln241_reg_1124 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            ref_tmp201_04246_fu_130 <= ref_tmp201_042_fu_162;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        if ((ap_loop_init == 1'b1)) begin
            ref_tmp201_042_fu_162 <= 16'd0;
        end else if (((icmp_ln241_reg_1124 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            ref_tmp201_042_fu_162 <= ap_phi_mux_ref_tmp201_043_phi_fu_367_p6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        if ((ap_loop_init == 1'b1)) begin
            ref_tmp201_0_14952_fu_146 <= 16'd0;
        end else if (((icmp_ln241_reg_1124 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            ref_tmp201_0_14952_fu_146 <= ref_tmp201_0_149_fu_174;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        if ((ap_loop_init == 1'b1)) begin
            ref_tmp201_0_149_fu_174 <= 16'd0;
        end else if (((icmp_ln241_reg_1124 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            ref_tmp201_0_149_fu_174 <= ap_phi_mux_ref_tmp201_0_150_phi_fu_355_p6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        if ((ap_loop_init == 1'b1)) begin
            ref_tmp241_04451_fu_138 <= 16'd0;
        end else if (((icmp_ln241_reg_1124 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            ref_tmp241_04451_fu_138 <= ref_tmp241_044_fu_166;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        if ((ap_loop_init == 1'b1)) begin
            ref_tmp241_044_fu_166 <= 16'd0;
        end else if (((icmp_ln241_reg_1124 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            ref_tmp241_044_fu_166 <= ap_phi_mux_ref_tmp241_045_phi_fu_390_p6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        if ((ap_loop_init == 1'b1)) begin
            ref_tmp241_0_14753_fu_150 <= 16'd0;
        end else if (((icmp_ln241_reg_1124 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            ref_tmp241_0_14753_fu_150 <= ref_tmp241_0_147_fu_170;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        if ((ap_loop_init == 1'b1)) begin
            ref_tmp241_0_147_fu_170 <= 16'd0;
        end else if (((icmp_ln241_reg_1124 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            ref_tmp241_0_147_fu_170 <= ap_phi_mux_ref_tmp241_0_148_phi_fu_378_p6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if (((ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln241_fu_498_p2 == 1'd0))) begin
            t_fu_158 <= add_ln241_fu_504_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            t_fu_158 <= 4'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        icmp_ln193_reg_1120 <= icmp_ln193_fu_424_p2;
        icmp_ln194_reg_1116 <= icmp_ln194_fu_418_p2;
        icmp_ln241_reg_1124 <= icmp_ln241_fu_498_p2;
        icmp_ln241_reg_1124_pp0_iter1_reg <= icmp_ln241_reg_1124;
        icmp_ln290_1_reg_1139 <= icmp_ln290_1_fu_556_p2;
        icmp_ln290_reg_1134 <= icmp_ln290_fu_534_p2;
        icmp_ln307_1_reg_1154 <= icmp_ln307_1_fu_604_p2;
        icmp_ln307_reg_1149 <= icmp_ln307_fu_582_p2;
        is_lastcol_reg_1108 <= is_lastcol_fu_406_p2;
        is_lastrow_reg_1112 <= is_lastrow_fu_412_p2;
        trunc_ln290_reg_1128 <= trunc_ln290_fu_520_p1;
        trunc_ln307_reg_1143 <= trunc_ln307_fu_568_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        icmp_ln241_reg_1124_pp0_iter2_reg <= icmp_ln241_reg_1124_pp0_iter1_reg;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln241_fu_498_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln241_reg_1124 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter3_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((((icmp_ln194_reg_1116 == 1'd1) & (icmp_ln241_reg_1124 == 1'd0) & (icmp_ln290_1_reg_1139 == 1'd0)) | ((icmp_ln194_reg_1116 == 1'd1) & (icmp_ln241_reg_1124 == 1'd0) & (icmp_ln290_1_reg_1139 == 1'd1)))) begin
        ap_phi_mux_ref_tmp201_043_phi_fu_367_p6 = ref_tmp201_0_fu_722_p3;
    end else if (((icmp_ln194_reg_1116 == 1'd0) & (icmp_ln241_reg_1124 == 1'd0))) begin
        ap_phi_mux_ref_tmp201_043_phi_fu_367_p6 = trunc_ln297_fu_689_p1;
    end else begin
        ap_phi_mux_ref_tmp201_043_phi_fu_367_p6 = ap_phi_reg_pp0_iter1_ref_tmp201_043_reg_364;
    end
end

always @ (*) begin
    if ((icmp_ln241_reg_1124 == 1'd0)) begin
        if (((icmp_ln194_reg_1116 == 1'd1) & (icmp_ln290_1_reg_1139 == 1'd0))) begin
            ap_phi_mux_ref_tmp201_0_150_phi_fu_355_p6 = 16'd0;
        end else if (((icmp_ln194_reg_1116 == 1'd1) & (icmp_ln290_1_reg_1139 == 1'd1))) begin
            ap_phi_mux_ref_tmp201_0_150_phi_fu_355_p6 = tmp_9_fu_731_p11;
        end else if ((icmp_ln194_reg_1116 == 1'd0)) begin
            ap_phi_mux_ref_tmp201_0_150_phi_fu_355_p6 = {{xa_in_dout[31:16]}};
        end else begin
            ap_phi_mux_ref_tmp201_0_150_phi_fu_355_p6 = ap_phi_reg_pp0_iter1_ref_tmp201_0_150_reg_352;
        end
    end else begin
        ap_phi_mux_ref_tmp201_0_150_phi_fu_355_p6 = ap_phi_reg_pp0_iter1_ref_tmp201_0_150_reg_352;
    end
end

always @ (*) begin
    if ((((icmp_ln193_reg_1120 == 1'd1) & (icmp_ln241_reg_1124 == 1'd0) & (icmp_ln307_1_reg_1154 == 1'd0)) | ((icmp_ln193_reg_1120 == 1'd1) & (icmp_ln241_reg_1124 == 1'd0) & (icmp_ln307_1_reg_1154 == 1'd1)))) begin
        ap_phi_mux_ref_tmp241_045_phi_fu_390_p6 = ref_tmp241_0_fu_784_p3;
    end else if (((icmp_ln193_reg_1120 == 1'd0) & (icmp_ln241_reg_1124 == 1'd0))) begin
        ap_phi_mux_ref_tmp241_045_phi_fu_390_p6 = trunc_ln314_fu_751_p1;
    end else begin
        ap_phi_mux_ref_tmp241_045_phi_fu_390_p6 = ap_phi_reg_pp0_iter1_ref_tmp241_045_reg_387;
    end
end

always @ (*) begin
    if ((icmp_ln241_reg_1124 == 1'd0)) begin
        if (((icmp_ln193_reg_1120 == 1'd1) & (icmp_ln307_1_reg_1154 == 1'd0))) begin
            ap_phi_mux_ref_tmp241_0_148_phi_fu_378_p6 = 16'd0;
        end else if (((icmp_ln193_reg_1120 == 1'd1) & (icmp_ln307_1_reg_1154 == 1'd1))) begin
            ap_phi_mux_ref_tmp241_0_148_phi_fu_378_p6 = tmp_3_fu_793_p11;
        end else if ((icmp_ln193_reg_1120 == 1'd0)) begin
            ap_phi_mux_ref_tmp241_0_148_phi_fu_378_p6 = {{xb_in_dout[31:16]}};
        end else begin
            ap_phi_mux_ref_tmp241_0_148_phi_fu_378_p6 = ap_phi_reg_pp0_iter1_ref_tmp241_0_148_reg_375;
        end
    end else begin
        ap_phi_mux_ref_tmp241_0_148_phi_fu_378_p6 = ap_phi_reg_pp0_iter1_ref_tmp241_0_148_reg_375;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage0_grp1))) begin
        ap_sig_allocacmp_p_load = grp_fu_924_p3;
    end else begin
        ap_sig_allocacmp_p_load = empty_53_fu_154;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage0_grp1))) begin
        ap_sig_allocacmp_p_load3 = grp_fu_915_p3;
    end else begin
        ap_sig_allocacmp_p_load3 = empty_52_fu_142;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage0_grp1))) begin
        ap_sig_allocacmp_p_load5 = grp_fu_906_p3;
    end else begin
        ap_sig_allocacmp_p_load5 = empty_51_fu_134;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage0_grp1))) begin
        ap_sig_allocacmp_p_load7 = grp_fu_897_p3;
    end else begin
        ap_sig_allocacmp_p_load7 = empty_50_fu_126;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_sig_allocacmp_t_5 = 4'd0;
    end else begin
        ap_sig_allocacmp_t_5 = t_fu_158;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        grp_fu_897_ce = 1'b1;
    end else begin
        grp_fu_897_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        grp_fu_906_ce = 1'b1;
    end else begin
        grp_fu_906_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        grp_fu_915_ce = 1'b1;
    end else begin
        grp_fu_915_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        grp_fu_924_ce = 1'b1;
    end else begin
        grp_fu_924_ce = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter3_reg == 1'b1) & (icmp_ln241_reg_1124_pp0_iter2_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        p_out1_ap_vld = 1'b1;
    end else begin
        p_out1_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter3_reg == 1'b1) & (icmp_ln241_reg_1124_pp0_iter2_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        p_out2_ap_vld = 1'b1;
    end else begin
        p_out2_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter3_reg == 1'b1) & (icmp_ln241_reg_1124_pp0_iter2_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        p_out3_ap_vld = 1'b1;
    end else begin
        p_out3_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter3_reg == 1'b1) & (icmp_ln241_reg_1124_pp0_iter2_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        p_out_ap_vld = 1'b1;
    end else begin
        p_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_predicate_op115_read_state2 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_grp1))) begin
        xa_in_blk_n = xa_in_empty_n;
    end else begin
        xa_in_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_predicate_op115_read_state2 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        xa_in_read = 1'b1;
    end else begin
        xa_in_read = 1'b0;
    end
end

always @ (*) begin
    if (((ap_predicate_op111_write_state2 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_grp1))) begin
        xa_out_blk_n = xa_out_full_n;
    end else begin
        xa_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_predicate_op111_write_state2 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        xa_out_write = 1'b1;
    end else begin
        xa_out_write = 1'b0;
    end
end

always @ (*) begin
    if (((ap_predicate_op126_read_state2 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_grp1))) begin
        xb_in_blk_n = xb_in_empty_n;
    end else begin
        xb_in_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_predicate_op126_read_state2 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        xb_in_read = 1'b1;
    end else begin
        xb_in_read = 1'b0;
    end
end

always @ (*) begin
    if (((ap_predicate_op113_write_state2 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_grp1))) begin
        xb_out_blk_n = xb_out_full_n;
    end else begin
        xb_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_predicate_op113_write_state2 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        xb_out_write = 1'b1;
    end else begin
        xb_out_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln241_fu_504_p2 = (ap_sig_allocacmp_t_5 + 4'd1);

assign add_ln290_fu_540_p2 = ($signed(empty_55_fu_514_p2) + $signed(6'd63));

assign add_ln307_fu_588_p2 = ($signed(empty_54_fu_562_p2) + $signed(6'd63));

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001_grp1 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1_grp1));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1_grp1));
end

assign ap_block_pp0_stage0_11001_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001_grp1 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1_grp1));
end

assign ap_block_pp0_stage0_grp1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1_grp1));
end

assign ap_block_pp0_stage0_subdone_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1_grp1 = (((ap_predicate_op126_read_state2 == 1'b1) & (xb_in_empty_n == 1'b0)) | ((ap_predicate_op115_read_state2 == 1'b1) & (xa_in_empty_n == 1'b0)) | ((ap_predicate_op113_write_state2 == 1'b1) & (xb_out_full_n == 1'b0)) | ((ap_predicate_op111_write_state2 == 1'b1) & (xa_out_full_n == 1'b0)));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_phi_reg_pp0_iter1_ref_tmp201_043_reg_364 = 'bx;

assign ap_phi_reg_pp0_iter1_ref_tmp201_0_150_reg_352 = 'bx;

assign ap_phi_reg_pp0_iter1_ref_tmp241_045_reg_387 = 'bx;

assign ap_phi_reg_pp0_iter1_ref_tmp241_0_148_reg_375 = 'bx;

always @ (*) begin
    ap_predicate_op111_write_state2 = ((is_lastcol_reg_1108 == 1'd0) & (icmp_ln241_reg_1124 == 1'd0));
end

always @ (*) begin
    ap_predicate_op113_write_state2 = ((is_lastrow_reg_1112 == 1'd0) & (icmp_ln241_reg_1124 == 1'd0));
end

always @ (*) begin
    ap_predicate_op115_read_state2 = ((icmp_ln194_reg_1116 == 1'd0) & (icmp_ln241_reg_1124 == 1'd0));
end

always @ (*) begin
    ap_predicate_op126_read_state2 = ((icmp_ln193_reg_1120 == 1'd0) & (icmp_ln241_reg_1124 == 1'd0));
end

assign ap_ready = ap_ready_sig;

assign ea_fu_671_p1 = ref_tmp201_0_14952_fu_146;

assign ea_fu_671_p2 = ref_tmp201_04246_fu_130;

assign eb_fu_680_p1 = ref_tmp241_0_14753_fu_150;

assign eb_fu_680_p2 = ref_tmp241_04451_fu_138;

assign empty_54_fu_562_p2 = (zext_ln241_2_fu_510_p1 - zext_ln241_cast_fu_402_p1);

assign empty_55_fu_514_p2 = (zext_ln241_2_fu_510_p1 - zext_ln241_1_cast_fu_398_p1);

assign icmp_ln193_fu_424_p2 = ((trunc_ln == 4'd0) ? 1'b1 : 1'b0);

assign icmp_ln194_fu_418_p2 = ((empty == 4'd0) ? 1'b1 : 1'b0);

assign icmp_ln241_fu_498_p2 = ((ap_sig_allocacmp_t_5 == 4'd11) ? 1'b1 : 1'b0);

assign icmp_ln290_1_fu_556_p2 = ((tmp_5_fu_546_p4 == 4'd0) ? 1'b1 : 1'b0);

assign icmp_ln290_fu_534_p2 = ((tmp_4_fu_524_p4 == 4'd0) ? 1'b1 : 1'b0);

assign icmp_ln307_1_fu_604_p2 = ((tmp_10_fu_594_p4 == 4'd0) ? 1'b1 : 1'b0);

assign icmp_ln307_fu_582_p2 = ((tmp_6_fu_572_p4 == 4'd0) ? 1'b1 : 1'b0);

assign is_lastcol_fu_406_p2 = ((empty == 4'd1) ? 1'b1 : 1'b0);

assign is_lastrow_fu_412_p2 = ((trunc_ln == 4'd1) ? 1'b1 : 1'b0);

assign p_out = empty_53_fu_154;

assign p_out1 = empty_52_fu_142;

assign p_out2 = empty_51_fu_134;

assign p_out3 = empty_50_fu_126;

assign ref_tmp201_0_fu_722_p3 = ((icmp_ln290_reg_1134[0:0] == 1'b1) ? tmp_8_fu_703_p11 : 16'd0);

assign ref_tmp241_0_fu_784_p3 = ((icmp_ln307_reg_1149[0:0] == 1'b1) ? tmp_2_fu_765_p11 : 16'd0);

assign sext_ln250_1_fu_643_p0 = ref_tmp241_044_fu_166;

assign sext_ln250_2_fu_647_p0 = ref_tmp201_04246_fu_130;

assign sext_ln250_3_fu_651_p0 = ref_tmp241_0_147_fu_170;

assign sext_ln250_4_fu_655_p0 = ref_tmp201_0_149_fu_174;

assign sext_ln250_5_fu_659_p0 = ref_tmp241_04451_fu_138;

assign sext_ln250_6_fu_663_p0 = ref_tmp201_0_14952_fu_146;

assign sext_ln250_7_fu_667_p0 = ref_tmp241_0_14753_fu_150;

assign sext_ln250_fu_639_p0 = ref_tmp201_042_fu_162;

assign tmp_10_fu_594_p4 = {{add_ln307_fu_588_p2[5:2]}};

assign tmp_2_fu_765_p9 = 'bx;

assign tmp_3_fu_793_p9 = 'bx;

assign tmp_4_fu_524_p4 = {{empty_55_fu_514_p2[5:2]}};

assign tmp_5_fu_546_p4 = {{add_ln290_fu_540_p2[5:2]}};

assign tmp_6_fu_572_p4 = {{empty_54_fu_562_p2[5:2]}};

assign tmp_8_fu_703_p9 = 'bx;

assign tmp_9_fu_731_p9 = 'bx;

assign trunc_ln290_fu_520_p1 = empty_55_fu_514_p2[2:0];

assign trunc_ln297_fu_689_p1 = xa_in_dout[15:0];

assign trunc_ln307_fu_568_p1 = empty_54_fu_562_p2[2:0];

assign trunc_ln314_fu_751_p1 = xb_in_dout[15:0];

assign xa_out_din = {{ea_fu_671_p1}, {ea_fu_671_p2}};

assign xb_out_din = {{eb_fu_680_p1}, {eb_fu_680_p2}};

assign zext_ln241_1_cast_fu_398_p1 = zext_ln241_1;

assign zext_ln241_2_fu_510_p1 = ap_sig_allocacmp_t_5;

assign zext_ln241_cast_fu_402_p1 = zext_ln241;

endmodule //sa_grid_compute_Pipeline_STEP
