// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module sa_grid_store_Pipeline_XCROSS (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        xa_out_dout,
        xa_out_empty_n,
        xa_out_read,
        xa_out_num_data_valid,
        xa_out_fifo_cap,
        out_right_TREADY,
        xb_out_dout,
        xb_out_empty_n,
        xb_out_read,
        xb_out_num_data_valid,
        xb_out_fifo_cap,
        out_down_TREADY,
        out_right_TDATA,
        out_right_TVALID,
        out_right_TKEEP,
        out_right_TSTRB,
        out_right_TLAST,
        out_down_TDATA,
        out_down_TVALID,
        out_down_TKEEP,
        out_down_TSTRB,
        out_down_TLAST,
        empty,
        trunc_ln1
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] xa_out_dout;
input   xa_out_empty_n;
output   xa_out_read;
input  [2:0] xa_out_num_data_valid;
input  [2:0] xa_out_fifo_cap;
input   out_right_TREADY;
input  [31:0] xb_out_dout;
input   xb_out_empty_n;
output   xb_out_read;
input  [2:0] xb_out_num_data_valid;
input  [2:0] xb_out_fifo_cap;
input   out_down_TREADY;
output  [31:0] out_right_TDATA;
output   out_right_TVALID;
output  [3:0] out_right_TKEEP;
output  [3:0] out_right_TSTRB;
output  [0:0] out_right_TLAST;
output  [31:0] out_down_TDATA;
output   out_down_TVALID;
output  [3:0] out_down_TKEEP;
output  [3:0] out_down_TSTRB;
output  [0:0] out_down_TLAST;
input  [3:0] empty;
input  [3:0] trunc_ln1;

reg ap_idle;
reg xa_out_read;
reg xb_out_read;
reg out_right_TVALID;
reg out_down_TVALID;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
reg   [0:0] icmp_ln379_reg_196;
reg    ap_block_state2_pp0_stage0_iter1_grp1;
reg    ap_block_pp0_stage0_subdone_grp1_done_reg;
reg    ap_block_pp0_stage0_subdone_grp1;
reg    ap_block_pp0_stage0_subdone;
reg   [0:0] icmp_ln378_reg_200;
reg    ap_block_state2_pp0_stage0_iter1_grp2;
reg    ap_block_pp0_stage0_subdone_grp2_done_reg;
reg    ap_block_pp0_stage0_subdone_grp2;
wire   [0:0] icmp_ln391_fu_160_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    xa_out_blk_n;
wire    ap_block_pp0_stage0_grp1;
reg    out_right_TDATA_blk_n;
reg    xb_out_blk_n;
wire    ap_block_pp0_stage0_grp2;
reg    out_down_TDATA_blk_n;
wire   [0:0] icmp_ln379_fu_140_p2;
reg    ap_block_pp0_stage0_11001;
wire   [0:0] icmp_ln378_fu_146_p2;
wire   [0:0] w_last_fu_172_p2;
reg   [0:0] w_last_reg_207;
wire   [0:0] w_last_1_fu_178_p2;
reg   [0:0] w_last_1_reg_212;
reg   [3:0] t_fu_74;
wire   [3:0] t_2_fu_166_p2;
wire    ap_loop_init;
reg   [3:0] ap_sig_allocacmp_t_1;
wire    ap_block_pp0_stage0;
reg    ap_block_pp0_stage0_11001_grp1;
reg    ap_block_pp0_stage0_01001_grp1;
reg    ap_block_pp0_stage0_11001_grp2;
reg    ap_block_pp0_stage0_01001_grp2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_block_pp0_stage0_subdone_grp1_done_reg = 1'b0;
#0 ap_block_pp0_stage0_subdone_grp2_done_reg = 1'b0;
#0 t_fu_74 = 4'd0;
#0 ap_done_reg = 1'b0;
end

sa_grid_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage0_subdone_grp1_done_reg <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_block_pp0_stage0_subdone_grp1_done_reg <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone_grp1)) begin
            ap_block_pp0_stage0_subdone_grp1_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage0_subdone_grp2_done_reg <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_block_pp0_stage0_subdone_grp2_done_reg <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone_grp2)) begin
            ap_block_pp0_stage0_subdone_grp2_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln391_fu_160_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            t_fu_74 <= t_2_fu_166_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            t_fu_74 <= 4'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln378_reg_200 <= icmp_ln378_fu_146_p2;
        icmp_ln379_reg_196 <= icmp_ln379_fu_140_p2;
        w_last_1_reg_212 <= w_last_1_fu_178_p2;
        w_last_reg_207 <= w_last_fu_172_p2;
    end
end

always @ (*) begin
    if (((icmp_ln391_fu_160_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_t_1 = 4'd0;
    end else begin
        ap_sig_allocacmp_t_1 = t_fu_74;
    end
end

always @ (*) begin
    if (((icmp_ln378_reg_200 == 1'd0) & (1'b0 == ap_block_pp0_stage0_subdone_grp2_done_reg) & (1'b0 == ap_block_pp0_stage0_grp2) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        out_down_TDATA_blk_n = out_down_TREADY;
    end else begin
        out_down_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((icmp_ln378_reg_200 == 1'd0) & (1'b0 == ap_block_pp0_stage0_subdone_grp2_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp2) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        out_down_TVALID = 1'b1;
    end else begin
        out_down_TVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg) & (1'b0 == ap_block_pp0_stage0_grp1) & (icmp_ln379_reg_196 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        out_right_TDATA_blk_n = out_right_TREADY;
    end else begin
        out_right_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (icmp_ln379_reg_196 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        out_right_TVALID = 1'b1;
    end else begin
        out_right_TVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg) & (1'b0 == ap_block_pp0_stage0_grp1) & (icmp_ln379_reg_196 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        xa_out_blk_n = xa_out_empty_n;
    end else begin
        xa_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (icmp_ln379_reg_196 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        xa_out_read = 1'b1;
    end else begin
        xa_out_read = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln378_reg_200 == 1'd0) & (1'b0 == ap_block_pp0_stage0_subdone_grp2_done_reg) & (1'b0 == ap_block_pp0_stage0_grp2) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        xb_out_blk_n = xb_out_empty_n;
    end else begin
        xb_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((icmp_ln378_reg_200 == 1'd0) & (1'b0 == ap_block_pp0_stage0_subdone_grp2_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp2) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        xb_out_read = 1'b1;
    end else begin
        xb_out_read = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001_grp1 = ((1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1_grp1));
end

always @ (*) begin
    ap_block_pp0_stage0_01001_grp2 = ((1'b0 == ap_block_pp0_stage0_subdone_grp2_done_reg) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1_grp2));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (((1'b0 == ap_block_pp0_stage0_subdone_grp2_done_reg) & (1'b1 == ap_block_state2_pp0_stage0_iter1_grp2)) | ((1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg) & (1'b1 == ap_block_state2_pp0_stage0_iter1_grp1))));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_grp1 = ((1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1_grp1));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_grp2 = ((1'b0 == ap_block_pp0_stage0_subdone_grp2_done_reg) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1_grp2));
end

assign ap_block_pp0_stage0_grp1 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_grp2 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_enable_reg_pp0_iter1 == 1'b1) & (((1'b0 == ap_block_pp0_stage0_subdone_grp2_done_reg) & (1'b1 == ap_block_state2_pp0_stage0_iter1_grp2)) | ((1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg) & (1'b1 == ap_block_state2_pp0_stage0_iter1_grp1))));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone_grp1 = ((1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1_grp1));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone_grp2 = ((1'b0 == ap_block_pp0_stage0_subdone_grp2_done_reg) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1_grp2));
end

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1_grp1 = (((icmp_ln379_reg_196 == 1'd0) & (out_right_TREADY == 1'b0)) | ((icmp_ln379_reg_196 == 1'd0) & (xa_out_empty_n == 1'b0)));
end

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1_grp2 = (((icmp_ln378_reg_200 == 1'd0) & (out_down_TREADY == 1'b0)) | ((icmp_ln378_reg_200 == 1'd0) & (xb_out_empty_n == 1'b0)));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign icmp_ln378_fu_146_p2 = ((trunc_ln1 == 4'd1) ? 1'b1 : 1'b0);

assign icmp_ln379_fu_140_p2 = ((empty == 4'd1) ? 1'b1 : 1'b0);

assign icmp_ln391_fu_160_p2 = ((ap_sig_allocacmp_t_1 == 4'd11) ? 1'b1 : 1'b0);

assign out_down_TDATA = xb_out_dout;

assign out_down_TKEEP = 4'd15;

assign out_down_TLAST = w_last_1_reg_212;

assign out_down_TSTRB = 4'd15;

assign out_right_TDATA = xa_out_dout;

assign out_right_TKEEP = 4'd15;

assign out_right_TLAST = w_last_reg_207;

assign out_right_TSTRB = 4'd15;

assign t_2_fu_166_p2 = (ap_sig_allocacmp_t_1 + 4'd1);

assign w_last_1_fu_178_p2 = ((ap_sig_allocacmp_t_1 == 4'd10) ? 1'b1 : 1'b0);

assign w_last_fu_172_p2 = ((ap_sig_allocacmp_t_1 == 4'd10) ? 1'b1 : 1'b0);

endmodule //sa_grid_store_Pipeline_XCROSS
