-- ==============================================================
-- Generated by Vitis HLS v2024.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity sa_grid_load is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    start_full_n : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    start_out : OUT STD_LOGIC;
    start_write : OUT STD_LOGIC;
    in_left_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    in_left_TVALID : IN STD_LOGIC;
    in_left_TREADY : OUT STD_LOGIC;
    in_left_TKEEP : IN STD_LOGIC_VECTOR (3 downto 0);
    in_left_TSTRB : IN STD_LOGIC_VECTOR (3 downto 0);
    in_left_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    in_up_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    in_up_TVALID : IN STD_LOGIC;
    in_up_TREADY : OUT STD_LOGIC;
    in_up_TKEEP : IN STD_LOGIC_VECTOR (3 downto 0);
    in_up_TSTRB : IN STD_LOGIC_VECTOR (3 downto 0);
    in_up_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    fwd_right_din : OUT STD_LOGIC_VECTOR (32 downto 0);
    fwd_right_full_n : IN STD_LOGIC;
    fwd_right_write : OUT STD_LOGIC;
    fwd_right_num_data_valid : IN STD_LOGIC_VECTOR (3 downto 0);
    fwd_right_fifo_cap : IN STD_LOGIC_VECTOR (3 downto 0);
    fwd_down_din : OUT STD_LOGIC_VECTOR (32 downto 0);
    fwd_down_full_n : IN STD_LOGIC;
    fwd_down_write : OUT STD_LOGIC;
    fwd_down_num_data_valid : IN STD_LOGIC_VECTOR (3 downto 0);
    fwd_down_fifo_cap : IN STD_LOGIC_VECTOR (3 downto 0);
    bufA_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    bufA_full_n : IN STD_LOGIC;
    bufA_write : OUT STD_LOGIC;
    bufA_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    bufA_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    bufB_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    bufB_full_n : IN STD_LOGIC;
    bufB_write : OUT STD_LOGIC;
    bufB_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    bufB_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    xa_in_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    xa_in_full_n : IN STD_LOGIC;
    xa_in_write : OUT STD_LOGIC;
    xa_in_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    xa_in_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    xb_in_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    xb_in_full_n : IN STD_LOGIC;
    xb_in_write : OUT STD_LOGIC;
    xb_in_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    xb_in_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    c_pass_din : OUT STD_LOGIC_VECTOR (32 downto 0);
    c_pass_full_n : IN STD_LOGIC;
    c_pass_write : OUT STD_LOGIC;
    c_pass_num_data_valid : IN STD_LOGIC_VECTOR (4 downto 0);
    c_pass_fifo_cap : IN STD_LOGIC_VECTOR (4 downto 0);
    pos_c_din : OUT STD_LOGIC_VECTOR (7 downto 0);
    pos_c_full_n : IN STD_LOGIC;
    pos_c_write : OUT STD_LOGIC;
    pos_c_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    pos_c_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    pos_s_din : OUT STD_LOGIC_VECTOR (7 downto 0);
    pos_s_full_n : IN STD_LOGIC;
    pos_s_write : OUT STD_LOGIC;
    pos_s_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    pos_s_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0) );
end;


architecture behav of sa_grid_load is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (15 downto 0) := "0000000001000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (15 downto 0) := "0000000010000000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (15 downto 0) := "0000000100000000";
    constant ap_ST_fsm_state10 : STD_LOGIC_VECTOR (15 downto 0) := "0000001000000000";
    constant ap_ST_fsm_state11 : STD_LOGIC_VECTOR (15 downto 0) := "0000010000000000";
    constant ap_ST_fsm_state12 : STD_LOGIC_VECTOR (15 downto 0) := "0000100000000000";
    constant ap_ST_fsm_state13 : STD_LOGIC_VECTOR (15 downto 0) := "0001000000000000";
    constant ap_ST_fsm_state14 : STD_LOGIC_VECTOR (15 downto 0) := "0010000000000000";
    constant ap_ST_fsm_state15 : STD_LOGIC_VECTOR (15 downto 0) := "0100000000000000";
    constant ap_ST_fsm_state16 : STD_LOGIC_VECTOR (15 downto 0) := "1000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001101";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv32_C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001100";
    constant ap_const_lv32_E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001110";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv32_13 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010011";
    constant ap_const_lv32_14 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010100";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";

attribute shreg_extract : string;
    signal real_start : STD_LOGIC;
    signal start_once_reg : STD_LOGIC := '0';
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal internal_ap_ready : STD_LOGIC;
    signal in_left_TDATA_blk_n : STD_LOGIC;
    signal ap_CS_fsm_state9 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state9 : signal is "none";
    signal or_ln156_reg_682 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state14 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state14 : signal is "none";
    signal is_col0_reg_652 : STD_LOGIC_VECTOR (0 downto 0);
    signal in_up_TDATA_blk_n : STD_LOGIC;
    signal or_ln157_fu_429_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state12 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state12 : signal is "none";
    signal or_ln169_reg_689 : STD_LOGIC_VECTOR (0 downto 0);
    signal pos_c_blk_n : STD_LOGIC;
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal pos_s_blk_n : STD_LOGIC;
    signal my_r_fu_329_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal my_r_reg_634 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_block_state4 : BOOLEAN;
    signal my_s_fu_338_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal my_s_reg_640 : STD_LOGIC_VECTOR (3 downto 0);
    signal is_row0_fu_347_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal is_row0_reg_646 : STD_LOGIC_VECTOR (0 downto 0);
    signal is_col0_fu_353_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal is_lastcol_fu_359_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal is_lastcol_reg_657 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln138_fu_385_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln138_reg_662 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln139_fu_391_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln139_reg_667 : STD_LOGIC_VECTOR (0 downto 0);
    signal picked_frame_fu_397_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal picked_frame_reg_672 : STD_LOGIC_VECTOR (0 downto 0);
    signal have_up_hdr_fu_419_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal have_up_hdr_reg_677 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state8 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state8 : signal is "none";
    signal grp_frame_group_fu_169_ap_done : STD_LOGIC;
    signal ap_predicate_op61_call_state8 : BOOLEAN;
    signal ap_block_state8_on_subcall_done : BOOLEAN;
    signal or_ln156_fu_424_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln169_fu_433_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state9 : BOOLEAN;
    signal grp_load_Pipeline_PICK_fu_146_ap_start : STD_LOGIC;
    signal grp_load_Pipeline_PICK_fu_146_ap_done : STD_LOGIC;
    signal grp_load_Pipeline_PICK_fu_146_ap_idle : STD_LOGIC;
    signal grp_load_Pipeline_PICK_fu_146_ap_ready : STD_LOGIC;
    signal grp_load_Pipeline_PICK_fu_146_in_left_TREADY : STD_LOGIC;
    signal grp_load_Pipeline_PICK_fu_146_in_up_TREADY : STD_LOGIC;
    signal grp_load_Pipeline_PICK_fu_146_h_data_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_load_Pipeline_PICK_fu_146_h_data_out_ap_vld : STD_LOGIC;
    signal grp_load_Pipeline_PICK_fu_146_from_left_out : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_load_Pipeline_PICK_fu_146_from_left_out_ap_vld : STD_LOGIC;
    signal grp_load_Pipeline_PICK_fu_146_from_up_out : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_load_Pipeline_PICK_fu_146_from_up_out_ap_vld : STD_LOGIC;
    signal grp_frame_group_fu_169_ap_start : STD_LOGIC;
    signal grp_frame_group_fu_169_ap_idle : STD_LOGIC;
    signal grp_frame_group_fu_169_ap_ready : STD_LOGIC;
    signal grp_frame_group_fu_169_in_left_TREADY : STD_LOGIC;
    signal grp_frame_group_fu_169_in_up_TREADY : STD_LOGIC;
    signal grp_frame_group_fu_169_use_up : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_frame_group_fu_169_have_first : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_frame_group_fu_169_my_r : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_frame_group_fu_169_my_s : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_frame_group_fu_169_fwd_right_din : STD_LOGIC_VECTOR (32 downto 0);
    signal grp_frame_group_fu_169_fwd_right_write : STD_LOGIC;
    signal grp_frame_group_fu_169_fwd_down_din : STD_LOGIC_VECTOR (32 downto 0);
    signal grp_frame_group_fu_169_fwd_down_write : STD_LOGIC;
    signal grp_frame_group_fu_169_bufA_din : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_frame_group_fu_169_bufA_write : STD_LOGIC;
    signal grp_frame_group_fu_169_bufB_din : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_frame_group_fu_169_bufB_write : STD_LOGIC;
    signal grp_load_Pipeline_CROSS_fu_207_ap_start : STD_LOGIC;
    signal grp_load_Pipeline_CROSS_fu_207_ap_done : STD_LOGIC;
    signal grp_load_Pipeline_CROSS_fu_207_ap_idle : STD_LOGIC;
    signal grp_load_Pipeline_CROSS_fu_207_ap_ready : STD_LOGIC;
    signal grp_load_Pipeline_CROSS_fu_207_xa_in_din : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_load_Pipeline_CROSS_fu_207_xa_in_write : STD_LOGIC;
    signal grp_load_Pipeline_CROSS_fu_207_xb_in_din : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_load_Pipeline_CROSS_fu_207_xb_in_write : STD_LOGIC;
    signal grp_load_Pipeline_CROSS_fu_207_in_left_TREADY : STD_LOGIC;
    signal grp_load_Pipeline_CROSS_fu_207_in_up_TREADY : STD_LOGIC;
    signal grp_load_Pipeline_IN_PASS_fu_233_ap_start : STD_LOGIC;
    signal grp_load_Pipeline_IN_PASS_fu_233_ap_done : STD_LOGIC;
    signal grp_load_Pipeline_IN_PASS_fu_233_ap_idle : STD_LOGIC;
    signal grp_load_Pipeline_IN_PASS_fu_233_ap_ready : STD_LOGIC;
    signal grp_load_Pipeline_IN_PASS_fu_233_c_pass_din : STD_LOGIC_VECTOR (32 downto 0);
    signal grp_load_Pipeline_IN_PASS_fu_233_c_pass_write : STD_LOGIC;
    signal grp_load_Pipeline_IN_PASS_fu_233_in_up_TREADY : STD_LOGIC;
    signal grp_load_Pipeline_IN_PASS5_fu_249_ap_start : STD_LOGIC;
    signal grp_load_Pipeline_IN_PASS5_fu_249_ap_done : STD_LOGIC;
    signal grp_load_Pipeline_IN_PASS5_fu_249_ap_idle : STD_LOGIC;
    signal grp_load_Pipeline_IN_PASS5_fu_249_ap_ready : STD_LOGIC;
    signal grp_load_Pipeline_IN_PASS5_fu_249_c_pass_din : STD_LOGIC_VECTOR (32 downto 0);
    signal grp_load_Pipeline_IN_PASS5_fu_249_c_pass_write : STD_LOGIC;
    signal grp_load_Pipeline_IN_PASS5_fu_249_in_left_TREADY : STD_LOGIC;
    signal grp_load_Pipeline_PICK_fu_146_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal from_left_loc_fu_100 : STD_LOGIC_VECTOR (0 downto 0);
    signal from_up_loc_fu_96 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_frame_group_fu_169_ap_start_reg : STD_LOGIC := '0';
    signal ap_block_state4_ignore_call0 : BOOLEAN;
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal grp_load_Pipeline_CROSS_fu_207_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state10 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state10 : signal is "none";
    signal ap_CS_fsm_state11 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state11 : signal is "none";
    signal grp_load_Pipeline_IN_PASS_fu_233_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state13 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state13 : signal is "none";
    signal grp_load_Pipeline_IN_PASS5_fu_249_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state15 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state15 : signal is "none";
    signal ap_CS_fsm_state16 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state16 : signal is "none";
    signal ap_block_state14 : BOOLEAN;
    signal ap_block_state14_on_subcall_done : BOOLEAN;
    signal ap_block_state12 : BOOLEAN;
    signal first_type_fu_377_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal or_ln154_fu_404_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln154_fu_408_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal have_left_hdr_fu_414_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state16_on_subcall_done : BOOLEAN;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_block_state1 : BOOLEAN;
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_block_state5_on_subcall_done : BOOLEAN;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ST_fsm_state7_blk : STD_LOGIC;
    signal ap_ST_fsm_state8_blk : STD_LOGIC;
    signal ap_ST_fsm_state9_blk : STD_LOGIC;
    signal ap_ST_fsm_state10_blk : STD_LOGIC;
    signal ap_ST_fsm_state11_blk : STD_LOGIC;
    signal ap_ST_fsm_state12_blk : STD_LOGIC;
    signal ap_ST_fsm_state13_blk : STD_LOGIC;
    signal ap_ST_fsm_state14_blk : STD_LOGIC;
    signal ap_ST_fsm_state15_blk : STD_LOGIC;
    signal ap_ST_fsm_state16_blk : STD_LOGIC;
    signal regslice_both_in_left_V_data_V_U_apdone_blk : STD_LOGIC;
    signal in_left_TDATA_int_regslice : STD_LOGIC_VECTOR (31 downto 0);
    signal in_left_TVALID_int_regslice : STD_LOGIC;
    signal in_left_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_in_left_V_data_V_U_ack_in : STD_LOGIC;
    signal regslice_both_in_left_V_keep_V_U_apdone_blk : STD_LOGIC;
    signal in_left_TKEEP_int_regslice : STD_LOGIC_VECTOR (3 downto 0);
    signal regslice_both_in_left_V_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_in_left_V_keep_V_U_ack_in : STD_LOGIC;
    signal regslice_both_in_left_V_strb_V_U_apdone_blk : STD_LOGIC;
    signal in_left_TSTRB_int_regslice : STD_LOGIC_VECTOR (3 downto 0);
    signal regslice_both_in_left_V_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_in_left_V_strb_V_U_ack_in : STD_LOGIC;
    signal regslice_both_in_left_V_last_V_U_apdone_blk : STD_LOGIC;
    signal in_left_TLAST_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_in_left_V_last_V_U_vld_out : STD_LOGIC;
    signal regslice_both_in_left_V_last_V_U_ack_in : STD_LOGIC;
    signal regslice_both_in_up_V_data_V_U_apdone_blk : STD_LOGIC;
    signal in_up_TDATA_int_regslice : STD_LOGIC_VECTOR (31 downto 0);
    signal in_up_TVALID_int_regslice : STD_LOGIC;
    signal in_up_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_in_up_V_data_V_U_ack_in : STD_LOGIC;
    signal regslice_both_in_up_V_keep_V_U_apdone_blk : STD_LOGIC;
    signal in_up_TKEEP_int_regslice : STD_LOGIC_VECTOR (3 downto 0);
    signal regslice_both_in_up_V_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_in_up_V_keep_V_U_ack_in : STD_LOGIC;
    signal regslice_both_in_up_V_strb_V_U_apdone_blk : STD_LOGIC;
    signal in_up_TSTRB_int_regslice : STD_LOGIC_VECTOR (3 downto 0);
    signal regslice_both_in_up_V_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_in_up_V_strb_V_U_ack_in : STD_LOGIC;
    signal regslice_both_in_up_V_last_V_U_apdone_blk : STD_LOGIC;
    signal in_up_TLAST_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_in_up_V_last_V_U_vld_out : STD_LOGIC;
    signal regslice_both_in_up_V_last_V_U_ack_in : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component sa_grid_load_Pipeline_PICK IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        in_left_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
        in_left_TVALID : IN STD_LOGIC;
        in_left_TREADY : OUT STD_LOGIC;
        in_left_TKEEP : IN STD_LOGIC_VECTOR (3 downto 0);
        in_left_TSTRB : IN STD_LOGIC_VECTOR (3 downto 0);
        in_left_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
        in_up_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
        in_up_TVALID : IN STD_LOGIC;
        in_up_TREADY : OUT STD_LOGIC;
        in_up_TKEEP : IN STD_LOGIC_VECTOR (3 downto 0);
        in_up_TSTRB : IN STD_LOGIC_VECTOR (3 downto 0);
        in_up_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
        h_data_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        h_data_out_ap_vld : OUT STD_LOGIC;
        from_left_out : OUT STD_LOGIC_VECTOR (0 downto 0);
        from_left_out_ap_vld : OUT STD_LOGIC;
        from_up_out : OUT STD_LOGIC_VECTOR (0 downto 0);
        from_up_out_ap_vld : OUT STD_LOGIC );
    end component;


    component sa_grid_frame_group IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        in_left_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
        in_left_TVALID : IN STD_LOGIC;
        in_left_TREADY : OUT STD_LOGIC;
        in_left_TKEEP : IN STD_LOGIC_VECTOR (3 downto 0);
        in_left_TSTRB : IN STD_LOGIC_VECTOR (3 downto 0);
        in_left_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
        in_up_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
        in_up_TVALID : IN STD_LOGIC;
        in_up_TREADY : OUT STD_LOGIC;
        in_up_TKEEP : IN STD_LOGIC_VECTOR (3 downto 0);
        in_up_TSTRB : IN STD_LOGIC_VECTOR (3 downto 0);
        in_up_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
        use_up : IN STD_LOGIC_VECTOR (0 downto 0);
        first_data_val : IN STD_LOGIC_VECTOR (31 downto 0);
        have_first : IN STD_LOGIC_VECTOR (0 downto 0);
        my_r : IN STD_LOGIC_VECTOR (3 downto 0);
        my_s : IN STD_LOGIC_VECTOR (3 downto 0);
        fwd_right_din : OUT STD_LOGIC_VECTOR (32 downto 0);
        fwd_right_full_n : IN STD_LOGIC;
        fwd_right_write : OUT STD_LOGIC;
        fwd_right_num_data_valid : IN STD_LOGIC_VECTOR (3 downto 0);
        fwd_right_fifo_cap : IN STD_LOGIC_VECTOR (3 downto 0);
        fwd_down_din : OUT STD_LOGIC_VECTOR (32 downto 0);
        fwd_down_full_n : IN STD_LOGIC;
        fwd_down_write : OUT STD_LOGIC;
        fwd_down_num_data_valid : IN STD_LOGIC_VECTOR (3 downto 0);
        fwd_down_fifo_cap : IN STD_LOGIC_VECTOR (3 downto 0);
        bufA_din : OUT STD_LOGIC_VECTOR (31 downto 0);
        bufA_full_n : IN STD_LOGIC;
        bufA_write : OUT STD_LOGIC;
        bufA_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        bufA_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        bufB_din : OUT STD_LOGIC_VECTOR (31 downto 0);
        bufB_full_n : IN STD_LOGIC;
        bufB_write : OUT STD_LOGIC;
        bufB_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        bufB_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0) );
    end component;


    component sa_grid_load_Pipeline_CROSS IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        in_left_TVALID : IN STD_LOGIC;
        xa_in_din : OUT STD_LOGIC_VECTOR (31 downto 0);
        xa_in_full_n : IN STD_LOGIC;
        xa_in_write : OUT STD_LOGIC;
        xa_in_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        xa_in_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        in_up_TVALID : IN STD_LOGIC;
        xb_in_din : OUT STD_LOGIC_VECTOR (31 downto 0);
        xb_in_full_n : IN STD_LOGIC;
        xb_in_write : OUT STD_LOGIC;
        xb_in_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        xb_in_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        in_left_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
        in_left_TREADY : OUT STD_LOGIC;
        in_left_TKEEP : IN STD_LOGIC_VECTOR (3 downto 0);
        in_left_TSTRB : IN STD_LOGIC_VECTOR (3 downto 0);
        in_left_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
        in_up_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
        in_up_TREADY : OUT STD_LOGIC;
        in_up_TKEEP : IN STD_LOGIC_VECTOR (3 downto 0);
        in_up_TSTRB : IN STD_LOGIC_VECTOR (3 downto 0);
        in_up_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
        my_s : IN STD_LOGIC_VECTOR (3 downto 0);
        my_r : IN STD_LOGIC_VECTOR (3 downto 0) );
    end component;


    component sa_grid_load_Pipeline_IN_PASS IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        in_up_TVALID : IN STD_LOGIC;
        c_pass_din : OUT STD_LOGIC_VECTOR (32 downto 0);
        c_pass_full_n : IN STD_LOGIC;
        c_pass_write : OUT STD_LOGIC;
        c_pass_num_data_valid : IN STD_LOGIC_VECTOR (4 downto 0);
        c_pass_fifo_cap : IN STD_LOGIC_VECTOR (4 downto 0);
        in_up_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
        in_up_TREADY : OUT STD_LOGIC;
        in_up_TKEEP : IN STD_LOGIC_VECTOR (3 downto 0);
        in_up_TSTRB : IN STD_LOGIC_VECTOR (3 downto 0);
        in_up_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
        is_col0 : IN STD_LOGIC_VECTOR (0 downto 0) );
    end component;


    component sa_grid_load_Pipeline_IN_PASS5 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        in_left_TVALID : IN STD_LOGIC;
        c_pass_din : OUT STD_LOGIC_VECTOR (32 downto 0);
        c_pass_full_n : IN STD_LOGIC;
        c_pass_write : OUT STD_LOGIC;
        c_pass_num_data_valid : IN STD_LOGIC_VECTOR (4 downto 0);
        c_pass_fifo_cap : IN STD_LOGIC_VECTOR (4 downto 0);
        in_left_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
        in_left_TREADY : OUT STD_LOGIC;
        in_left_TKEEP : IN STD_LOGIC_VECTOR (3 downto 0);
        in_left_TSTRB : IN STD_LOGIC_VECTOR (3 downto 0);
        in_left_TLAST : IN STD_LOGIC_VECTOR (0 downto 0) );
    end component;


    component sa_grid_regslice_both IS
    generic (
        DataWidth : INTEGER );
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        data_in : IN STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_in : IN STD_LOGIC;
        ack_in : OUT STD_LOGIC;
        data_out : OUT STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_out : OUT STD_LOGIC;
        ack_out : IN STD_LOGIC;
        apdone_blk : OUT STD_LOGIC );
    end component;



begin
    grp_load_Pipeline_PICK_fu_146 : component sa_grid_load_Pipeline_PICK
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_load_Pipeline_PICK_fu_146_ap_start,
        ap_done => grp_load_Pipeline_PICK_fu_146_ap_done,
        ap_idle => grp_load_Pipeline_PICK_fu_146_ap_idle,
        ap_ready => grp_load_Pipeline_PICK_fu_146_ap_ready,
        in_left_TDATA => in_left_TDATA_int_regslice,
        in_left_TVALID => in_left_TVALID_int_regslice,
        in_left_TREADY => grp_load_Pipeline_PICK_fu_146_in_left_TREADY,
        in_left_TKEEP => in_left_TKEEP_int_regslice,
        in_left_TSTRB => in_left_TSTRB_int_regslice,
        in_left_TLAST => in_left_TLAST_int_regslice,
        in_up_TDATA => in_up_TDATA_int_regslice,
        in_up_TVALID => in_up_TVALID_int_regslice,
        in_up_TREADY => grp_load_Pipeline_PICK_fu_146_in_up_TREADY,
        in_up_TKEEP => in_up_TKEEP_int_regslice,
        in_up_TSTRB => in_up_TSTRB_int_regslice,
        in_up_TLAST => in_up_TLAST_int_regslice,
        h_data_out => grp_load_Pipeline_PICK_fu_146_h_data_out,
        h_data_out_ap_vld => grp_load_Pipeline_PICK_fu_146_h_data_out_ap_vld,
        from_left_out => grp_load_Pipeline_PICK_fu_146_from_left_out,
        from_left_out_ap_vld => grp_load_Pipeline_PICK_fu_146_from_left_out_ap_vld,
        from_up_out => grp_load_Pipeline_PICK_fu_146_from_up_out,
        from_up_out_ap_vld => grp_load_Pipeline_PICK_fu_146_from_up_out_ap_vld);

    grp_frame_group_fu_169 : component sa_grid_frame_group
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_frame_group_fu_169_ap_start,
        ap_done => grp_frame_group_fu_169_ap_done,
        ap_idle => grp_frame_group_fu_169_ap_idle,
        ap_ready => grp_frame_group_fu_169_ap_ready,
        in_left_TDATA => in_left_TDATA_int_regslice,
        in_left_TVALID => in_left_TVALID_int_regslice,
        in_left_TREADY => grp_frame_group_fu_169_in_left_TREADY,
        in_left_TKEEP => in_left_TKEEP_int_regslice,
        in_left_TSTRB => in_left_TSTRB_int_regslice,
        in_left_TLAST => in_left_TLAST_int_regslice,
        in_up_TDATA => in_up_TDATA_int_regslice,
        in_up_TVALID => in_up_TVALID_int_regslice,
        in_up_TREADY => grp_frame_group_fu_169_in_up_TREADY,
        in_up_TKEEP => in_up_TKEEP_int_regslice,
        in_up_TSTRB => in_up_TSTRB_int_regslice,
        in_up_TLAST => in_up_TLAST_int_regslice,
        use_up => grp_frame_group_fu_169_use_up,
        first_data_val => grp_load_Pipeline_PICK_fu_146_h_data_out,
        have_first => grp_frame_group_fu_169_have_first,
        my_r => grp_frame_group_fu_169_my_r,
        my_s => grp_frame_group_fu_169_my_s,
        fwd_right_din => grp_frame_group_fu_169_fwd_right_din,
        fwd_right_full_n => fwd_right_full_n,
        fwd_right_write => grp_frame_group_fu_169_fwd_right_write,
        fwd_right_num_data_valid => ap_const_lv4_0,
        fwd_right_fifo_cap => ap_const_lv4_0,
        fwd_down_din => grp_frame_group_fu_169_fwd_down_din,
        fwd_down_full_n => fwd_down_full_n,
        fwd_down_write => grp_frame_group_fu_169_fwd_down_write,
        fwd_down_num_data_valid => ap_const_lv4_0,
        fwd_down_fifo_cap => ap_const_lv4_0,
        bufA_din => grp_frame_group_fu_169_bufA_din,
        bufA_full_n => bufA_full_n,
        bufA_write => grp_frame_group_fu_169_bufA_write,
        bufA_num_data_valid => ap_const_lv3_0,
        bufA_fifo_cap => ap_const_lv3_0,
        bufB_din => grp_frame_group_fu_169_bufB_din,
        bufB_full_n => bufB_full_n,
        bufB_write => grp_frame_group_fu_169_bufB_write,
        bufB_num_data_valid => ap_const_lv3_0,
        bufB_fifo_cap => ap_const_lv3_0);

    grp_load_Pipeline_CROSS_fu_207 : component sa_grid_load_Pipeline_CROSS
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_load_Pipeline_CROSS_fu_207_ap_start,
        ap_done => grp_load_Pipeline_CROSS_fu_207_ap_done,
        ap_idle => grp_load_Pipeline_CROSS_fu_207_ap_idle,
        ap_ready => grp_load_Pipeline_CROSS_fu_207_ap_ready,
        in_left_TVALID => in_left_TVALID_int_regslice,
        xa_in_din => grp_load_Pipeline_CROSS_fu_207_xa_in_din,
        xa_in_full_n => xa_in_full_n,
        xa_in_write => grp_load_Pipeline_CROSS_fu_207_xa_in_write,
        xa_in_num_data_valid => ap_const_lv3_0,
        xa_in_fifo_cap => ap_const_lv3_0,
        in_up_TVALID => in_up_TVALID_int_regslice,
        xb_in_din => grp_load_Pipeline_CROSS_fu_207_xb_in_din,
        xb_in_full_n => xb_in_full_n,
        xb_in_write => grp_load_Pipeline_CROSS_fu_207_xb_in_write,
        xb_in_num_data_valid => ap_const_lv3_0,
        xb_in_fifo_cap => ap_const_lv3_0,
        in_left_TDATA => in_left_TDATA_int_regslice,
        in_left_TREADY => grp_load_Pipeline_CROSS_fu_207_in_left_TREADY,
        in_left_TKEEP => in_left_TKEEP_int_regslice,
        in_left_TSTRB => in_left_TSTRB_int_regslice,
        in_left_TLAST => in_left_TLAST_int_regslice,
        in_up_TDATA => in_up_TDATA_int_regslice,
        in_up_TREADY => grp_load_Pipeline_CROSS_fu_207_in_up_TREADY,
        in_up_TKEEP => in_up_TKEEP_int_regslice,
        in_up_TSTRB => in_up_TSTRB_int_regslice,
        in_up_TLAST => in_up_TLAST_int_regslice,
        my_s => my_s_reg_640,
        my_r => my_r_reg_634);

    grp_load_Pipeline_IN_PASS_fu_233 : component sa_grid_load_Pipeline_IN_PASS
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_load_Pipeline_IN_PASS_fu_233_ap_start,
        ap_done => grp_load_Pipeline_IN_PASS_fu_233_ap_done,
        ap_idle => grp_load_Pipeline_IN_PASS_fu_233_ap_idle,
        ap_ready => grp_load_Pipeline_IN_PASS_fu_233_ap_ready,
        in_up_TVALID => in_up_TVALID_int_regslice,
        c_pass_din => grp_load_Pipeline_IN_PASS_fu_233_c_pass_din,
        c_pass_full_n => c_pass_full_n,
        c_pass_write => grp_load_Pipeline_IN_PASS_fu_233_c_pass_write,
        c_pass_num_data_valid => ap_const_lv5_0,
        c_pass_fifo_cap => ap_const_lv5_0,
        in_up_TDATA => in_up_TDATA_int_regslice,
        in_up_TREADY => grp_load_Pipeline_IN_PASS_fu_233_in_up_TREADY,
        in_up_TKEEP => in_up_TKEEP_int_regslice,
        in_up_TSTRB => in_up_TSTRB_int_regslice,
        in_up_TLAST => in_up_TLAST_int_regslice,
        is_col0 => ap_const_lv1_0);

    grp_load_Pipeline_IN_PASS5_fu_249 : component sa_grid_load_Pipeline_IN_PASS5
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_load_Pipeline_IN_PASS5_fu_249_ap_start,
        ap_done => grp_load_Pipeline_IN_PASS5_fu_249_ap_done,
        ap_idle => grp_load_Pipeline_IN_PASS5_fu_249_ap_idle,
        ap_ready => grp_load_Pipeline_IN_PASS5_fu_249_ap_ready,
        in_left_TVALID => in_left_TVALID_int_regslice,
        c_pass_din => grp_load_Pipeline_IN_PASS5_fu_249_c_pass_din,
        c_pass_full_n => c_pass_full_n,
        c_pass_write => grp_load_Pipeline_IN_PASS5_fu_249_c_pass_write,
        c_pass_num_data_valid => ap_const_lv5_0,
        c_pass_fifo_cap => ap_const_lv5_0,
        in_left_TDATA => in_left_TDATA_int_regslice,
        in_left_TREADY => grp_load_Pipeline_IN_PASS5_fu_249_in_left_TREADY,
        in_left_TKEEP => in_left_TKEEP_int_regslice,
        in_left_TSTRB => in_left_TSTRB_int_regslice,
        in_left_TLAST => in_left_TLAST_int_regslice);

    regslice_both_in_left_V_data_V_U : component sa_grid_regslice_both
    generic map (
        DataWidth => 32)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => in_left_TDATA,
        vld_in => in_left_TVALID,
        ack_in => regslice_both_in_left_V_data_V_U_ack_in,
        data_out => in_left_TDATA_int_regslice,
        vld_out => in_left_TVALID_int_regslice,
        ack_out => in_left_TREADY_int_regslice,
        apdone_blk => regslice_both_in_left_V_data_V_U_apdone_blk);

    regslice_both_in_left_V_keep_V_U : component sa_grid_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => in_left_TKEEP,
        vld_in => in_left_TVALID,
        ack_in => regslice_both_in_left_V_keep_V_U_ack_in,
        data_out => in_left_TKEEP_int_regslice,
        vld_out => regslice_both_in_left_V_keep_V_U_vld_out,
        ack_out => in_left_TREADY_int_regslice,
        apdone_blk => regslice_both_in_left_V_keep_V_U_apdone_blk);

    regslice_both_in_left_V_strb_V_U : component sa_grid_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => in_left_TSTRB,
        vld_in => in_left_TVALID,
        ack_in => regslice_both_in_left_V_strb_V_U_ack_in,
        data_out => in_left_TSTRB_int_regslice,
        vld_out => regslice_both_in_left_V_strb_V_U_vld_out,
        ack_out => in_left_TREADY_int_regslice,
        apdone_blk => regslice_both_in_left_V_strb_V_U_apdone_blk);

    regslice_both_in_left_V_last_V_U : component sa_grid_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => in_left_TLAST,
        vld_in => in_left_TVALID,
        ack_in => regslice_both_in_left_V_last_V_U_ack_in,
        data_out => in_left_TLAST_int_regslice,
        vld_out => regslice_both_in_left_V_last_V_U_vld_out,
        ack_out => in_left_TREADY_int_regslice,
        apdone_blk => regslice_both_in_left_V_last_V_U_apdone_blk);

    regslice_both_in_up_V_data_V_U : component sa_grid_regslice_both
    generic map (
        DataWidth => 32)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => in_up_TDATA,
        vld_in => in_up_TVALID,
        ack_in => regslice_both_in_up_V_data_V_U_ack_in,
        data_out => in_up_TDATA_int_regslice,
        vld_out => in_up_TVALID_int_regslice,
        ack_out => in_up_TREADY_int_regslice,
        apdone_blk => regslice_both_in_up_V_data_V_U_apdone_blk);

    regslice_both_in_up_V_keep_V_U : component sa_grid_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => in_up_TKEEP,
        vld_in => in_up_TVALID,
        ack_in => regslice_both_in_up_V_keep_V_U_ack_in,
        data_out => in_up_TKEEP_int_regslice,
        vld_out => regslice_both_in_up_V_keep_V_U_vld_out,
        ack_out => in_up_TREADY_int_regslice,
        apdone_blk => regslice_both_in_up_V_keep_V_U_apdone_blk);

    regslice_both_in_up_V_strb_V_U : component sa_grid_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => in_up_TSTRB,
        vld_in => in_up_TVALID,
        ack_in => regslice_both_in_up_V_strb_V_U_ack_in,
        data_out => in_up_TSTRB_int_regslice,
        vld_out => regslice_both_in_up_V_strb_V_U_vld_out,
        ack_out => in_up_TREADY_int_regslice,
        apdone_blk => regslice_both_in_up_V_strb_V_U_apdone_blk);

    regslice_both_in_up_V_last_V_U : component sa_grid_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => in_up_TLAST,
        vld_in => in_up_TVALID,
        ack_in => regslice_both_in_up_V_last_V_U_ack_in,
        data_out => in_up_TLAST_int_regslice,
        vld_out => regslice_both_in_up_V_last_V_U_vld_out,
        ack_out => in_up_TREADY_int_regslice,
        apdone_blk => regslice_both_in_up_V_last_V_U_apdone_blk);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_state16) and (ap_const_boolean_0 = ap_block_state16_on_subcall_done))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    grp_frame_group_fu_169_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_frame_group_fu_169_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_state7) or ((ap_const_logic_1 = ap_CS_fsm_state4) and (is_row0_fu_347_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_state4_ignore_call0)) or ((ap_const_logic_1 = ap_CS_fsm_state4) and (is_col0_fu_353_p2 = ap_const_lv1_1) and (is_row0_fu_347_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_state4_ignore_call0)))) then 
                    grp_frame_group_fu_169_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_frame_group_fu_169_ap_ready = ap_const_logic_1)) then 
                    grp_frame_group_fu_169_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_load_Pipeline_CROSS_fu_207_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_load_Pipeline_CROSS_fu_207_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
                    grp_load_Pipeline_CROSS_fu_207_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_load_Pipeline_CROSS_fu_207_ap_ready = ap_const_logic_1)) then 
                    grp_load_Pipeline_CROSS_fu_207_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_load_Pipeline_IN_PASS5_fu_249_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_load_Pipeline_IN_PASS5_fu_249_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state15)) then 
                    grp_load_Pipeline_IN_PASS5_fu_249_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_load_Pipeline_IN_PASS5_fu_249_ap_ready = ap_const_logic_1)) then 
                    grp_load_Pipeline_IN_PASS5_fu_249_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_load_Pipeline_IN_PASS_fu_233_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_load_Pipeline_IN_PASS_fu_233_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state13)) then 
                    grp_load_Pipeline_IN_PASS_fu_233_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_load_Pipeline_IN_PASS_fu_233_ap_ready = ap_const_logic_1)) then 
                    grp_load_Pipeline_IN_PASS_fu_233_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_load_Pipeline_PICK_fu_146_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_load_Pipeline_PICK_fu_146_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
                    grp_load_Pipeline_PICK_fu_146_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_load_Pipeline_PICK_fu_146_ap_ready = ap_const_logic_1)) then 
                    grp_load_Pipeline_PICK_fu_146_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    start_once_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                start_once_reg <= ap_const_logic_0;
            else
                if (((internal_ap_ready = ap_const_logic_0) and (real_start = ap_const_logic_1))) then 
                    start_once_reg <= ap_const_logic_1;
                elsif ((internal_ap_ready = ap_const_logic_1)) then 
                    start_once_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_load_Pipeline_PICK_fu_146_from_left_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                from_left_loc_fu_100 <= grp_load_Pipeline_PICK_fu_146_from_left_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_load_Pipeline_PICK_fu_146_from_up_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                from_up_loc_fu_96 <= grp_load_Pipeline_PICK_fu_146_from_up_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state8) and (ap_const_boolean_0 = ap_block_state8_on_subcall_done))) then
                have_up_hdr_reg_677 <= have_up_hdr_fu_419_p2;
                or_ln156_reg_682 <= or_ln156_fu_424_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state4) and (ap_const_boolean_0 = ap_block_state4))) then
                icmp_ln138_reg_662 <= icmp_ln138_fu_385_p2;
                icmp_ln139_reg_667 <= icmp_ln139_fu_391_p2;
                is_col0_reg_652 <= is_col0_fu_353_p2;
                is_lastcol_reg_657 <= is_lastcol_fu_359_p2;
                is_row0_reg_646 <= is_row0_fu_347_p2;
                my_r_reg_634 <= grp_load_Pipeline_PICK_fu_146_h_data_out(19 downto 16);
                my_s_reg_640 <= grp_load_Pipeline_PICK_fu_146_h_data_out(15 downto 12);
                picked_frame_reg_672 <= picked_frame_fu_397_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state9) and (ap_const_boolean_0 = ap_block_state9))) then
                or_ln169_reg_689 <= or_ln169_fu_433_p2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_state9, ap_CS_fsm_state14, is_col0_reg_652, ap_CS_fsm_state12, or_ln169_reg_689, ap_CS_fsm_state4, ap_block_state4, is_row0_fu_347_p2, ap_CS_fsm_state8, grp_frame_group_fu_169_ap_done, ap_block_state8_on_subcall_done, ap_block_state9, grp_load_Pipeline_PICK_fu_146_ap_done, grp_load_Pipeline_CROSS_fu_207_ap_done, ap_CS_fsm_state3, ap_CS_fsm_state5, ap_CS_fsm_state6, ap_CS_fsm_state11, ap_CS_fsm_state16, ap_block_state14, ap_block_state14_on_subcall_done, ap_block_state12, ap_block_state16_on_subcall_done, ap_block_state1, ap_block_state5_on_subcall_done)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                if (((grp_load_Pipeline_PICK_fu_146_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state4 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state4) and (is_row0_fu_347_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_state4))) then
                    ap_NS_fsm <= ap_ST_fsm_state5;
                elsif (((ap_const_logic_1 = ap_CS_fsm_state4) and (is_row0_fu_347_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_state4))) then
                    ap_NS_fsm <= ap_ST_fsm_state6;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when ap_ST_fsm_state5 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state5) and (ap_const_boolean_0 = ap_block_state5_on_subcall_done))) then
                    ap_NS_fsm <= ap_ST_fsm_state8;
                else
                    ap_NS_fsm <= ap_ST_fsm_state5;
                end if;
            when ap_ST_fsm_state6 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state6) and (grp_frame_group_fu_169_ap_done = ap_const_logic_1) and (is_col0_reg_652 = ap_const_lv1_0))) then
                    ap_NS_fsm <= ap_ST_fsm_state8;
                elsif (((ap_const_logic_1 = ap_CS_fsm_state6) and (grp_frame_group_fu_169_ap_done = ap_const_logic_1) and (is_col0_reg_652 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state7;
                else
                    ap_NS_fsm <= ap_ST_fsm_state6;
                end if;
            when ap_ST_fsm_state7 => 
                ap_NS_fsm <= ap_ST_fsm_state8;
            when ap_ST_fsm_state8 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state8) and (ap_const_boolean_0 = ap_block_state8_on_subcall_done))) then
                    ap_NS_fsm <= ap_ST_fsm_state9;
                else
                    ap_NS_fsm <= ap_ST_fsm_state8;
                end if;
            when ap_ST_fsm_state9 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state9) and (ap_const_boolean_0 = ap_block_state9))) then
                    ap_NS_fsm <= ap_ST_fsm_state10;
                else
                    ap_NS_fsm <= ap_ST_fsm_state9;
                end if;
            when ap_ST_fsm_state10 => 
                ap_NS_fsm <= ap_ST_fsm_state11;
            when ap_ST_fsm_state11 => 
                if (((grp_load_Pipeline_CROSS_fu_207_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state11))) then
                    ap_NS_fsm <= ap_ST_fsm_state12;
                else
                    ap_NS_fsm <= ap_ST_fsm_state11;
                end if;
            when ap_ST_fsm_state12 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state12) and (ap_const_boolean_0 = ap_block_state12) and (or_ln169_reg_689 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state14;
                elsif (((ap_const_logic_1 = ap_CS_fsm_state12) and (ap_const_boolean_0 = ap_block_state12) and (or_ln169_reg_689 = ap_const_lv1_0))) then
                    ap_NS_fsm <= ap_ST_fsm_state13;
                else
                    ap_NS_fsm <= ap_ST_fsm_state12;
                end if;
            when ap_ST_fsm_state13 => 
                ap_NS_fsm <= ap_ST_fsm_state14;
            when ap_ST_fsm_state14 => 
                if ((not(((ap_const_boolean_1 = ap_block_state14_on_subcall_done) or (ap_const_boolean_1 = ap_block_state14))) and (ap_const_logic_1 = ap_CS_fsm_state14) and (is_col0_reg_652 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state16;
                elsif ((not(((ap_const_boolean_1 = ap_block_state14_on_subcall_done) or (ap_const_boolean_1 = ap_block_state14))) and (ap_const_logic_1 = ap_CS_fsm_state14) and (is_col0_reg_652 = ap_const_lv1_0))) then
                    ap_NS_fsm <= ap_ST_fsm_state15;
                else
                    ap_NS_fsm <= ap_ST_fsm_state14;
                end if;
            when ap_ST_fsm_state15 => 
                ap_NS_fsm <= ap_ST_fsm_state16;
            when ap_ST_fsm_state16 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state16) and (ap_const_boolean_0 = ap_block_state16_on_subcall_done))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state16;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXXXXXXXXX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state10 <= ap_CS_fsm(9);
    ap_CS_fsm_state11 <= ap_CS_fsm(10);
    ap_CS_fsm_state12 <= ap_CS_fsm(11);
    ap_CS_fsm_state13 <= ap_CS_fsm(12);
    ap_CS_fsm_state14 <= ap_CS_fsm(13);
    ap_CS_fsm_state15 <= ap_CS_fsm(14);
    ap_CS_fsm_state16 <= ap_CS_fsm(15);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_CS_fsm_state7 <= ap_CS_fsm(6);
    ap_CS_fsm_state8 <= ap_CS_fsm(7);
    ap_CS_fsm_state9 <= ap_CS_fsm(8);
    ap_ST_fsm_state10_blk <= ap_const_logic_0;

    ap_ST_fsm_state11_blk_assign_proc : process(grp_load_Pipeline_CROSS_fu_207_ap_done)
    begin
        if ((grp_load_Pipeline_CROSS_fu_207_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state11_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state11_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state12_blk_assign_proc : process(ap_block_state12)
    begin
        if ((ap_const_boolean_1 = ap_block_state12)) then 
            ap_ST_fsm_state12_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state12_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state13_blk <= ap_const_logic_0;

    ap_ST_fsm_state14_blk_assign_proc : process(ap_block_state14, ap_block_state14_on_subcall_done)
    begin
        if (((ap_const_boolean_1 = ap_block_state14_on_subcall_done) or (ap_const_boolean_1 = ap_block_state14))) then 
            ap_ST_fsm_state14_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state14_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state15_blk <= ap_const_logic_0;

    ap_ST_fsm_state16_blk_assign_proc : process(ap_block_state16_on_subcall_done)
    begin
        if ((ap_const_boolean_1 = ap_block_state16_on_subcall_done)) then 
            ap_ST_fsm_state16_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state16_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state1_blk_assign_proc : process(ap_block_state1)
    begin
        if ((ap_const_boolean_1 = ap_block_state1)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;

    ap_ST_fsm_state3_blk_assign_proc : process(grp_load_Pipeline_PICK_fu_146_ap_done)
    begin
        if ((grp_load_Pipeline_PICK_fu_146_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state3_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state3_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state4_blk_assign_proc : process(ap_block_state4)
    begin
        if ((ap_const_boolean_1 = ap_block_state4)) then 
            ap_ST_fsm_state4_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state4_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state5_blk_assign_proc : process(ap_block_state5_on_subcall_done)
    begin
        if ((ap_const_boolean_1 = ap_block_state5_on_subcall_done)) then 
            ap_ST_fsm_state5_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state5_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state6_blk_assign_proc : process(grp_frame_group_fu_169_ap_done)
    begin
        if ((grp_frame_group_fu_169_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state6_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state6_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state7_blk <= ap_const_logic_0;

    ap_ST_fsm_state8_blk_assign_proc : process(ap_block_state8_on_subcall_done)
    begin
        if ((ap_const_boolean_1 = ap_block_state8_on_subcall_done)) then 
            ap_ST_fsm_state8_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state8_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state9_blk_assign_proc : process(ap_block_state9)
    begin
        if ((ap_const_boolean_1 = ap_block_state9)) then 
            ap_ST_fsm_state9_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state9_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state1_assign_proc : process(real_start, ap_done_reg)
    begin
                ap_block_state1 <= ((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0));
    end process;


    ap_block_state12_assign_proc : process(or_ln169_reg_689, in_up_TVALID_int_regslice)
    begin
                ap_block_state12 <= ((in_up_TVALID_int_regslice = ap_const_logic_0) and (or_ln169_reg_689 = ap_const_lv1_0));
    end process;


    ap_block_state14_assign_proc : process(is_col0_reg_652, in_left_TVALID_int_regslice)
    begin
                ap_block_state14 <= ((in_left_TVALID_int_regslice = ap_const_logic_0) and (is_col0_reg_652 = ap_const_lv1_0));
    end process;


    ap_block_state14_on_subcall_done_assign_proc : process(or_ln169_reg_689, grp_load_Pipeline_IN_PASS_fu_233_ap_done)
    begin
                ap_block_state14_on_subcall_done <= ((grp_load_Pipeline_IN_PASS_fu_233_ap_done = ap_const_logic_0) and (or_ln169_reg_689 = ap_const_lv1_0));
    end process;


    ap_block_state16_on_subcall_done_assign_proc : process(is_col0_reg_652, grp_load_Pipeline_IN_PASS5_fu_249_ap_done)
    begin
                ap_block_state16_on_subcall_done <= ((grp_load_Pipeline_IN_PASS5_fu_249_ap_done = ap_const_logic_0) and (is_col0_reg_652 = ap_const_lv1_0));
    end process;


    ap_block_state4_assign_proc : process(pos_c_full_n, pos_s_full_n)
    begin
                ap_block_state4 <= ((pos_s_full_n = ap_const_logic_0) or (pos_c_full_n = ap_const_logic_0));
    end process;


    ap_block_state4_ignore_call0_assign_proc : process(pos_c_full_n, pos_s_full_n)
    begin
                ap_block_state4_ignore_call0 <= ((pos_s_full_n = ap_const_logic_0) or (pos_c_full_n = ap_const_logic_0));
    end process;


    ap_block_state5_on_subcall_done_assign_proc : process(is_col0_reg_652, grp_frame_group_fu_169_ap_done)
    begin
                ap_block_state5_on_subcall_done <= ((grp_frame_group_fu_169_ap_done = ap_const_logic_0) and (is_col0_reg_652 = ap_const_lv1_1));
    end process;


    ap_block_state8_on_subcall_done_assign_proc : process(grp_frame_group_fu_169_ap_done, ap_predicate_op61_call_state8)
    begin
                ap_block_state8_on_subcall_done <= ((ap_predicate_op61_call_state8 = ap_const_boolean_1) and (grp_frame_group_fu_169_ap_done = ap_const_logic_0));
    end process;


    ap_block_state9_assign_proc : process(or_ln156_reg_682, or_ln157_fu_429_p2, in_left_TVALID_int_regslice, in_up_TVALID_int_regslice)
    begin
                ap_block_state9 <= (((in_up_TVALID_int_regslice = ap_const_logic_0) and (or_ln157_fu_429_p2 = ap_const_lv1_0)) or ((in_left_TVALID_int_regslice = ap_const_logic_0) and (or_ln156_reg_682 = ap_const_lv1_0)));
    end process;


    ap_done_assign_proc : process(ap_done_reg, ap_CS_fsm_state16, ap_block_state16_on_subcall_done)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state16) and (ap_const_boolean_0 = ap_block_state16_on_subcall_done))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(real_start, ap_CS_fsm_state1)
    begin
        if (((real_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_predicate_op61_call_state8_assign_proc : process(is_col0_reg_652, is_row0_reg_646)
    begin
                ap_predicate_op61_call_state8 <= ((is_row0_reg_646 = ap_const_lv1_1) and (is_col0_reg_652 = ap_const_lv1_1));
    end process;

    ap_ready <= internal_ap_ready;
    bufA_din <= grp_frame_group_fu_169_bufA_din;

    bufA_write_assign_proc : process(is_col0_reg_652, ap_CS_fsm_state8, ap_predicate_op61_call_state8, grp_frame_group_fu_169_bufA_write, ap_CS_fsm_state5, ap_CS_fsm_state6)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state6) or ((ap_const_logic_1 = ap_CS_fsm_state5) and (is_col0_reg_652 = ap_const_lv1_1)) or ((ap_const_logic_1 = ap_CS_fsm_state8) and (ap_predicate_op61_call_state8 = ap_const_boolean_1)))) then 
            bufA_write <= grp_frame_group_fu_169_bufA_write;
        else 
            bufA_write <= ap_const_logic_0;
        end if; 
    end process;

    bufB_din <= grp_frame_group_fu_169_bufB_din;

    bufB_write_assign_proc : process(is_col0_reg_652, ap_CS_fsm_state8, ap_predicate_op61_call_state8, grp_frame_group_fu_169_bufB_write, ap_CS_fsm_state5, ap_CS_fsm_state6)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state6) or ((ap_const_logic_1 = ap_CS_fsm_state5) and (is_col0_reg_652 = ap_const_lv1_1)) or ((ap_const_logic_1 = ap_CS_fsm_state8) and (ap_predicate_op61_call_state8 = ap_const_boolean_1)))) then 
            bufB_write <= grp_frame_group_fu_169_bufB_write;
        else 
            bufB_write <= ap_const_logic_0;
        end if; 
    end process;


    c_pass_din_assign_proc : process(ap_CS_fsm_state14, is_col0_reg_652, or_ln169_reg_689, grp_load_Pipeline_IN_PASS_fu_233_c_pass_din, grp_load_Pipeline_IN_PASS5_fu_249_c_pass_din, ap_CS_fsm_state16)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state16) and (is_col0_reg_652 = ap_const_lv1_0))) then 
            c_pass_din <= grp_load_Pipeline_IN_PASS5_fu_249_c_pass_din;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state14) and (or_ln169_reg_689 = ap_const_lv1_0))) then 
            c_pass_din <= grp_load_Pipeline_IN_PASS_fu_233_c_pass_din;
        else 
            c_pass_din <= grp_load_Pipeline_IN_PASS5_fu_249_c_pass_din;
        end if; 
    end process;


    c_pass_write_assign_proc : process(ap_CS_fsm_state14, is_col0_reg_652, or_ln169_reg_689, grp_load_Pipeline_IN_PASS_fu_233_c_pass_write, grp_load_Pipeline_IN_PASS5_fu_249_c_pass_write, ap_CS_fsm_state16)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state16) and (is_col0_reg_652 = ap_const_lv1_0))) then 
            c_pass_write <= grp_load_Pipeline_IN_PASS5_fu_249_c_pass_write;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state14) and (or_ln169_reg_689 = ap_const_lv1_0))) then 
            c_pass_write <= grp_load_Pipeline_IN_PASS_fu_233_c_pass_write;
        else 
            c_pass_write <= ap_const_logic_0;
        end if; 
    end process;

    first_type_fu_377_p3 <= grp_load_Pipeline_PICK_fu_146_h_data_out(23 downto 20);
    fwd_down_din <= grp_frame_group_fu_169_fwd_down_din;

    fwd_down_write_assign_proc : process(is_col0_reg_652, ap_CS_fsm_state8, ap_predicate_op61_call_state8, grp_frame_group_fu_169_fwd_down_write, ap_CS_fsm_state5, ap_CS_fsm_state6)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state6) or ((ap_const_logic_1 = ap_CS_fsm_state5) and (is_col0_reg_652 = ap_const_lv1_1)) or ((ap_const_logic_1 = ap_CS_fsm_state8) and (ap_predicate_op61_call_state8 = ap_const_boolean_1)))) then 
            fwd_down_write <= grp_frame_group_fu_169_fwd_down_write;
        else 
            fwd_down_write <= ap_const_logic_0;
        end if; 
    end process;

    fwd_right_din <= grp_frame_group_fu_169_fwd_right_din;

    fwd_right_write_assign_proc : process(is_col0_reg_652, ap_CS_fsm_state8, ap_predicate_op61_call_state8, grp_frame_group_fu_169_fwd_right_write, ap_CS_fsm_state5, ap_CS_fsm_state6)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state6) or ((ap_const_logic_1 = ap_CS_fsm_state5) and (is_col0_reg_652 = ap_const_lv1_1)) or ((ap_const_logic_1 = ap_CS_fsm_state8) and (ap_predicate_op61_call_state8 = ap_const_boolean_1)))) then 
            fwd_right_write <= grp_frame_group_fu_169_fwd_right_write;
        else 
            fwd_right_write <= ap_const_logic_0;
        end if; 
    end process;

    grp_frame_group_fu_169_ap_start <= grp_frame_group_fu_169_ap_start_reg;

    grp_frame_group_fu_169_have_first_assign_proc : process(is_col0_reg_652, picked_frame_reg_672, ap_CS_fsm_state8, ap_predicate_op61_call_state8, ap_CS_fsm_state5, ap_CS_fsm_state6)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state8) and (ap_predicate_op61_call_state8 = ap_const_boolean_1))) then 
            grp_frame_group_fu_169_have_first <= ap_const_lv1_0;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state6) or ((ap_const_logic_1 = ap_CS_fsm_state5) and (is_col0_reg_652 = ap_const_lv1_1)))) then 
            grp_frame_group_fu_169_have_first <= picked_frame_reg_672;
        else 
            grp_frame_group_fu_169_have_first <= "X";
        end if; 
    end process;


    grp_frame_group_fu_169_my_r_assign_proc : process(is_col0_reg_652, my_r_reg_634, ap_CS_fsm_state8, ap_predicate_op61_call_state8, ap_CS_fsm_state5, ap_CS_fsm_state6)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state6) or ((ap_const_logic_1 = ap_CS_fsm_state8) and (ap_predicate_op61_call_state8 = ap_const_boolean_1)))) then 
            grp_frame_group_fu_169_my_r <= ap_const_lv4_0;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state5) and (is_col0_reg_652 = ap_const_lv1_1))) then 
            grp_frame_group_fu_169_my_r <= my_r_reg_634;
        else 
            grp_frame_group_fu_169_my_r <= "XXXX";
        end if; 
    end process;


    grp_frame_group_fu_169_my_s_assign_proc : process(is_col0_reg_652, my_s_reg_640, ap_CS_fsm_state8, ap_predicate_op61_call_state8, ap_CS_fsm_state5, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            grp_frame_group_fu_169_my_s <= my_s_reg_640;
        elsif ((((ap_const_logic_1 = ap_CS_fsm_state5) and (is_col0_reg_652 = ap_const_lv1_1)) or ((ap_const_logic_1 = ap_CS_fsm_state8) and (ap_predicate_op61_call_state8 = ap_const_boolean_1)))) then 
            grp_frame_group_fu_169_my_s <= ap_const_lv4_0;
        else 
            grp_frame_group_fu_169_my_s <= "XXXX";
        end if; 
    end process;


    grp_frame_group_fu_169_use_up_assign_proc : process(is_col0_reg_652, ap_CS_fsm_state8, ap_predicate_op61_call_state8, ap_CS_fsm_state5, ap_CS_fsm_state6)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state6) or ((ap_const_logic_1 = ap_CS_fsm_state8) and (ap_predicate_op61_call_state8 = ap_const_boolean_1)))) then 
            grp_frame_group_fu_169_use_up <= ap_const_lv1_0;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state5) and (is_col0_reg_652 = ap_const_lv1_1))) then 
            grp_frame_group_fu_169_use_up <= ap_const_lv1_1;
        else 
            grp_frame_group_fu_169_use_up <= "X";
        end if; 
    end process;

    grp_load_Pipeline_CROSS_fu_207_ap_start <= grp_load_Pipeline_CROSS_fu_207_ap_start_reg;
    grp_load_Pipeline_IN_PASS5_fu_249_ap_start <= grp_load_Pipeline_IN_PASS5_fu_249_ap_start_reg;
    grp_load_Pipeline_IN_PASS_fu_233_ap_start <= grp_load_Pipeline_IN_PASS_fu_233_ap_start_reg;
    grp_load_Pipeline_PICK_fu_146_ap_start <= grp_load_Pipeline_PICK_fu_146_ap_start_reg;
    have_left_hdr_fu_414_p2 <= (xor_ln154_fu_408_p2 and from_left_loc_fu_100);
    have_up_hdr_fu_419_p2 <= (xor_ln154_fu_408_p2 and from_up_loc_fu_96);
    icmp_ln138_fu_385_p2 <= "1" when (first_type_fu_377_p3 = ap_const_lv4_0) else "0";
    icmp_ln139_fu_391_p2 <= "1" when (first_type_fu_377_p3 = ap_const_lv4_1) else "0";

    in_left_TDATA_blk_n_assign_proc : process(ap_CS_fsm_state9, or_ln156_reg_682, ap_CS_fsm_state14, is_col0_reg_652, in_left_TVALID_int_regslice)
    begin
        if ((((ap_const_logic_1 = ap_CS_fsm_state14) and (is_col0_reg_652 = ap_const_lv1_0)) or ((ap_const_logic_1 = ap_CS_fsm_state9) and (or_ln156_reg_682 = ap_const_lv1_0)))) then 
            in_left_TDATA_blk_n <= in_left_TVALID_int_regslice;
        else 
            in_left_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    in_left_TREADY <= regslice_both_in_left_V_data_V_U_ack_in;

    in_left_TREADY_int_regslice_assign_proc : process(ap_CS_fsm_state9, or_ln156_reg_682, ap_CS_fsm_state14, is_col0_reg_652, ap_CS_fsm_state8, ap_predicate_op61_call_state8, ap_block_state9, grp_load_Pipeline_PICK_fu_146_in_left_TREADY, grp_frame_group_fu_169_in_left_TREADY, grp_load_Pipeline_CROSS_fu_207_in_left_TREADY, grp_load_Pipeline_IN_PASS5_fu_249_in_left_TREADY, ap_CS_fsm_state3, ap_CS_fsm_state5, ap_CS_fsm_state6, ap_CS_fsm_state11, ap_CS_fsm_state16, ap_block_state14, ap_block_state14_on_subcall_done)
    begin
        if (((not(((ap_const_boolean_1 = ap_block_state14_on_subcall_done) or (ap_const_boolean_1 = ap_block_state14))) and (ap_const_logic_1 = ap_CS_fsm_state14) and (is_col0_reg_652 = ap_const_lv1_0)) or ((ap_const_logic_1 = ap_CS_fsm_state9) and (ap_const_boolean_0 = ap_block_state9) and (or_ln156_reg_682 = ap_const_lv1_0)))) then 
            in_left_TREADY_int_regslice <= ap_const_logic_1;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state16) and (is_col0_reg_652 = ap_const_lv1_0))) then 
            in_left_TREADY_int_regslice <= grp_load_Pipeline_IN_PASS5_fu_249_in_left_TREADY;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
            in_left_TREADY_int_regslice <= grp_load_Pipeline_CROSS_fu_207_in_left_TREADY;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state6) or ((ap_const_logic_1 = ap_CS_fsm_state5) and (is_col0_reg_652 = ap_const_lv1_1)) or ((ap_const_logic_1 = ap_CS_fsm_state8) and (ap_predicate_op61_call_state8 = ap_const_boolean_1)))) then 
            in_left_TREADY_int_regslice <= grp_frame_group_fu_169_in_left_TREADY;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            in_left_TREADY_int_regslice <= grp_load_Pipeline_PICK_fu_146_in_left_TREADY;
        else 
            in_left_TREADY_int_regslice <= ap_const_logic_0;
        end if; 
    end process;


    in_up_TDATA_blk_n_assign_proc : process(ap_CS_fsm_state9, or_ln157_fu_429_p2, ap_CS_fsm_state12, or_ln169_reg_689, in_up_TVALID_int_regslice)
    begin
        if ((((ap_const_logic_1 = ap_CS_fsm_state12) and (or_ln169_reg_689 = ap_const_lv1_0)) or ((ap_const_logic_1 = ap_CS_fsm_state9) and (or_ln157_fu_429_p2 = ap_const_lv1_0)))) then 
            in_up_TDATA_blk_n <= in_up_TVALID_int_regslice;
        else 
            in_up_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    in_up_TREADY <= regslice_both_in_up_V_data_V_U_ack_in;

    in_up_TREADY_int_regslice_assign_proc : process(ap_CS_fsm_state9, ap_CS_fsm_state14, is_col0_reg_652, or_ln157_fu_429_p2, ap_CS_fsm_state12, or_ln169_reg_689, ap_CS_fsm_state8, ap_predicate_op61_call_state8, ap_block_state9, grp_load_Pipeline_PICK_fu_146_in_up_TREADY, grp_frame_group_fu_169_in_up_TREADY, grp_load_Pipeline_CROSS_fu_207_in_up_TREADY, grp_load_Pipeline_IN_PASS_fu_233_in_up_TREADY, ap_CS_fsm_state3, ap_CS_fsm_state5, ap_CS_fsm_state6, ap_CS_fsm_state11, ap_block_state12)
    begin
        if ((((ap_const_logic_1 = ap_CS_fsm_state12) and (ap_const_boolean_0 = ap_block_state12) and (or_ln169_reg_689 = ap_const_lv1_0)) or ((ap_const_logic_1 = ap_CS_fsm_state9) and (ap_const_boolean_0 = ap_block_state9) and (or_ln157_fu_429_p2 = ap_const_lv1_0)))) then 
            in_up_TREADY_int_regslice <= ap_const_logic_1;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state14) and (or_ln169_reg_689 = ap_const_lv1_0))) then 
            in_up_TREADY_int_regslice <= grp_load_Pipeline_IN_PASS_fu_233_in_up_TREADY;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
            in_up_TREADY_int_regslice <= grp_load_Pipeline_CROSS_fu_207_in_up_TREADY;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state6) or ((ap_const_logic_1 = ap_CS_fsm_state5) and (is_col0_reg_652 = ap_const_lv1_1)) or ((ap_const_logic_1 = ap_CS_fsm_state8) and (ap_predicate_op61_call_state8 = ap_const_boolean_1)))) then 
            in_up_TREADY_int_regslice <= grp_frame_group_fu_169_in_up_TREADY;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            in_up_TREADY_int_regslice <= grp_load_Pipeline_PICK_fu_146_in_up_TREADY;
        else 
            in_up_TREADY_int_regslice <= ap_const_logic_0;
        end if; 
    end process;


    internal_ap_ready_assign_proc : process(ap_CS_fsm_state16, ap_block_state16_on_subcall_done)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state16) and (ap_const_boolean_0 = ap_block_state16_on_subcall_done))) then 
            internal_ap_ready <= ap_const_logic_1;
        else 
            internal_ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    is_col0_fu_353_p2 <= "1" when (my_s_fu_338_p3 = ap_const_lv4_0) else "0";
    is_lastcol_fu_359_p2 <= "0" when (my_s_fu_338_p3 = ap_const_lv4_1) else "1";
    is_row0_fu_347_p2 <= "1" when (my_r_fu_329_p3 = ap_const_lv4_0) else "0";
    my_r_fu_329_p3 <= grp_load_Pipeline_PICK_fu_146_h_data_out(19 downto 16);
    my_s_fu_338_p3 <= grp_load_Pipeline_PICK_fu_146_h_data_out(15 downto 12);
    or_ln154_fu_404_p2 <= (icmp_ln139_reg_667 or icmp_ln138_reg_662);
    or_ln156_fu_424_p2 <= (is_col0_reg_652 or have_left_hdr_fu_414_p2);
    or_ln157_fu_429_p2 <= (is_row0_reg_646 or have_up_hdr_reg_677);
    or_ln169_fu_433_p2 <= (is_row0_reg_646 or is_lastcol_reg_657);
    picked_frame_fu_397_p2 <= (icmp_ln139_fu_391_p2 or icmp_ln138_fu_385_p2);

    pos_c_blk_n_assign_proc : process(pos_c_full_n, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            pos_c_blk_n <= pos_c_full_n;
        else 
            pos_c_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    pos_c_din <= grp_load_Pipeline_PICK_fu_146_h_data_out(19 downto 12);

    pos_c_write_assign_proc : process(ap_CS_fsm_state4, ap_block_state4)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) and (ap_const_boolean_0 = ap_block_state4))) then 
            pos_c_write <= ap_const_logic_1;
        else 
            pos_c_write <= ap_const_logic_0;
        end if; 
    end process;


    pos_s_blk_n_assign_proc : process(pos_s_full_n, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            pos_s_blk_n <= pos_s_full_n;
        else 
            pos_s_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    pos_s_din <= grp_load_Pipeline_PICK_fu_146_h_data_out(19 downto 12);

    pos_s_write_assign_proc : process(ap_CS_fsm_state4, ap_block_state4)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) and (ap_const_boolean_0 = ap_block_state4))) then 
            pos_s_write <= ap_const_logic_1;
        else 
            pos_s_write <= ap_const_logic_0;
        end if; 
    end process;


    real_start_assign_proc : process(ap_start, start_full_n, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (start_full_n = ap_const_logic_0))) then 
            real_start <= ap_const_logic_0;
        else 
            real_start <= ap_start;
        end if; 
    end process;

    start_out <= real_start;

    start_write_assign_proc : process(real_start, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (real_start = ap_const_logic_1))) then 
            start_write <= ap_const_logic_1;
        else 
            start_write <= ap_const_logic_0;
        end if; 
    end process;

    xa_in_din <= grp_load_Pipeline_CROSS_fu_207_xa_in_din;
    xa_in_write <= grp_load_Pipeline_CROSS_fu_207_xa_in_write;
    xb_in_din <= grp_load_Pipeline_CROSS_fu_207_xb_in_din;
    xb_in_write <= grp_load_Pipeline_CROSS_fu_207_xb_in_write;
    xor_ln154_fu_408_p2 <= (or_ln154_fu_404_p2 xor ap_const_lv1_1);
end behav;
