-- ==============================================================
-- Generated by Vitis HLS v2024.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity sa_grid_compute_Pipeline_STEP is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    xa_out_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    xa_out_full_n : IN STD_LOGIC;
    xa_out_write : OUT STD_LOGIC;
    xa_out_num_data_valid : IN STD_LOGIC_VECTOR (31 downto 0);
    xa_out_fifo_cap : IN STD_LOGIC_VECTOR (31 downto 0);
    xb_out_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    xb_out_full_n : IN STD_LOGIC;
    xb_out_write : OUT STD_LOGIC;
    xb_out_num_data_valid : IN STD_LOGIC_VECTOR (31 downto 0);
    xb_out_fifo_cap : IN STD_LOGIC_VECTOR (31 downto 0);
    xa_in_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    xa_in_empty_n : IN STD_LOGIC;
    xa_in_read : OUT STD_LOGIC;
    xa_in_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    xa_in_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    xb_in_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    xb_in_empty_n : IN STD_LOGIC;
    xb_in_read : OUT STD_LOGIC;
    xb_in_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    xb_in_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    zext_ln241 : IN STD_LOGIC_VECTOR (4 downto 0);
    bufB_9 : IN STD_LOGIC_VECTOR (15 downto 0);
    bufB_11 : IN STD_LOGIC_VECTOR (15 downto 0);
    bufB_13 : IN STD_LOGIC_VECTOR (15 downto 0);
    bufB_15 : IN STD_LOGIC_VECTOR (15 downto 0);
    zext_ln241_1 : IN STD_LOGIC_VECTOR (4 downto 0);
    bufA_9 : IN STD_LOGIC_VECTOR (15 downto 0);
    bufA_10 : IN STD_LOGIC_VECTOR (15 downto 0);
    bufA_11 : IN STD_LOGIC_VECTOR (15 downto 0);
    bufA_12 : IN STD_LOGIC_VECTOR (15 downto 0);
    bufA_13 : IN STD_LOGIC_VECTOR (15 downto 0);
    bufA_14 : IN STD_LOGIC_VECTOR (15 downto 0);
    bufA_15 : IN STD_LOGIC_VECTOR (15 downto 0);
    bufA_16 : IN STD_LOGIC_VECTOR (15 downto 0);
    bufB_10 : IN STD_LOGIC_VECTOR (15 downto 0);
    bufB_12 : IN STD_LOGIC_VECTOR (15 downto 0);
    bufB_14 : IN STD_LOGIC_VECTOR (15 downto 0);
    bufB_16 : IN STD_LOGIC_VECTOR (15 downto 0);
    empty : IN STD_LOGIC_VECTOR (3 downto 0);
    trunc_ln : IN STD_LOGIC_VECTOR (3 downto 0);
    p_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    p_out_ap_vld : OUT STD_LOGIC;
    p_out1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    p_out1_ap_vld : OUT STD_LOGIC;
    p_out2 : OUT STD_LOGIC_VECTOR (31 downto 0);
    p_out2_ap_vld : OUT STD_LOGIC;
    p_out3 : OUT STD_LOGIC_VECTOR (31 downto 0);
    p_out3_ap_vld : OUT STD_LOGIC );
end;


architecture behav of sa_grid_compute_Pipeline_STEP is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv4_B : STD_LOGIC_VECTOR (3 downto 0) := "1011";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv6_3F : STD_LOGIC_VECTOR (5 downto 0) := "111111";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal icmp_ln241_reg_1124 : STD_LOGIC_VECTOR (0 downto 0);
    signal is_lastcol_reg_1108 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_predicate_op111_write_state2 : BOOLEAN;
    signal is_lastrow_reg_1112 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_predicate_op113_write_state2 : BOOLEAN;
    signal icmp_ln194_reg_1116 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_predicate_op115_read_state2 : BOOLEAN;
    signal icmp_ln193_reg_1120 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_predicate_op126_read_state2 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1_grp1 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln241_fu_498_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal xa_out_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0_grp1 : BOOLEAN;
    signal xb_out_blk_n : STD_LOGIC;
    signal xa_in_blk_n : STD_LOGIC;
    signal xb_in_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0_11001_grp0 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone_grp0 : BOOLEAN;
    signal ap_block_pp0_stage0_11001_grp1 : BOOLEAN;
    signal is_lastcol_fu_406_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal is_lastrow_fu_412_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln194_fu_418_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln193_fu_424_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln241_reg_1124_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln241_reg_1124_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln290_fu_520_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln290_reg_1128 : STD_LOGIC_VECTOR (2 downto 0);
    signal icmp_ln290_fu_534_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln290_reg_1134 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln290_1_fu_556_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln290_1_reg_1139 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln307_fu_568_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln307_reg_1143 : STD_LOGIC_VECTOR (2 downto 0);
    signal icmp_ln307_fu_582_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln307_reg_1149 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln307_1_fu_604_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln307_1_reg_1154 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter1_stage0 : STD_LOGIC;
    signal ap_phi_mux_ref_tmp201_0_150_phi_fu_355_p6 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_reg_pp0_iter1_ref_tmp201_0_150_reg_352 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_9_fu_731_p11 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_mux_ref_tmp201_043_phi_fu_367_p6 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln297_fu_689_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_reg_pp0_iter1_ref_tmp201_043_reg_364 : STD_LOGIC_VECTOR (15 downto 0);
    signal ref_tmp201_0_fu_722_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_mux_ref_tmp241_0_148_phi_fu_378_p6 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_reg_pp0_iter1_ref_tmp241_0_148_reg_375 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_3_fu_793_p11 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_mux_ref_tmp241_045_phi_fu_390_p6 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln314_fu_751_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_reg_pp0_iter1_ref_tmp241_045_reg_387 : STD_LOGIC_VECTOR (15 downto 0);
    signal ref_tmp241_0_fu_784_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal empty_50_fu_126 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal grp_fu_897_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_sig_allocacmp_p_load7 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ref_tmp201_04246_fu_130 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal empty_51_fu_134 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal grp_fu_906_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_sig_allocacmp_p_load5 : STD_LOGIC_VECTOR (31 downto 0);
    signal ref_tmp241_04451_fu_138 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal empty_52_fu_142 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal grp_fu_915_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_sig_allocacmp_p_load3 : STD_LOGIC_VECTOR (31 downto 0);
    signal ref_tmp201_0_14952_fu_146 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal ref_tmp241_0_14753_fu_150 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal empty_53_fu_154 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal grp_fu_924_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_sig_allocacmp_p_load : STD_LOGIC_VECTOR (31 downto 0);
    signal t_fu_158 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal add_ln241_fu_504_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_sig_allocacmp_t_5 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal ref_tmp201_042_fu_162 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal ref_tmp241_044_fu_166 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal ref_tmp241_0_147_fu_170 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal ref_tmp201_0_149_fu_174 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal ap_block_pp0_stage0_01001_grp1 : BOOLEAN;
    signal zext_ln241_2_fu_510_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal zext_ln241_1_cast_fu_398_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal empty_55_fu_514_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_4_fu_524_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln290_fu_540_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_5_fu_546_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal zext_ln241_cast_fu_402_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal empty_54_fu_562_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_6_fu_572_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln307_fu_588_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_10_fu_594_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal sext_ln250_fu_639_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln250_1_fu_643_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln250_2_fu_647_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln250_3_fu_651_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln250_4_fu_655_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln250_5_fu_659_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln250_6_fu_663_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln250_7_fu_667_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal ea_fu_671_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal ea_fu_671_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal eb_fu_680_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal eb_fu_680_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_8_fu_703_p9 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_8_fu_703_p11 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_9_fu_731_p9 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_2_fu_765_p9 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_2_fu_765_p11 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_3_fu_793_p9 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_897_ce : STD_LOGIC;
    signal grp_fu_906_ce : STD_LOGIC;
    signal grp_fu_915_ce : STD_LOGIC;
    signal grp_fu_924_ce : STD_LOGIC;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal tmp_8_fu_703_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_8_fu_703_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_8_fu_703_p5 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_8_fu_703_p7 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_9_fu_731_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_9_fu_731_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_9_fu_731_p5 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_9_fu_731_p7 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_2_fu_765_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_2_fu_765_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_2_fu_765_p5 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_2_fu_765_p7 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_3_fu_793_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_3_fu_793_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_3_fu_793_p5 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_3_fu_793_p7 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component sa_grid_sparsemux_9_3_16_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        CASE0 : STD_LOGIC_VECTOR (2 downto 0);
        din0_WIDTH : INTEGER;
        CASE1 : STD_LOGIC_VECTOR (2 downto 0);
        din1_WIDTH : INTEGER;
        CASE2 : STD_LOGIC_VECTOR (2 downto 0);
        din2_WIDTH : INTEGER;
        CASE3 : STD_LOGIC_VECTOR (2 downto 0);
        din3_WIDTH : INTEGER;
        def_WIDTH : INTEGER;
        sel_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (15 downto 0);
        din2 : IN STD_LOGIC_VECTOR (15 downto 0);
        din3 : IN STD_LOGIC_VECTOR (15 downto 0);
        def : IN STD_LOGIC_VECTOR (15 downto 0);
        sel : IN STD_LOGIC_VECTOR (2 downto 0);
        dout : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;


    component sa_grid_mac_muladd_16s_16s_32ns_32_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (15 downto 0);
        din2 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component sa_grid_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    sparsemux_9_3_16_1_1_U116 : component sa_grid_sparsemux_9_3_16_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "000",
        din0_WIDTH => 16,
        CASE1 => "001",
        din1_WIDTH => 16,
        CASE2 => "010",
        din2_WIDTH => 16,
        CASE3 => "011",
        din3_WIDTH => 16,
        def_WIDTH => 16,
        sel_WIDTH => 3,
        dout_WIDTH => 16)
    port map (
        din0 => bufA_9,
        din1 => bufA_10,
        din2 => bufA_11,
        din3 => bufA_12,
        def => tmp_8_fu_703_p9,
        sel => trunc_ln290_reg_1128,
        dout => tmp_8_fu_703_p11);

    sparsemux_9_3_16_1_1_U117 : component sa_grid_sparsemux_9_3_16_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "001",
        din0_WIDTH => 16,
        CASE1 => "010",
        din1_WIDTH => 16,
        CASE2 => "011",
        din2_WIDTH => 16,
        CASE3 => "100",
        din3_WIDTH => 16,
        def_WIDTH => 16,
        sel_WIDTH => 3,
        dout_WIDTH => 16)
    port map (
        din0 => bufA_13,
        din1 => bufA_14,
        din2 => bufA_15,
        din3 => bufA_16,
        def => tmp_9_fu_731_p9,
        sel => trunc_ln290_reg_1128,
        dout => tmp_9_fu_731_p11);

    sparsemux_9_3_16_1_1_U118 : component sa_grid_sparsemux_9_3_16_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "000",
        din0_WIDTH => 16,
        CASE1 => "001",
        din1_WIDTH => 16,
        CASE2 => "010",
        din2_WIDTH => 16,
        CASE3 => "011",
        din3_WIDTH => 16,
        def_WIDTH => 16,
        sel_WIDTH => 3,
        dout_WIDTH => 16)
    port map (
        din0 => bufB_9,
        din1 => bufB_11,
        din2 => bufB_13,
        din3 => bufB_15,
        def => tmp_2_fu_765_p9,
        sel => trunc_ln307_reg_1143,
        dout => tmp_2_fu_765_p11);

    sparsemux_9_3_16_1_1_U119 : component sa_grid_sparsemux_9_3_16_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "001",
        din0_WIDTH => 16,
        CASE1 => "010",
        din1_WIDTH => 16,
        CASE2 => "011",
        din2_WIDTH => 16,
        CASE3 => "100",
        din3_WIDTH => 16,
        def_WIDTH => 16,
        sel_WIDTH => 3,
        dout_WIDTH => 16)
    port map (
        din0 => bufB_10,
        din1 => bufB_12,
        din2 => bufB_14,
        din3 => bufB_16,
        def => tmp_3_fu_793_p9,
        sel => trunc_ln307_reg_1143,
        dout => tmp_3_fu_793_p11);

    mac_muladd_16s_16s_32ns_32_4_1_U120 : component sa_grid_mac_muladd_16s_16s_32ns_32_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        din2_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => sext_ln250_fu_639_p0,
        din1 => sext_ln250_1_fu_643_p0,
        din2 => ap_sig_allocacmp_p_load7,
        ce => grp_fu_897_ce,
        dout => grp_fu_897_p3);

    mac_muladd_16s_16s_32ns_32_4_1_U121 : component sa_grid_mac_muladd_16s_16s_32ns_32_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        din2_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => sext_ln250_2_fu_647_p0,
        din1 => sext_ln250_3_fu_651_p0,
        din2 => ap_sig_allocacmp_p_load5,
        ce => grp_fu_906_ce,
        dout => grp_fu_906_p3);

    mac_muladd_16s_16s_32ns_32_4_1_U122 : component sa_grid_mac_muladd_16s_16s_32ns_32_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        din2_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => sext_ln250_4_fu_655_p0,
        din1 => sext_ln250_5_fu_659_p0,
        din2 => ap_sig_allocacmp_p_load3,
        ce => grp_fu_915_ce,
        dout => grp_fu_915_p3);

    mac_muladd_16s_16s_32ns_32_4_1_U123 : component sa_grid_mac_muladd_16s_16s_32ns_32_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        din2_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => sext_ln250_6_fu_663_p0,
        din1 => sext_ln250_7_fu_667_p0,
        din2 => ap_sig_allocacmp_p_load,
        ce => grp_fu_924_ce,
        dout => grp_fu_924_p3);

    flow_control_loop_pipe_sequential_init_U : component sa_grid_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready_pp0_iter3_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter1_stage0)) then 
                    ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    empty_50_fu_126_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    empty_50_fu_126 <= ap_const_lv32_0;
                elsif ((ap_enable_reg_pp0_iter4 = ap_const_logic_1)) then 
                    empty_50_fu_126 <= grp_fu_897_p3;
                end if;
            end if; 
        end if;
    end process;

    empty_51_fu_134_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    empty_51_fu_134 <= ap_const_lv32_0;
                elsif ((ap_enable_reg_pp0_iter4 = ap_const_logic_1)) then 
                    empty_51_fu_134 <= grp_fu_906_p3;
                end if;
            end if; 
        end if;
    end process;

    empty_52_fu_142_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    empty_52_fu_142 <= ap_const_lv32_0;
                elsif ((ap_enable_reg_pp0_iter4 = ap_const_logic_1)) then 
                    empty_52_fu_142 <= grp_fu_915_p3;
                end if;
            end if; 
        end if;
    end process;

    empty_53_fu_154_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    empty_53_fu_154 <= ap_const_lv32_0;
                elsif ((ap_enable_reg_pp0_iter4 = ap_const_logic_1)) then 
                    empty_53_fu_154 <= grp_fu_924_p3;
                end if;
            end if; 
        end if;
    end process;

    ref_tmp201_04246_fu_130_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    ref_tmp201_04246_fu_130 <= ap_const_lv16_0;
                elsif (((icmp_ln241_reg_1124 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    ref_tmp201_04246_fu_130 <= ref_tmp201_042_fu_162;
                end if;
            end if; 
        end if;
    end process;

    ref_tmp201_042_fu_162_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    ref_tmp201_042_fu_162 <= ap_const_lv16_0;
                elsif (((icmp_ln241_reg_1124 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    ref_tmp201_042_fu_162 <= ap_phi_mux_ref_tmp201_043_phi_fu_367_p6;
                end if;
            end if; 
        end if;
    end process;

    ref_tmp201_0_14952_fu_146_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    ref_tmp201_0_14952_fu_146 <= ap_const_lv16_0;
                elsif (((icmp_ln241_reg_1124 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    ref_tmp201_0_14952_fu_146 <= ref_tmp201_0_149_fu_174;
                end if;
            end if; 
        end if;
    end process;

    ref_tmp201_0_149_fu_174_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    ref_tmp201_0_149_fu_174 <= ap_const_lv16_0;
                elsif (((icmp_ln241_reg_1124 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    ref_tmp201_0_149_fu_174 <= ap_phi_mux_ref_tmp201_0_150_phi_fu_355_p6;
                end if;
            end if; 
        end if;
    end process;

    ref_tmp241_04451_fu_138_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    ref_tmp241_04451_fu_138 <= ap_const_lv16_0;
                elsif (((icmp_ln241_reg_1124 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    ref_tmp241_04451_fu_138 <= ref_tmp241_044_fu_166;
                end if;
            end if; 
        end if;
    end process;

    ref_tmp241_044_fu_166_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    ref_tmp241_044_fu_166 <= ap_const_lv16_0;
                elsif (((icmp_ln241_reg_1124 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    ref_tmp241_044_fu_166 <= ap_phi_mux_ref_tmp241_045_phi_fu_390_p6;
                end if;
            end if; 
        end if;
    end process;

    ref_tmp241_0_14753_fu_150_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    ref_tmp241_0_14753_fu_150 <= ap_const_lv16_0;
                elsif (((icmp_ln241_reg_1124 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    ref_tmp241_0_14753_fu_150 <= ref_tmp241_0_147_fu_170;
                end if;
            end if; 
        end if;
    end process;

    ref_tmp241_0_147_fu_170_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    ref_tmp241_0_147_fu_170 <= ap_const_lv16_0;
                elsif (((icmp_ln241_reg_1124 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    ref_tmp241_0_147_fu_170 <= ap_phi_mux_ref_tmp241_0_148_phi_fu_378_p6;
                end if;
            end if; 
        end if;
    end process;

    t_fu_158_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (icmp_ln241_fu_498_p2 = ap_const_lv1_0))) then 
                    t_fu_158 <= add_ln241_fu_504_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    t_fu_158 <= ap_const_lv4_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
                icmp_ln193_reg_1120 <= icmp_ln193_fu_424_p2;
                icmp_ln194_reg_1116 <= icmp_ln194_fu_418_p2;
                icmp_ln241_reg_1124 <= icmp_ln241_fu_498_p2;
                icmp_ln241_reg_1124_pp0_iter1_reg <= icmp_ln241_reg_1124;
                icmp_ln290_1_reg_1139 <= icmp_ln290_1_fu_556_p2;
                icmp_ln290_reg_1134 <= icmp_ln290_fu_534_p2;
                icmp_ln307_1_reg_1154 <= icmp_ln307_1_fu_604_p2;
                icmp_ln307_reg_1149 <= icmp_ln307_fu_582_p2;
                is_lastcol_reg_1108 <= is_lastcol_fu_406_p2;
                is_lastrow_reg_1112 <= is_lastrow_fu_412_p2;
                trunc_ln290_reg_1128 <= trunc_ln290_fu_520_p1;
                trunc_ln307_reg_1143 <= trunc_ln307_fu_568_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
                icmp_ln241_reg_1124_pp0_iter2_reg <= icmp_ln241_reg_1124_pp0_iter1_reg;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln241_fu_504_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_t_5) + unsigned(ap_const_lv4_1));
    add_ln290_fu_540_p2 <= std_logic_vector(unsigned(empty_55_fu_514_p2) + unsigned(ap_const_lv6_3F));
    add_ln307_fu_588_p2 <= std_logic_vector(unsigned(empty_54_fu_562_p2) + unsigned(ap_const_lv6_3F));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_grp1_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_state2_pp0_stage0_iter1_grp1)
    begin
                ap_block_pp0_stage0_01001_grp1 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1_grp1));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_state2_pp0_stage0_iter1_grp1)
    begin
                ap_block_pp0_stage0_11001 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1_grp1));
    end process;

        ap_block_pp0_stage0_11001_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_11001_grp1_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_state2_pp0_stage0_iter1_grp1)
    begin
                ap_block_pp0_stage0_11001_grp1 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1_grp1));
    end process;

        ap_block_pp0_stage0_grp1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_state2_pp0_stage0_iter1_grp1)
    begin
                ap_block_pp0_stage0_subdone <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1_grp1));
    end process;

        ap_block_pp0_stage0_subdone_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state2_pp0_stage0_iter1_grp1_assign_proc : process(xa_out_full_n, xb_out_full_n, xa_in_empty_n, xb_in_empty_n, ap_predicate_op111_write_state2, ap_predicate_op113_write_state2, ap_predicate_op115_read_state2, ap_predicate_op126_read_state2)
    begin
                ap_block_state2_pp0_stage0_iter1_grp1 <= (((ap_predicate_op126_read_state2 = ap_const_boolean_1) and (xb_in_empty_n = ap_const_logic_0)) or ((ap_predicate_op115_read_state2 = ap_const_boolean_1) and (xa_in_empty_n = ap_const_logic_0)) or ((ap_predicate_op113_write_state2 = ap_const_boolean_1) and (xb_out_full_n = ap_const_logic_0)) or ((ap_predicate_op111_write_state2 = ap_const_boolean_1) and (xa_out_full_n = ap_const_logic_0)));
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln241_fu_498_p2)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln241_fu_498_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_condition_exit_pp0_iter1_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln241_reg_1124, ap_block_pp0_stage0_subdone)
    begin
        if (((icmp_ln241_reg_1124 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_loop_exit_ready_pp0_iter3_reg, ap_done_reg)
    begin
        if (((ap_loop_exit_ready_pp0_iter3_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4)
    begin
        if (((ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;

    ap_phi_mux_ref_tmp201_043_phi_fu_367_p6_assign_proc : process(icmp_ln241_reg_1124, icmp_ln194_reg_1116, icmp_ln290_1_reg_1139, trunc_ln297_fu_689_p1, ap_phi_reg_pp0_iter1_ref_tmp201_043_reg_364, ref_tmp201_0_fu_722_p3)
    begin
        if ((((icmp_ln194_reg_1116 = ap_const_lv1_1) and (icmp_ln241_reg_1124 = ap_const_lv1_0) and (icmp_ln290_1_reg_1139 = ap_const_lv1_0)) or ((icmp_ln194_reg_1116 = ap_const_lv1_1) and (icmp_ln241_reg_1124 = ap_const_lv1_0) and (icmp_ln290_1_reg_1139 = ap_const_lv1_1)))) then 
            ap_phi_mux_ref_tmp201_043_phi_fu_367_p6 <= ref_tmp201_0_fu_722_p3;
        elsif (((icmp_ln194_reg_1116 = ap_const_lv1_0) and (icmp_ln241_reg_1124 = ap_const_lv1_0))) then 
            ap_phi_mux_ref_tmp201_043_phi_fu_367_p6 <= trunc_ln297_fu_689_p1;
        else 
            ap_phi_mux_ref_tmp201_043_phi_fu_367_p6 <= ap_phi_reg_pp0_iter1_ref_tmp201_043_reg_364;
        end if; 
    end process;


    ap_phi_mux_ref_tmp201_0_150_phi_fu_355_p6_assign_proc : process(xa_in_dout, icmp_ln241_reg_1124, icmp_ln194_reg_1116, icmp_ln290_1_reg_1139, ap_phi_reg_pp0_iter1_ref_tmp201_0_150_reg_352, tmp_9_fu_731_p11)
    begin
        if ((icmp_ln241_reg_1124 = ap_const_lv1_0)) then
            if (((icmp_ln194_reg_1116 = ap_const_lv1_1) and (icmp_ln290_1_reg_1139 = ap_const_lv1_0))) then 
                ap_phi_mux_ref_tmp201_0_150_phi_fu_355_p6 <= ap_const_lv16_0;
            elsif (((icmp_ln194_reg_1116 = ap_const_lv1_1) and (icmp_ln290_1_reg_1139 = ap_const_lv1_1))) then 
                ap_phi_mux_ref_tmp201_0_150_phi_fu_355_p6 <= tmp_9_fu_731_p11;
            elsif ((icmp_ln194_reg_1116 = ap_const_lv1_0)) then 
                ap_phi_mux_ref_tmp201_0_150_phi_fu_355_p6 <= xa_in_dout(31 downto 16);
            else 
                ap_phi_mux_ref_tmp201_0_150_phi_fu_355_p6 <= ap_phi_reg_pp0_iter1_ref_tmp201_0_150_reg_352;
            end if;
        else 
            ap_phi_mux_ref_tmp201_0_150_phi_fu_355_p6 <= ap_phi_reg_pp0_iter1_ref_tmp201_0_150_reg_352;
        end if; 
    end process;


    ap_phi_mux_ref_tmp241_045_phi_fu_390_p6_assign_proc : process(icmp_ln241_reg_1124, icmp_ln193_reg_1120, icmp_ln307_1_reg_1154, trunc_ln314_fu_751_p1, ap_phi_reg_pp0_iter1_ref_tmp241_045_reg_387, ref_tmp241_0_fu_784_p3)
    begin
        if ((((icmp_ln193_reg_1120 = ap_const_lv1_1) and (icmp_ln241_reg_1124 = ap_const_lv1_0) and (icmp_ln307_1_reg_1154 = ap_const_lv1_0)) or ((icmp_ln193_reg_1120 = ap_const_lv1_1) and (icmp_ln241_reg_1124 = ap_const_lv1_0) and (icmp_ln307_1_reg_1154 = ap_const_lv1_1)))) then 
            ap_phi_mux_ref_tmp241_045_phi_fu_390_p6 <= ref_tmp241_0_fu_784_p3;
        elsif (((icmp_ln193_reg_1120 = ap_const_lv1_0) and (icmp_ln241_reg_1124 = ap_const_lv1_0))) then 
            ap_phi_mux_ref_tmp241_045_phi_fu_390_p6 <= trunc_ln314_fu_751_p1;
        else 
            ap_phi_mux_ref_tmp241_045_phi_fu_390_p6 <= ap_phi_reg_pp0_iter1_ref_tmp241_045_reg_387;
        end if; 
    end process;


    ap_phi_mux_ref_tmp241_0_148_phi_fu_378_p6_assign_proc : process(xb_in_dout, icmp_ln241_reg_1124, icmp_ln193_reg_1120, icmp_ln307_1_reg_1154, ap_phi_reg_pp0_iter1_ref_tmp241_0_148_reg_375, tmp_3_fu_793_p11)
    begin
        if ((icmp_ln241_reg_1124 = ap_const_lv1_0)) then
            if (((icmp_ln193_reg_1120 = ap_const_lv1_1) and (icmp_ln307_1_reg_1154 = ap_const_lv1_0))) then 
                ap_phi_mux_ref_tmp241_0_148_phi_fu_378_p6 <= ap_const_lv16_0;
            elsif (((icmp_ln193_reg_1120 = ap_const_lv1_1) and (icmp_ln307_1_reg_1154 = ap_const_lv1_1))) then 
                ap_phi_mux_ref_tmp241_0_148_phi_fu_378_p6 <= tmp_3_fu_793_p11;
            elsif ((icmp_ln193_reg_1120 = ap_const_lv1_0)) then 
                ap_phi_mux_ref_tmp241_0_148_phi_fu_378_p6 <= xb_in_dout(31 downto 16);
            else 
                ap_phi_mux_ref_tmp241_0_148_phi_fu_378_p6 <= ap_phi_reg_pp0_iter1_ref_tmp241_0_148_reg_375;
            end if;
        else 
            ap_phi_mux_ref_tmp241_0_148_phi_fu_378_p6 <= ap_phi_reg_pp0_iter1_ref_tmp241_0_148_reg_375;
        end if; 
    end process;

    ap_phi_reg_pp0_iter1_ref_tmp201_043_reg_364 <= "XXXXXXXXXXXXXXXX";
    ap_phi_reg_pp0_iter1_ref_tmp201_0_150_reg_352 <= "XXXXXXXXXXXXXXXX";
    ap_phi_reg_pp0_iter1_ref_tmp241_045_reg_387 <= "XXXXXXXXXXXXXXXX";
    ap_phi_reg_pp0_iter1_ref_tmp241_0_148_reg_375 <= "XXXXXXXXXXXXXXXX";

    ap_predicate_op111_write_state2_assign_proc : process(icmp_ln241_reg_1124, is_lastcol_reg_1108)
    begin
                ap_predicate_op111_write_state2 <= ((is_lastcol_reg_1108 = ap_const_lv1_0) and (icmp_ln241_reg_1124 = ap_const_lv1_0));
    end process;


    ap_predicate_op113_write_state2_assign_proc : process(icmp_ln241_reg_1124, is_lastrow_reg_1112)
    begin
                ap_predicate_op113_write_state2 <= ((is_lastrow_reg_1112 = ap_const_lv1_0) and (icmp_ln241_reg_1124 = ap_const_lv1_0));
    end process;


    ap_predicate_op115_read_state2_assign_proc : process(icmp_ln241_reg_1124, icmp_ln194_reg_1116)
    begin
                ap_predicate_op115_read_state2 <= ((icmp_ln194_reg_1116 = ap_const_lv1_0) and (icmp_ln241_reg_1124 = ap_const_lv1_0));
    end process;


    ap_predicate_op126_read_state2_assign_proc : process(icmp_ln241_reg_1124, icmp_ln193_reg_1120)
    begin
                ap_predicate_op126_read_state2 <= ((icmp_ln193_reg_1120 = ap_const_lv1_0) and (icmp_ln241_reg_1124 = ap_const_lv1_0));
    end process;

    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_p_load_assign_proc : process(ap_enable_reg_pp0_iter4, ap_block_pp0_stage0_grp1, empty_53_fu_154, grp_fu_924_p3)
    begin
        if (((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_grp1))) then 
            ap_sig_allocacmp_p_load <= grp_fu_924_p3;
        else 
            ap_sig_allocacmp_p_load <= empty_53_fu_154;
        end if; 
    end process;


    ap_sig_allocacmp_p_load3_assign_proc : process(ap_enable_reg_pp0_iter4, ap_block_pp0_stage0_grp1, empty_52_fu_142, grp_fu_915_p3)
    begin
        if (((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_grp1))) then 
            ap_sig_allocacmp_p_load3 <= grp_fu_915_p3;
        else 
            ap_sig_allocacmp_p_load3 <= empty_52_fu_142;
        end if; 
    end process;


    ap_sig_allocacmp_p_load5_assign_proc : process(ap_enable_reg_pp0_iter4, ap_block_pp0_stage0_grp1, empty_51_fu_134, grp_fu_906_p3)
    begin
        if (((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_grp1))) then 
            ap_sig_allocacmp_p_load5 <= grp_fu_906_p3;
        else 
            ap_sig_allocacmp_p_load5 <= empty_51_fu_134;
        end if; 
    end process;


    ap_sig_allocacmp_p_load7_assign_proc : process(ap_enable_reg_pp0_iter4, ap_block_pp0_stage0_grp1, empty_50_fu_126, grp_fu_897_p3)
    begin
        if (((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_grp1))) then 
            ap_sig_allocacmp_p_load7 <= grp_fu_897_p3;
        else 
            ap_sig_allocacmp_p_load7 <= empty_50_fu_126;
        end if; 
    end process;


    ap_sig_allocacmp_t_5_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_loop_init, t_fu_158, ap_block_pp0_stage0)
    begin
        if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            ap_sig_allocacmp_t_5 <= ap_const_lv4_0;
        else 
            ap_sig_allocacmp_t_5 <= t_fu_158;
        end if; 
    end process;

    ea_fu_671_p1 <= ref_tmp201_0_14952_fu_146;
    ea_fu_671_p2 <= ref_tmp201_04246_fu_130;
    eb_fu_680_p1 <= ref_tmp241_0_14753_fu_150;
    eb_fu_680_p2 <= ref_tmp241_04451_fu_138;
    empty_54_fu_562_p2 <= std_logic_vector(unsigned(zext_ln241_2_fu_510_p1) - unsigned(zext_ln241_cast_fu_402_p1));
    empty_55_fu_514_p2 <= std_logic_vector(unsigned(zext_ln241_2_fu_510_p1) - unsigned(zext_ln241_1_cast_fu_398_p1));

    grp_fu_897_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1))) then 
            grp_fu_897_ce <= ap_const_logic_1;
        else 
            grp_fu_897_ce <= ap_const_logic_0;
        end if; 
    end process;


    grp_fu_906_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1))) then 
            grp_fu_906_ce <= ap_const_logic_1;
        else 
            grp_fu_906_ce <= ap_const_logic_0;
        end if; 
    end process;


    grp_fu_915_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1))) then 
            grp_fu_915_ce <= ap_const_logic_1;
        else 
            grp_fu_915_ce <= ap_const_logic_0;
        end if; 
    end process;


    grp_fu_924_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1))) then 
            grp_fu_924_ce <= ap_const_logic_1;
        else 
            grp_fu_924_ce <= ap_const_logic_0;
        end if; 
    end process;

    icmp_ln193_fu_424_p2 <= "1" when (trunc_ln = ap_const_lv4_0) else "0";
    icmp_ln194_fu_418_p2 <= "1" when (empty = ap_const_lv4_0) else "0";
    icmp_ln241_fu_498_p2 <= "1" when (ap_sig_allocacmp_t_5 = ap_const_lv4_B) else "0";
    icmp_ln290_1_fu_556_p2 <= "1" when (tmp_5_fu_546_p4 = ap_const_lv4_0) else "0";
    icmp_ln290_fu_534_p2 <= "1" when (tmp_4_fu_524_p4 = ap_const_lv4_0) else "0";
    icmp_ln307_1_fu_604_p2 <= "1" when (tmp_10_fu_594_p4 = ap_const_lv4_0) else "0";
    icmp_ln307_fu_582_p2 <= "1" when (tmp_6_fu_572_p4 = ap_const_lv4_0) else "0";
    is_lastcol_fu_406_p2 <= "1" when (empty = ap_const_lv4_1) else "0";
    is_lastrow_fu_412_p2 <= "1" when (trunc_ln = ap_const_lv4_1) else "0";
    p_out <= empty_53_fu_154;
    p_out1 <= empty_52_fu_142;

    p_out1_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001_grp1, icmp_ln241_reg_1124_pp0_iter2_reg, ap_loop_exit_ready_pp0_iter3_reg)
    begin
        if (((ap_loop_exit_ready_pp0_iter3_reg = ap_const_logic_1) and (icmp_ln241_reg_1124_pp0_iter2_reg = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1))) then 
            p_out1_ap_vld <= ap_const_logic_1;
        else 
            p_out1_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    p_out2 <= empty_51_fu_134;

    p_out2_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001_grp1, icmp_ln241_reg_1124_pp0_iter2_reg, ap_loop_exit_ready_pp0_iter3_reg)
    begin
        if (((ap_loop_exit_ready_pp0_iter3_reg = ap_const_logic_1) and (icmp_ln241_reg_1124_pp0_iter2_reg = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1))) then 
            p_out2_ap_vld <= ap_const_logic_1;
        else 
            p_out2_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    p_out3 <= empty_50_fu_126;

    p_out3_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001_grp1, icmp_ln241_reg_1124_pp0_iter2_reg, ap_loop_exit_ready_pp0_iter3_reg)
    begin
        if (((ap_loop_exit_ready_pp0_iter3_reg = ap_const_logic_1) and (icmp_ln241_reg_1124_pp0_iter2_reg = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1))) then 
            p_out3_ap_vld <= ap_const_logic_1;
        else 
            p_out3_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    p_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001_grp1, icmp_ln241_reg_1124_pp0_iter2_reg, ap_loop_exit_ready_pp0_iter3_reg)
    begin
        if (((ap_loop_exit_ready_pp0_iter3_reg = ap_const_logic_1) and (icmp_ln241_reg_1124_pp0_iter2_reg = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1))) then 
            p_out_ap_vld <= ap_const_logic_1;
        else 
            p_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    ref_tmp201_0_fu_722_p3 <= 
        tmp_8_fu_703_p11 when (icmp_ln290_reg_1134(0) = '1') else 
        ap_const_lv16_0;
    ref_tmp241_0_fu_784_p3 <= 
        tmp_2_fu_765_p11 when (icmp_ln307_reg_1149(0) = '1') else 
        ap_const_lv16_0;
    sext_ln250_1_fu_643_p0 <= ref_tmp241_044_fu_166;
    sext_ln250_2_fu_647_p0 <= ref_tmp201_04246_fu_130;
    sext_ln250_3_fu_651_p0 <= ref_tmp241_0_147_fu_170;
    sext_ln250_4_fu_655_p0 <= ref_tmp201_0_149_fu_174;
    sext_ln250_5_fu_659_p0 <= ref_tmp241_04451_fu_138;
    sext_ln250_6_fu_663_p0 <= ref_tmp201_0_14952_fu_146;
    sext_ln250_7_fu_667_p0 <= ref_tmp241_0_14753_fu_150;
    sext_ln250_fu_639_p0 <= ref_tmp201_042_fu_162;
    tmp_10_fu_594_p4 <= add_ln307_fu_588_p2(5 downto 2);
    tmp_2_fu_765_p9 <= "XXXXXXXXXXXXXXXX";
    tmp_3_fu_793_p9 <= "XXXXXXXXXXXXXXXX";
    tmp_4_fu_524_p4 <= empty_55_fu_514_p2(5 downto 2);
    tmp_5_fu_546_p4 <= add_ln290_fu_540_p2(5 downto 2);
    tmp_6_fu_572_p4 <= empty_54_fu_562_p2(5 downto 2);
    tmp_8_fu_703_p9 <= "XXXXXXXXXXXXXXXX";
    tmp_9_fu_731_p9 <= "XXXXXXXXXXXXXXXX";
    trunc_ln290_fu_520_p1 <= empty_55_fu_514_p2(3 - 1 downto 0);
    trunc_ln297_fu_689_p1 <= xa_in_dout(16 - 1 downto 0);
    trunc_ln307_fu_568_p1 <= empty_54_fu_562_p2(3 - 1 downto 0);
    trunc_ln314_fu_751_p1 <= xb_in_dout(16 - 1 downto 0);

    xa_in_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, xa_in_empty_n, ap_predicate_op115_read_state2, ap_block_pp0_stage0_grp1)
    begin
        if (((ap_predicate_op115_read_state2 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_grp1))) then 
            xa_in_blk_n <= xa_in_empty_n;
        else 
            xa_in_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    xa_in_read_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_predicate_op115_read_state2, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_predicate_op115_read_state2 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1))) then 
            xa_in_read <= ap_const_logic_1;
        else 
            xa_in_read <= ap_const_logic_0;
        end if; 
    end process;


    xa_out_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, xa_out_full_n, ap_predicate_op111_write_state2, ap_block_pp0_stage0_grp1)
    begin
        if (((ap_predicate_op111_write_state2 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_grp1))) then 
            xa_out_blk_n <= xa_out_full_n;
        else 
            xa_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    xa_out_din <= (ea_fu_671_p1 & ea_fu_671_p2);

    xa_out_write_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_predicate_op111_write_state2, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_predicate_op111_write_state2 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1))) then 
            xa_out_write <= ap_const_logic_1;
        else 
            xa_out_write <= ap_const_logic_0;
        end if; 
    end process;


    xb_in_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, xb_in_empty_n, ap_predicate_op126_read_state2, ap_block_pp0_stage0_grp1)
    begin
        if (((ap_predicate_op126_read_state2 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_grp1))) then 
            xb_in_blk_n <= xb_in_empty_n;
        else 
            xb_in_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    xb_in_read_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_predicate_op126_read_state2, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_predicate_op126_read_state2 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1))) then 
            xb_in_read <= ap_const_logic_1;
        else 
            xb_in_read <= ap_const_logic_0;
        end if; 
    end process;


    xb_out_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, xb_out_full_n, ap_predicate_op113_write_state2, ap_block_pp0_stage0_grp1)
    begin
        if (((ap_predicate_op113_write_state2 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_grp1))) then 
            xb_out_blk_n <= xb_out_full_n;
        else 
            xb_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    xb_out_din <= (eb_fu_680_p1 & eb_fu_680_p2);

    xb_out_write_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_predicate_op113_write_state2, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_predicate_op113_write_state2 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1))) then 
            xb_out_write <= ap_const_logic_1;
        else 
            xb_out_write <= ap_const_logic_0;
        end if; 
    end process;

    zext_ln241_1_cast_fu_398_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(zext_ln241_1),6));
    zext_ln241_2_fu_510_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_sig_allocacmp_t_5),6));
    zext_ln241_cast_fu_402_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(zext_ln241),6));
end behav;
